### ISSUE TITLE
Incorrect error message displayed when iso unavailable

### ISSUE THREAD

**Issue by jourdan** [FedoraQt/MediaWriter#100]
Recently attempting to write fedora 26 workstation edition from fedora 25 install of media writer '4.1.0-1.fc25.x86_64' and got a message saying "destination drive is not writable".  Went to getfedora.org to download it myself and received an nginx error.  Switched to write server edition and it worked just fine.

**Comment by MartinBriza** [comment]
So did the file get downloaded? I think the "destination drive not writable" error happens only when writing an image to a flash drive.

**Comment by grulja** [comment]
Possibly no longer an issue. Feel free to re-open if you can still reproduce with FMW 4.2.1.
