### ISSUE TITLE
Restore not working 

### ISSUE THREAD

**Issue by sameer615** [FedoraQt/MediaWriter#147]
hello 
i was installing using custom image file and unfortunately my fadora media writer got stopped while writing to disk now the USB drive is not showing and restore option appearing on the top but when i'm doing the restore. its not restoring anything .

and now USB is not even mounting

**Comment by MartinBriza** [comment]
Can you please specify the operating system and FMW versions?

**Comment by sameer615** [comment]
I'm using windows 10 and FMW 4.1.0

**Comment by MartinBriza** [comment]
Try FMW 4.1.1 from the Releases section here on Github. In case it doesn't work, you'll have to use the Windows Partition manager (instructions here: https://www.howtogeek.com/101862/how-to-manage-partitions-on-windows-without-downloading-any-other-software/ ). Please don't hesitate to contact me for further information.

**Comment by grulja** [comment]
Closing now as it's 3 years old issue. Please feel free to re-open if the issue is still reproducible with FMW 4.2.1.
