### ISSUE TITLE
Checking the written data - prog. sems to have stalled

### ISSUE THREAD

**Issue by deafandy** [FedoraQt/MediaWriter#148]
so, it's been about 20 minutes, and it's still stuck on checking the written data... 
i'm guessing it shouldn't take this long...?

specs: 
portable HDD on USB 2.0; i5 2500K (stock speed) on gigabyte GA-Z68XP-UDP3; 8GB ram; HD7850 graphics 
(yes it's an old beast, but it runs pretty fast and smooth and rarely crashes)
i want to (try and) install fedora on a laptop, not this PC. the laptop is an Acer cloudbook, N3050 CPU, 2GB ram

**Comment by deafandy** [comment]
okay... just tried again with version 4.1.0 ... appeared to have worked - "your drive may appear smaller" - no kidding, it's not even showing in 'my computer'...

**Comment by wolfv6** [comment]
I got the same error installing Fedora Workstation 27, and I am using the same USB stick that worked when installing Fedora Workstation 26.

**Comment by MartinBriza** [comment]
Did you use the "write after downloading" checkbox or did you start writing manually?

**Comment by wolfv6** [comment]
@MartinBriza I was using Fedora Workstation 26.

**Comment by shvr** [comment]
I've run into this issue as well. For me, it's only been hit when selecting the "write after downloading" checkbox. The ISO appears to be written, it's just MediaWriter hangs and and won't finish verifying the write (I've waited at least ten minutes after the progress bar finished).

This has happened on an up to date Windows 10 and Fedora Workstation 27 using MediaWriter version 4.1.1. No crash log is generated and nothing is output about it when running MediaWriter from the command line.

**Comment by sanjabonic** [comment]
Same results as @shvr here, except for using Fedora Media Writer on Fedora Workstation 27.

**Comment by tjackson** [comment]
I got the same stall on the checking the written data just now on updated Windows 10. Also, under apps and features instead of reporting the writer version it shows up as "${VERSIONMAJOR.${VERSIONMINOR}"... but I downloaded it about half an hour ago if that indicates the version, for Fedora 28.

With a second write it finishes promptly.

**Comment by SteeveDroz** [comment]
I may have a lead: when clicking the "write after downloading" ckeckbox, a prompt asks for my password. The download time may be longer than the time the password is stored.

Try not to use that option, unless your download speed makes us all envious.

I had the same problem. Clicking "cancel" and then "Create liveUSB" again worked fine.

**Comment by JLMOX** [comment]
SteeveDross' solution worked fine (cancel then press Create Live USB again). On my second attempt I got the message finished.

**Comment by jermch** [comment]
Downloaded FedoraMediaWriter-win32-4.1.1.exe on 7/31.  Same issue as I selected the write after downloading" option.  The FMW app was not responding as it stopped during verifying .  I was however able to boot and install from the USB media.  

Developers should look into this issue

**Comment by laidan6000** [comment]
I just hit the same issue using Fedora 28. Cancelling and then trying again doesn't work for me.

**Comment by laidan6000** [comment]
I resolved the issue by logging into Fedora as the root user and then running MediaWriter from there, using a blank USB drive. As suggested above, I deselected the "Write after downloading" checkbox.

**Comment by avanemanic** [comment]
I had the same issue when I checked "write after downloading", but it worked after re-writing the disk.

**Comment by giteauser** [comment]
Same problem. Windows 10 1803

**Comment by joshwaiam** [comment]
I've had the same issue.  Windows 10, all updated.  Just downloaded Fedora Media Writer an hour ago.  I did check to automatically write after download on the attempt that stalled on "Checking the written data."

**Comment by lukemgriffith** [comment]
I am also getting this on Windows 10 1803. I used the write after download option.

**Comment by polatsinan** [comment]
Have the same problem, it takes forever to check the written data. Windows 10 and checked the box to start write after downloading.
The issue was opened a year ago, still no fix?

**Comment by iptaylortechnical** [comment]
Just had this issue after checking "write after downloading."

**Comment by MartinBriza** [comment]
Oh yeah, I've got to admit that feature doesn't work _exactly_ as I'd like it to. I'll try to do something about it.
Also, I'm sorry for keeping you guys waiting so long, I've not been completely present in this repo for a while now... I'll try to be a better maintainer

**Comment by dreadnoughtc** [comment]
same issue (and fix) for f29 
dont check the box and if you did; cancel and create USB once again

**Comment by vaporwavie** [comment]
Can confirm: this also happened to me. The way around is basically what @SteeveDroz said. Just to clarify and also to be in the same boat, I checked the "Write after downloading" checkbox before starting the whole process for the first time.

**Comment by MartinBriza** [comment]
Good news guys! I seem to have a fix for this. For the curious developers, it's in the `fix/delayed-write` branch. Expect a new release soonish.

**Comment by MartinBriza** [comment]
Fixed with 5a38833deda9ed4cc57a3d95424466848e0b4279

**Comment by kevr** [comment]
> Downloaded FedoraMediaWriter-win32-4.1.1.exe on 7/31. Same issue as I selected the write after downloading" option. The FMW app was not responding as it stopped during verifying . I was however able to boot and install from the USB media.
> 
> Developers should look into this issue. I have a very fast connection... did not see any prompt for password though.

Gotta be the douchiest issue post I've ever seen.
