### ISSUE TITLE
Mac version spins up the dGPU. 

### ISSUE THREAD

**Issue by egriffith** [FedoraQt/MediaWriter#151]
I'm not sure what would be valuable information to provide but the Mac version of MediaWriter (4.1.0) causes the dedicated GPU to spin up according to GfxCardStatus. Considering nothing MediaWriter does is GPU accelerated (or is it?) I don't see any reason for it to do so. All MediaWriter is really doing with the dGPU is wasting power and spinning up more heat. A fix would be highly appreciated by all of us road-warriors who are also Linux enthusiasts.

**Comment by MartinBriza** [comment]
The thing is, it actually is GPU accelerated. However you're right it's just wasting power. I have switched to using the nonaccelerated software-rendered QML backend on Linux and Windows and I guess doing the same will be a good idea on macOS. I'll check if it's possible to force using the iGPU instead and if I find no reasonable solution, I'll just disable acceleration altogether.
Thanks for raising this concern!

**Comment by verdurin** [comment]
Ah - this explains why I was seeing so much heat generated on my MacBook Pro. Interesting.

**Comment by joona0825** [comment]
Is it the reason why I can hear the fan spinning? I saw 120% of CPU usage. But mysterious thing is, it only happens when I download the image file
