### ISSUE TITLE
Crashes when trying to write or clean

### ISSUE THREAD

**Issue by kenny-w1** [FedoraQt/MediaWriter#162]
W@15518ms: QBackingStore::endPaint() called with active painter on backingstore paint device
W@15534ms: QBackingStore::endPaint() called with active painter on backingstore paint device
W@15550ms: QBackingStore::endPaint() called with active painter on backingstore paint device
W@15567ms: QBackingStore::endPaint() called with active painter on backingstore paint device
W@15588ms: QBackingStore::endPaint() called with active painter on backingstore paint device
W@15602ms: QBackingStore::endPaint() called with active painter on backingstore paint device
Segmentation fault

https://pastebin.com/6CQ9DF5m

Whenever I try to write to a disk or clean one that already has something on it, mediawriter crashes.
Using Void Linux MUSL.

**Comment by MartinBriza** [comment]
The warnings are harmless, it's a Qt bug. Can you obtain a backtrace, by any chance, please? For example from `coredumpctl`.

**Comment by balcer** [comment]
I have got the same problem after selecting the image. 

           PID: 4461 (mediawriter)
           UID: 1000 (bbalcerzak)
           GID: 1000 (bbalcerzak)
        Signal: 11 (SEGV)
     Timestamp: Mon 2018-05-28 22:30:44 CEST (1min 1s ago)
  Command Line: mediawriter
    Executable: /usr/bin/mediawriter
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (bbalcerzak)
       Boot ID: ddd856f2b0a0420cbbb659f6ee25b461
    Machine ID: 4f385c9ac8c4464c8d2860249fb1c985
      Hostname: localhost.localdomain
       Storage: /var/lib/systemd/coredump/core.mediawriter.1000.ddd856f2b0a0420cbbb659f6ee25b461.4461.1527539444000000.lz4
       Message: Process 4461 (mediawriter) of user 1000 dumped core.
                
                Stack trace of thread 4461:
                #0  0x000055f1bf91d740 _ZNK19ReleaseArchitecture11descriptionEv (mediawriter)
                #1  0x000055f1bf91d7a1 _ZNK14ReleaseVariant4nameEv (mediawriter)
                #2  0x000055f1bf93dbd8 _ZN14ReleaseVariant18qt_static_metacallEP7QObjectN11QMetaObject4CallEiPPv (mediawriter)
                #3  0x00007f62d1797fac _ZL12loadPropertyPN3QV415ExecutionEngineEP7QObjectRK16QQmlPropertyData (libQt5Qml.so.5)
                #4  0x00007f62d1799899 _ZN3QV414QObjectWrapper14getQmlPropertyEPNS_15ExecutionEngineEP15QQmlContextDataP7QObjectPNS_6StringENS0_12RevisionModeEPb (libQt5Qml.so.5)
                #5  0x00007f62d173ec6b _ZN3QV418QQmlContextWrapper3getEPKNS_7ManagedEPNS_6StringEPb (libQt5Qml.so.5)
                #6  0x00007f62d16fd515 _ZN3QV416ExecutionContext11getPropertyEPNS_6StringE (libQt5Qml.so.5)
                #7  0x00007f62d17aec9f _ZN3QV47Runtime28method_getActivationPropertyEPNS_15ExecutionEngineEi (libQt5Qml.so.5)
                #8  0x00007f629dd30b95 n/a (n/a)
                #9  0x00007f62d16fe6ef _ZN3QV416ExecutionContext10simpleCallERNS_5ScopeEPNS_8CallDataEPNS_8FunctionE (libQt5Qml.so.5)
                #10 0x00007f62d184b239 _ZN24QQmlJavaScriptExpression8evaluateEPN3QV48CallDataEPbRNS0_5ScopeE (libQt5Qml.so.5)
                #11 0x00007f62d1855806 _ZN21QQmlNonbindingBinding8doUpdateERKN24QQmlJavaScriptExpression13DeleteWatcherE6QFlagsIN16QQmlPropertyData9WriteFlagEERN3QV45ScopeE (libQt5Qml.so.5)
                #12 0x00007f62d1852643 _ZN11QQmlBinding6updateE6QFlagsIN16QQmlPropertyData9WriteFlagEE (libQt5Qml.so.5)
                #13 0x00007f62d185f3f4 _ZN17QQmlObjectCreator8finalizeER26QQmlInstantiationInterrupt (libQt5Qml.so.5)
                #14 0x00007f62d17dd11a _ZN20QQmlIncubatorPrivate8incubateER26QQmlInstantiationInterrupt (libQt5Qml.so.5)
                #15 0x00007f62d17dd717 _ZN17QQmlEnginePrivate8incubateER13QQmlIncubatorP15QQmlContextData (libQt5Qml.so.5)
                #16 0x00007f62d18947e7 _ZN24QQmlDelegateModelPrivate6objectEN18QQmlListCompositor5GroupEiN13QQmlIncubator14IncubationModeE (libQt5Qml.so.5)
                #17 0x00007f62d1894915 _ZN17QQmlDelegateModel6objectEiN13QQmlIncubator14IncubationModeE (libQt5Qml.so.5)
                #18 0x00007f62d27ab3bf _ZN21QQuickRepeaterPrivate12requestItemsEv (libQt5Quick.so.5)
                #19 0x00007f62d27abb83 _ZN14QQuickRepeater8setModelERK8QVariant (libQt5Quick.so.5)
                #20 0x00007f62d27ad825 _ZN14QQuickRepeater18qt_static_metacallEP7QObjectN11QMetaObject4CallEiPPv (libQt5Quick.so.5)
                #21 0x00007f62d17d6da2 _ZNK16QQmlPropertyData13writePropertyEP7QObjectPv6QFlagsINS_9WriteFlagEE (libQt5Qml.so.5)
                #22 0x00007f62d17d4073 _ZN19QQmlPropertyPrivate5writeEP7QObjectRK16QQmlPropertyDataRK8QVariantP15QQmlContextData6QFlagsINS2_9WriteFlagEE (libQt5Qml.so.5)
                #23 0x00007f62d1853894 _ZN11QQmlBinding9slowWriteERK16QQmlPropertyDataS2_RKN3QV45ValueEb6QFlagsINS0_9WriteFlagEE (libQt5Qml.so.5)
                #24 0x00007f62d1854958 _ZN14GenericBindingILi0EE5writeERKN3QV45ValueEb6QFlagsIN16QQmlPropertyData9WriteFlagEE (libQt5Qml.so.5)
                #25 0x00007f62d1855956 _ZN21QQmlNonbindingBinding8doUpdateERKN24QQmlJavaScriptExpression13DeleteWatcherE6QFlagsIN16QQmlPropertyData9WriteFlagEERN3QV45ScopeE (libQt5Qml.so.5)
                #26 0x00007f62d1852643 _ZN11QQmlBinding6updateE6QFlagsIN16QQmlPropertyData9WriteFlagEE (libQt5Qml.so.5)
                #27 0x00007f62d182a1d3 _ZN12QQmlNotifier10emitNotifyEP20QQmlNotifierEndpointPPv (libQt5Qml.so.5)
                #28 0x00007f62d17c4681 _ZN8QQmlData13signalEmittedEP24QAbstractDeclarativeDataP7QObjectiPPv (libQt5Qml.so.5)
                #29 0x00007f62d1283713 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                #30 0x000055f1bf93e1e3 _ZN14ReleaseManager18qt_static_metacallEP7QObjectN11QMetaObject4CallEiPPv (mediawriter)
                #31 0x000055f1bf93ee73 _ZN14ReleaseManager11qt_metacallEN11QMetaObject4CallEiPPv (mediawriter)
                #32 0x00007f62d179cfc1 _ZN3QV414QObjectWrapper11setPropertyEPNS_15ExecutionEngineEP7QObjectP16QQmlPropertyDataRKNS_5ValueE (libQt5Qml.so.5)
                #33 0x00007f62d179def6 _ZN3QV414QObjectWrapper14setQmlPropertyEPNS_15ExecutionEngineEP15QQmlContextDataP7QObjectPNS_6StringENS0_12RevisionModeERKNS_5ValueE (libQt5Qml.so.5)

**Comment by grulja** [comment]
I'm going to close this bug now. I believe it's no longer a problem. Feel free to re-open if you can still reproduce it.
