### ISSUE TITLE
add Silverblue (previously known as Fedora Atomic Workstation) 

### ISSUE THREAD

**Issue by matthiasclasen** [FedoraQt/MediaWriter#166]
It would be great to add Sliverblue to the list of known installs in the fedora-media-writer.

It does not really fit under spins or labs - not sure where to put it. In any case, the logo and
download url can be found here: www.teamsilverblue.org

**Comment by MartinBriza** [comment]
FMW copies the Fedora website pretty much 1:1 so when it appears there, I'm going to list it the same way the website does.

**Comment by matthiasclasen** [comment]
See https://getfedora.org/workstation/download/ 

There is now a box talking about "atomic workstation" .
This will get updated for Fedora 29 to talk about "Fedora Silverblue". Can we have that in the media writer too, please ?

**Comment by MartinBriza** [comment]
Ok. I think we can do this by adding Silverblue to releases.json as a Workstation subvariant. Then it would get displayed as an alternative version to 28/29.

**Comment by matthiasclasen** [comment]
Ping. How about it ?

**Comment by rugk** [comment]
I still don't find it in v4.1.4-3.

The search cannot find it, at least.

What I find is some kind of AArch64 (??) image in the workstation version selection that also has a "Silverblue" in it's name:
![silverblue](https://user-images.githubusercontent.com/11966684/80753013-d9602480-8b2c-11ea-9231-a4950541204f.png)

AArch64 is some AMD architecture, that is not helpful for usual x86_64 users.

This is still totally confusing, as Silverblue is IMHO quite different from Workstation and should ahve
* it's own entry
* and is AFAIK also available in multiple architectures and, of course, versions 

Should I open a new issue for that?
