### ISSUE TITLE
Translation Bug

### ISSUE THREAD

**Issue by alsoGAMER** [FedoraQt/MediaWriter#167]
The phrase "Le spin di Fedora" is not shown correctly

![Screenshot of bug](https://user-images.githubusercontent.com/35269770/40301504-9a12d8b0-5cec-11e8-8853-f063ca287c7b.png)

**Comment by MartinBriza** [comment]
I think that's a translation bug. Please see https://fedora.zanata.org/iteration/view/mediawriter/master if it's translated right (it may be, though, last translations pull happened quite a while ago).
