### ISSUE TITLE
Crashes when Server selected

### ISSUE THREAD

**Issue by Flamestar98** [FedoraQt/MediaWriter#170]
Fedora Media Writer crashes when attempting to select Server.

This issue is related to both the Flatpak and Deb/RPM version, on more than one PC, and on more than one DE.

I would be happy to attach a log file, I just need someone to point me to where it is.

**Comment by flyingpimonster** [comment]
When I run Media Writer from the terminal, then select server, I get the following message: `W@5196ms: qrc:/dialogs/DownloadDialog.qml:482: TypeError: Cannot read property 'id' of null (qrc:/dialogs/DownloadDialog.qml:482)`, then a segfault.

**Comment by adamboutcher** [comment]
Can confirm in 4.1.1-1.fc28.

Selected Server and the program just exits.

**Comment by jimdhood** [comment]
Confirming same behavior as other with 4.1.1-1.fc28. Upon selecting Server, app crashes on both Windows 10 and macOS High Sierra 10.13.6.

**Comment by MartinBriza** [comment]
This is fixed with 4.1.2

**Comment by LucienMP** [comment]
> This is fixed with 4.1.2

Fedora site is still reflecting 4.1.1, came here due to that crash (Nov 27 2018)
