### ISSUE TITLE
mediawriter is unable to write on an SD card connected through an internal reader 

### ISSUE THREAD

**Issue by lruzicka** [FedoraQt/MediaWriter#171]
## Description of problem:
When I try to create a Fedora 28 Image on an SD card, mediawriter is unable to do so and throws out an error message.

## Version-Release number of selected component (if applicable):
mediawriter 4.1.1.2.fc28

## How reproducible:
Always

## Steps to Reproduce:
1. Insert the SD card
2. Run the mediawriter.
3. Click on Create Live USB.
4. Check that SD card is the target
5. Click on Write to disk.

## Actual results:

When you click **Write to disk**, an error message (*Writing failed: "Message recipient disconnected from message bus without replying"*) appears and you cannot write to the SD card.

## Expected results:
The image is written without problems.

## Additional info:

1. In the messages put to console, I have found this:
====
W@16923ms: QBackingStore::endPaint() called with active painter on backingstore paint device
W@16938ms: QBackingStore::endPaint() called with active painter on backingstore paint device
W@16939ms: Writing failed: "Message recipient disconnected from message bus without replying"
W@16940ms: QBackingStore::endPaint() called with active painter on backingstore paint device
W@16941ms: Couldn't send a notification: "org.freedesktop.DBus.Error.ServiceUnknown" - "The name org.freedesktop.Notifications was not provided by any .service files"
W@16951ms: QBackingStore::endPaint() called with active painter on backingstore paint device
W@16954ms: QBackingStore::endPaint() called with active painter on backingstore paint device
W@16958ms: QBackingStore::endPaint() called with active painter on backingstore paint device
====

2. Mediawriter writes with no problems to USB devices and SD cards connected via SATA bus (they report as sdb)
3. Mediawriter does not write to a card connected through an internal reader (reports as mmcblk0)
4. Both dd and arm-image-installer are able to create the image on that SD card (mmcblk0)

**Comment by MartinBriza** [comment]
Please try if it works with permissive or disabled SELinux.

**Comment by lruzicka** [comment]
I can confirm that it works with permissive SELinux. Do you think it is an SELinux issue?

**Comment by MartinBriza** [comment]
Yes, let's continue in the Fedora bug ( https://bugzilla.redhat.com/show_bug.cgi?id=1601903 )
