### ISSUE TITLE
Burned Windows ISO to USB isn't bootable

### ISSUE THREAD

**Issue by Futureknows** [FedoraQt/MediaWriter#172]
I've tried writing three different official Windows ISOs to a USB stick. Mediawriter writes the ISO properly but when I try to boot the BIOS doesn't see the EFI boot sector. If I inspect the disks using Ubuntu Disks utility the USB doesn't show as bootable.

Is this expected? Many tutorials say it should work.

**Comment by MartinBriza** [comment]
Yes, it is expected. Fedora Media Writer does officially support only Fedora ISOs. It works with a lot of other distribution images, too, and also some other OSes (I know it works with FreeDOS and probably some others).
However, Windows uses a different bootable disk format that Fedora and it was never intended to support it, I'm sorry about this.
