### ISSUE TITLE
Building MediaWriter in Void Linux MUSL

### ISSUE THREAD

**Issue by kyledolichev** [FedoraQt/MediaWriter#174]
Hello, I had MediaWriter working the other day on Void Linux MUSL, but unfortunately today had to re-do my Void installation, this time around MediaWriter segmentation faults when I click 'Restore'. 
For some reason I am also unable to get to the Wiki on this here github repo. It just won't load :/ 

What packages does MediaWriter use to wipe/write to USBs/etc ?

Its also spamming my terminal endlessly with 

"W@171234ms: QBackingStore::endPaint() called with active painter on backingstore paint device"

I've been using this software for years since I started using Linux, and even though I've moved on from Fedora I still use this program to create bootable USBs, thank you for creating it :D

**Comment by kyledolichev** [comment]
I have to use the flatpak app to wipe a USB, and the compiled app to write the USBs. Flatpak app crashes when I try to write a USB & compiled app crashes when I try to format a USB.

**Comment by squimrel** [comment]
It uses udisks which uses libblockdev which uses parted if I remember correctly. Most likely this segfault is related to Qt and unrelated to udisks though.
You should try to format your portable media device using `gparted`. If that works then it's most likely a Qt issue as mentioned.

**Comment by kyledolichev** [comment]
gparted works. I wonder if libblockdev-devel in the makedepends would help...

**Comment by kyledolichev** [comment]
umm.... Are you guys gonna be fixing your wiki??

**Comment by squimrel** [comment]
Great, that you solved your issue!

I don't quite understand what makedepends you're talking about. libblockdev-devel is not required to build FMW. FMW only talks to the udisks daemon via the dbus interface which does all the work.

Yeah, I guess build instructions are not document very well.
I guess for Qt5 it's the same as documented for mac and windows (qtbase, qtdeclarative and qtquickcontrols).

**Comment by kyledolichev** [comment]
It didn't solve my issue... I have all of those QT5 dependencies.

**Comment by MartinBriza** [comment]
I guess the crashes are related to your graphics drivers rather than FMW or Qt (or any dependencies) itself. Can you at least post a backtrace so we know what to look into?
Also, there is nothing on the Wiki pages here in the repository, that's why you cannot access it.

**Comment by grulja** [comment]
I guess this is no longer an issue? I will close this bug now. Feel free to re-open if the issue remains.
