### ISSUE TITLE
Can't find windows binary release for 4.1.2

### ISSUE THREAD

**Issue by jonbrock** [FedoraQt/MediaWriter#176]
Hi, on the releases page it says "NOTICE Binaries on this page won't be signed from now on!
For a signed release, please visit https://getfedora.org . There will be a few days delay between a new release and official binaries being published."

However, I can't find a download for MediaWriter on getfedora.org. I also can't find the unsigned releases on the project page. Perhaps add a direct link to the official signed release and/or add the unsigned binaries to the releases page?

**Comment by e-flex** [comment]
The official documentation also links to GitHub, https://docs.fedoraproject.org/en-US/fedora/f28/install-guide/install/Preparing_for_Installation/#sect-preparing-boot-media, that should also probably be updated.

**Comment by MartinBriza** [comment]
Hmm, the docs have to be fixed.
_The_ official way is to go to getfedora.org and download the binary there. Yeah, I mentioned there should be something here but I kind of... uhh, sorry, didn't get around to create them. Anyway, when I do, they won't be signed because my code signing certificates expired and I'm not planning to buy new ones. The official getfedora released binaries will be signed though.

**Comment by oskarb** [comment]
> The official way is to go to getfedora.org and download the binary there. 
But where? If it's there, it sure isn''t easy to find. I'm trapped in a loop of links.

**Comment by oskarb** [comment]
Ok, on getfedora.org there is nothing on this under Server. Have to click on Workstation to find link for Mediawriter (still at 4.1.1). Not entirely expected since it's the Server build I'm looking at. Expected MediaWriter to be available under both editions.

**Comment by adamboutcher** [comment]
There is still no 4.1.2 windows binary available on getfredora.org which means trying to write a server image to pen drive isn't possible 😢

**Comment by oskarb** [comment]
@adamboutcher The MediaWriter under Workstation is the same. It's just difficult to find the link.

**Comment by alexkoster** [comment]
bump.  I'm still seeing the v4.1.1 binary at [this ](https://getfedora.org/en/workstation/download/) page.  Any chance of the 4.1.2 binary being posted? Thanks,

**Comment by oskarb** [comment]
Well, now the link on that page gives you something called "FedoraMediaWriter-win32-latest.exe" which sadly lacks any version attributes:
![image](https://user-images.githubusercontent.com/482095/105838537-7e326400-5fd0-11eb-87aa-ae48cb9cd0d3.png)

When you run it, the installer also doesn't mention the version number. At least not before clicking "Install", but I assume the actual installed program will mention the version number.

Not a major problem I guess, but an unfortunate omission if it happens to be easy to fix.
