### ISSUE TITLE
no space check, no save dir options

### ISSUE THREAD

**Issue by J-Dunn** [FedoraQt/MediaWriter#177]
Hi,

1) MediaWriter does not check for space on the default destination. 

2) Neither does it allow the user to select anything other than "your download area" without even saying clearly what that destination is.

**Comment by MartinBriza** [comment]
This is a design decision. Your "Download area" is completely configurable on all three supported platforms. If your use case requires storing the ISO elsewhere, I suggest either setting the Downloads folder to something else or downloading the ISO yourself manually and then using the "Custom" option in FMW.

**Comment by J-Dunn** [comment]
That does not address the no space check issue.
