### ISSUE TITLE
MediaWriter does not display the source URL when down loading. 

### ISSUE THREAD

**Issue by J-Dunn** [FedoraQt/MediaWriter#178]
Since we are downloading something to be burned to an installation medium and to install a new OS, it would be comforting to see the source URL it is accessing actually displayed. 

The GUI interface adds ease of use but there is no reason this should prevent the basic security of seeing the source URL and being allowed to know what you are doing. 

This also relates to the issue #177 of not showing where the download is being stored and allowing this path to be selected.  Convenience of a GUI does no necessitate dumbing down the user and unnecessary obfuscation.

**Comment by MartinBriza** [comment]
This is a design decision, too. Displaying the origin URL would mean unnecessary clutter to the user interface.

**Comment by J-Dunn** [comment]
Displaying the source which is being used for my new OS is not "unnecessary clutter"  .  We've seen where blind faith attitudes gets you with FB etc recently. 

The essence of being minimalist is to provide the minimum not less than the minimum.  Since I have no idea where your prog is sources the ISOs I would like to see it.
