### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [FedoraQt/MediaWriter#180]
i've downloaded Version '4.1.1' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are missing.
all apps on macOS are supposed to contain valid version information.

**Comment by MartinBriza** [comment]
Thanks for the useful info, I'll look into it once I grab my Mac. Should be fixed with the next release.

**Comment by core-code** [comment]
awesome, thanks!
