### ISSUE TITLE
No instructions on how to fix USB stick after media writer is used

### ISSUE THREAD

**Issue by mrjohnc** [FedoraQt/MediaWriter#182]
I recently installed Fedora using MediaWriter, I now have an unusable USB stick which gives errors when I try to reformat it on Fedora, OSX and Windows 10 with no instructions on how to unbreak it. 

It would be really great if instructions were available for Fedora, Windows and OSX (only providing them for Fedora assumes that the user was able to successfully install it)

Thanks

**Comment by kartur** [comment]
Having the same problem. There is an ANACONDA partition on my drive now that I can't delete in Windows...
![untitled](https://user-images.githubusercontent.com/2276497/48478410-84c7cd00-e804-11e8-97eb-b7991684d97d.png)

**Comment by MartinBriza** [comment]
When writing to the flash drive, FMW tells you you can insert the drive again when FMW is running to restore the partition. A notification will pop up inside the app that will let you fix the problem.

However, if the flash drive is dead (doesn't seem to be @kartur 's problem but it may be what happened to @mrjohnc , there's nothing I can do). This happens pretty often especially with cheap drives. Flash memory is not very resilient if you write a lot of data to it.
