### ISSUE TITLE
Unpopulated information in Windows Programs uninstaller

### ISSUE THREAD

**Issue by cyfrost** [FedoraQt/MediaWriter#183]
Hi,

I've installed Fedora Media Writer on a Windows 10 PC and noticed that the information related to version and icon of this app were left unpopulated. Please see the below image

![untitled](https://user-images.githubusercontent.com/12471103/46995879-40c7a680-d138-11e8-998a-5d49705786ae.png)

Ideally we want the following information listed there:

Current Information Listed there:
------------------------------------
Name: Fedora Project - Fedora Media Writer - Tool to write Fedora images to flash drives
Publisher: "Fedora Project"
Version: "${MAJORVERSION}.${MINORVERSION}.${VERSIONBUILD}"
Icon: `<no icon listed>`

Desirable Information needed there:
----------------------------------------
Name: Fedora Media Writer
Publisher: Fedora Project
Version: `<current version of the program>`
Icon: `<the icon of the program>`

I can help with resolving this issue. I'm working on it, will raise a PR soon.

Thanks!

**Comment by scootergrisen** [comment]
Also would be nice if the size was there.

**Comment by cyfrost** [comment]
#185 -- has the fixes for some of these issues. Would like to see it being approved and merged 👍
