### ISSUE TITLE
Bricked the USB flash drive

### ISSUE THREAD

**Issue by erAck** [FedoraQt/MediaWriter#189]
In the middle of writing an .iso image to an USB flash drive an "Error while writing" (or some such) was displayed, after that the drive was dead. It's also not recognized as any device when reinserted or attached to another machine.
There was no ~/Documents/FedoraMediaWriter.log file.
Used mediawriter-4.1.2-1.fc28.x86_64

**Comment by MartinBriza** [comment]
The drive is dead, most likely. If you don't see it in Device Manager or Disk Management, it died.

**Comment by erAck** [comment]
I know it's dead..
First try of MediaWriter, worst outcome.
I rather continued to use Disk Image Writer (gnome-disks --restore-disk-image) that previously also wrote another image to the very same flash drive successfully.
