### ISSUE TITLE
No medium found after MediaWriter BOFH is done with it

### ISSUE THREAD

**Issue by apapsch** [FedoraQt/MediaWriter#190]
So, I innocently wanted to try out Fedora Silverblue and the website tells me that I need Fedora Media Writer. Usually I just use the venerable `dd` but today I got weak at the sight of flashy buttons and stuff and thus installed the MediaWriter flatpak. It seems the MediaWriter exhibits some serious BOFH behavior, because my thumb drive is now wasted due to some Undetermined Peripheral Corruption (Error) manifesting in "no medium found" when `dd` tries to open the device file. Needless to say, the boot fails (BIOS not finding anything bootable). I've written several different images to the thumb drive in the past and all booted fine. I don't use the drive very often, so if it's a hardware failure it must have been some cheap stuff.

```
[   70.617625] usb 4-1: new SuperSpeed Gen 1 USB device number 2 using xhci_hcd
[   70.630603] usb 4-1: New USB device found, idVendor=8564, idProduct=1000, bcdDevice=10.75
[   70.630605] usb 4-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   70.630606] usb 4-1: Product: Mass Storage Device
[   70.630607] usb 4-1: Manufacturer: JetFlash
[   70.630608] usb 4-1: SerialNumber: 09031000002244244610
[   70.672002] usb-storage 4-1:1.0: USB Mass Storage device detected
[   70.673479] scsi host6: usb-storage 4-1:1.0
[   70.673552] usbcore: registered new interface driver usb-storage
[   70.676968] usbcore: registered new interface driver uas
[   71.703906] scsi 6:0:0:0: Direct-Access     JetFlash NAND Flash       1.00 PQ: 0 ANSI: 6
[   71.706989] sd 6:0:0:0: Attached scsi generic sg1 type 0
[   71.707489] sd 6:0:0:0: [sdb] Attached SCSI removable disk
```

```
% sudo dd if=Fedora-Silverblue-ostree-x86_64-29-1.2.iso of=/dev/sdb status=progress
[sudo] password for foo: 
dd: failed to open '/dev/sdb': No medium found
```

**Comment by MartinBriza** [comment]
hey, sorry to be the bearer of bad news but if even dd doesn't find the root block device, the drive is most likely dead
