### ISSUE TITLE
UI text is small

### ISSUE THREAD

**Issue by allanday** [FedoraQt/MediaWriter#193]
Using Fedora Media Writer on Fedora 29, the UI text looks very small:

![image](https://user-images.githubusercontent.com/213068/54211375-1b697980-44d9-11e9-875b-4bd773a0f5c6.png)

This is certainly smaller than the UI text elsewhere in my Fedora system.

**Comment by TomaszGasior** [comment]
I would say: "Media Writer should not set its own font size, instead should follow default from Qt" ;)

**Comment by grulja** [comment]
Should be fixed with FMW 4.2.0.
