### ISSUE TITLE
Much slower than cp

### ISSUE THREAD

**Issue by eszlari** [FedoraQt/MediaWriter#196]
```
root@hal4000:~# time cp image.iso /dev/sdc

real    3m23,999s
user    0m0,000s
sys     0m1,012s
```

With MediaWriter (flatpak) the same image takes about `9m30s`.

OS: Kubuntu 18.10

**Comment by MartinBriza** [comment]
Hmm, I'm not saying that FMW is the fastest tool around, however:
1) are you sure using cp is the right way? for some reason i don't believe it'd boot
2) I can't really do much about it, FMW is using the org.freedesktop.UDisks2.Block.OpenForBenchmark D-Bus method to open the device and write to it using block-aligned I/O (which is usually pretty fast).

I'll close this issue but ff you're interested in more details, please go ahead and ask. However I'd suggest you open a bug report against the UDisks2 project if you're concerned about the FMW performance - this would also affect other tools using the same API, like GNOME Disks.

**Comment by eszlari** [comment]
>  for some reason i don't believe it'd boot

I have tested it, it works.

> I'll close this issue but ff you're interested in more details, please go ahead and ask.

The obvious question: Can you reproduce this?

**Comment by MartinBriza** [comment]
I have just tried it:
```
# time cp Downloads/Fedora-Server-netinst-x86_64-29-1.2.iso /dev/sdb 
cp: overwrite '/dev/sdb'? y

real    0m11.541s
user    0m0.006s
sys     0m1.198s
```
Only a small part of the data got copied, the drive doesn't boot correctly

**Comment by eszlari** [comment]
```
$ time sudo dd if=image.iso of=/dev/sdc

real    3m12,451s
user    0m0,002s
sys     0m1,036s
```

...and the system boots & works.
