### ISSUE TITLE
Update app icon

### ISSUE THREAD

**Issue by jimmac** [FedoraQt/MediaWriter#198]
With the 3.32 release of GNOME, the application icon style guidelines [have been updated](https://developer.gnome.org/hig/stable/icon-design.html.en), embracing a more geometric look with vivid colors. The number of sizes necessary has also been reduced. I'd like to propose an updated icon, keeping you in the loop from the start of the design process.

**Comment by jimmac** [comment]
Having Fedora logo part of the icon relies on having the new logo in place. So without that variable out, I'd like to also suggest simplifying the icon by using the usb-c connector despite flash media not being all too common for it yet. It's becoming more recognizable and has a more modern vibe to it:

![Fedora_media_writer 2](https://user-images.githubusercontent.com/14821/54991688-c3913f00-4fbd-11e9-9598-8a4f991e938f.png)

**Comment by jimmac** [comment]
Based on the existing logo & colors:

![Screenshot from 2019-03-26 12-08-55](https://user-images.githubusercontent.com/14821/54992606-fb998180-4fbf-11e9-9ee8-3c76c8cff71e.png)

**Comment by jimmac** [comment]
Based on the new logo design iterations it might look more like this --

![Screenshot from 2019-03-26 12-18-07](https://user-images.githubusercontent.com/14821/54993087-52ec2180-4fc1-11e9-8535-46c9d86725be.png)

**Comment by jimmac** [comment]
The latest iteration of the Fedora logo looks more like this:
![fedora-now](https://user-images.githubusercontent.com/14821/55234478-892cd980-522b-11e9-9d8a-ed1b5117c833.png)

**Comment by jimmac** [comment]
Here are the fullcolor and symbolic variants of the icon. If the Fedora logo changes, I'll update.

[org.fedoraproject.MediaWriter.zip](https://github.com/FedoraQt/MediaWriter/files/3058627/org.fedoraproject.MediaWriter.zip)

**Comment by jimmac** [comment]
Turns out the new logo isn't at a stage to be used, so here's a variant of the app icon based on the old logo. fullcolor and symbolic included.

![Screenshot from 2019-04-10 14-36-17](https://user-images.githubusercontent.com/14821/55879066-077b6b00-5b9e-11e9-9fac-482e20108116.png)


[org.fedoraproject.MediaWriter.zip](https://github.com/FedoraQt/MediaWriter/files/3063766/org.fedoraproject.MediaWriter.zip)

**Comment by MartinBriza** [comment]
thank you very much Jakub! I'll update the app icon with the next release.

**Comment by MartinBriza** [comment]
Partially fixed with 28e27d90baedef5ca031513e5c0047be569ceaa2 - updated only the regular hicolor icon, symbolic is to be updated later

**Comment by jimmac** [comment]
Fedora 34 finally ships with the updated logo. Attached are the fullcolor, devel/nightly and symbolic icons updated to reflect the change.

file:///home/jimmac/org.fedoraproject.MediaWriter.zip

**Comment by grulja** [comment]
Nice, I will update the app with this icon and inlude it in the next release.

**Comment by grulja** [comment]
Done: https://github.com/FedoraQt/MediaWriter/commit/ceef7054625037db4dfe2189b85c173877e5c404

Thank you.
