### ISSUE TITLE
Media writer not refreshed after switching desktops

### ISSUE THREAD

**Issue by fujisan43** [FedoraQt/MediaWriter#200]
After I launched Media Writer, I moved the desktop to the left and came back to see [this](https://imgur.com/a/ACxz8TC).

Media Writer does not refresh and only buttons and drop-down menu are visible.

version 4.1.2-1

**Comment by MartinBriza** [comment]
That's unfortunately either a Qt or driver issue, there's nothing I can do about it. I suggest taking this up to your distro and report against `qtdeclarative` or your graphics card drivers.
