### ISSUE TITLE
Cannot write to internal drives!

### ISSUE THREAD

**Issue by AMDphreak** [FedoraQt/MediaWriter#205]
I have an internal SSD via SATA connector that I have dedicated to loading installer images and live disks for testing OSes.

It appears MediaWriter only wants to write to external USB drives. This is a huge problem. This seems like a nice precaution but the entire usefulness of the program is lessened by this. I do not intend to buy a fast external flash drive to use this with. It's not as convenient.

Drives that are available:
![Drives that are actually available](https://user-images.githubusercontent.com/1058978/61846127-8eadcf80-ae6b-11e9-8e2b-5db228461a75.png)

Drives that it can write to:
![Drives that it can write to](https://user-images.githubusercontent.com/1058978/61846108-7d64c300-ae6b-11e9-9e4c-e5e438239400.png)

**Comment by MartinBriza** [comment]
You don't really want to do that. The image that would get written to your internal drive would be read-only. Except for installing Fedora to other drives from it, it would be pretty useless.
