### ISSUE TITLE
Not working on X570 with Ryzen 3700X

### ISSUE THREAD

**Issue by SMadani** [FedoraQt/MediaWriter#206]
I installed the image to a 32GB Kingston Datatraveller G4 and when I go to boot I get loads of errors and the 50 minute wait "a start job is running for dev-mapper"...
 I haven't had issues with installing Fedora on first-gen Ryzen Threadripper but not only does this not work for X570 / 3rd gen Ryzen but also my keyboard (Fnatic miniSTREAK USB C 3.1) doesn't work properly, but that may be a BIOS bug.

I'm using MSI X570 A-PRO, 32 (2x16) GB Corsair LPX Vengance DDR4-3200 MHz RAM, AMD Ryzen 7 3700X. I'm running the 7C37vH2 BIOS, which is the latest at time of writing. Let me know if there's anything else I can try or if any further info is needed.

**Comment by SMadani** [comment]
May be related: https://bugzilla.redhat.com/show_bug.cgi?id=1729268

**Comment by SMadani** [comment]
Solution is to use the "respin" ISO, fixed it for me. Is there any reason why the respin isn't used currently?

**Comment by MartinBriza** [comment]
This is the Fedora Media Writer repository. It only writes the image to your flash drive. For potential graphics driver issues (and any other Fedora bugs), please consult Fedora Bugzilla.
