### ISSUE TITLE
ISO download error

### ISSUE THREAD

**Issue by Igor-Belyaev** [FedoraQt/MediaWriter#208]
Hello! 
Now MediaWriter can't write Fedora on a USB-device. It finish with error. I guess it use not correct download pathes to iso-images. Also it is not impossible to download iso-images from site getfedora.org. It has incorrect download links too.
Site link: https: //fedora.ip-connect.info/releases/30/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-30-1.2.iso
Correct link: https: //fedora.ip-connect.info/**linux**/releases/30/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-30-1.2.iso

Sincerely yours,
Igor

**Comment by MartinBriza** [comment]
Hey Igor, sorry for replying so late. This would be a Fedora Websites issue in the future. MediaWriter just works with whatever it gets from getfedora.org.
