### ISSUE TITLE
External hard drive is not still bootable after writing the iso in it

### ISSUE THREAD

**Issue by PyHOK** [FedoraQt/MediaWriter#209]
Hello, I have successfully burn an iso file into my external hard drive with the MediaWriter. However, when I try to boot the computer from the hard drive, there is an error message showing that the drive is not bootable.
I am currently using windows 10 on my computer. The iso file is CentOS 7 1810. My computer is a HP laptop. The external hard drive is a TOSHIBA.
Do you have any idea how to solve this problem?

**Comment by MartinBriza** [comment]
It's possible Windows messed around with the drive in the meantime. Try writing to the drive again.
