### ISSUE TITLE
Restoring the USB volume isn't working 

### ISSUE THREAD

**Issue by Shenouda-Fawzy** [FedoraQt/MediaWriter#212]
After I write Fedora iso file to the USB, it doesn't show up again, tried to use 'Restore' button but nothing happend, the USB isn't restored and still invisible.

**Comment by MartinBriza** [comment]
It's probably dead. Flash drives die sometimes and I occasionally receive reports about these but unfortunately I can't do anything about it. 

I'll probably have to write a diagnostic guide for the users so it's easier to be sure if the drive died or not.

**Comment by Shenouda-Fawzy** [comment]
The drive isn't dead. I used Rufus App to rewrite another media on it, and it work good again.
