### ISSUE TITLE
Receive out of space error when downloading

### ISSUE THREAD

**Issue by rghamilton3** [FedoraQt/MediaWriter#213]
I'm not entirely sure where it's trying to download because I don't even see any logs. Is there a reason the download directory isn't configurable? Would you accept a PR for it to be?

**Comment by MartinBriza** [comment]
It's trying to download to your Downloads folder, however is that configured.
I don't think having a special option for that is all that necessary - if you care about having the downloaded file somewhere else, you could just download the file from the website manually and it'd be easier and faster.

**Comment by grulja** [comment]
Closing as WONTFIX. We are not going to make this configurable.
