### ISSUE TITLE
"Fedora Media Writer" can't always be translated

### ISSUE THREAD

**Issue by scootergrisen** [FedoraQt/MediaWriter#214]
If i download FedoraMediaWriter-win32-4.1.4.exe it seems the name "Fedora Media Writer" can't be translated many places in the installer and also in the program.

But on Zanata there is a few strings where "Fedora Media Writer" can be translated.
But i can't translate it consistently if i am only able to translate it sometimes.

**Comment by MartinBriza** [comment]
Installer is not really made translateable because messing around with NSIS is pretty painful to me. Sorry. Patches welcome though :)

**Comment by grulja** [comment]
Duplicate of https://github.com/FedoraQt/MediaWriter/issues/184.
