### ISSUE TITLE
Fedora 31 - new version of Fedora Media Writer necessary

### ISSUE THREAD

**Issue by AWHubGit** [FedoraQt/MediaWriter#215]
Today Fedora 31 is already available, but Fedora Media Writer 4.1.3 doesn't know it.
Is it necessary to download/install new version of Fedora Media Writer to get Fedora 31 (32....)?
Please clarify.

**Comment by MartinBriza** [comment]
Hey, thanks for reporting but this is the same story with every single Fedora release. The metadata about new Fedora releases is hosted on getfedora.org, which means it's necessary to report this to the people who maintain Fedora websites.
In this cycle I reported this after the Beta release, to no avail. However, I got pinged from a several Fedora people today who will ping more people so I think it's safe to say the gears are turning now and I hope everything will be in order very soon.

**Comment by MartinBriza** [comment]
I'll leave this issue open for a bit so we don't get more duplicate reports.

**Comment by sileshn** [comment]
It works now..
![Capture](https://user-images.githubusercontent.com/977360/67996534-c2bc3c00-fc75-11e9-9d46-4680517bdae5.PNG)

**Comment by MartinBriza** [comment]
Great! So it's time to close this. Thanks for you concern, guys!
