### ISSUE TITLE
[RFE] Improve restoration of USB drives in Windows

### ISSUE THREAD

**Issue by ifdru74** [FedoraQt/MediaWriter#216]
Steps to reproduce:
1. Get a Kingston's DTE2G/64GB flash drive and a Windows 10 Pro;
2. Write Fedore Core 31 live DVD with FedoraMediaWriter-win32-4.1.4 onto the flash drive;
3. Use it for several hours;
4. Use restore option in FedoraMediaWriter-win32-4.1.4;
5. Receive message "Cannot find the file specified." when you try to format restored flash drive or when you try to set drive letter;

**Comment by r0bertini** [comment]
The USB (SanDisk 32GB) cannot be restored and used anymore in Windows 10 neither in MacOS Catalina - both systems can't format the device. Only application which can operate with the USB is Fedora Media Writer - but even after hitting Restore which finishes successfully it didn't help and the USB is still useless. Is there any workaround?

**Comment by ifdru74** [comment]
Hello,
I was managed to restore the flash capacity with the other program ( https://rufus.ie/ ) which allowed me to restore the capacity and format. After that, in some systems my flash drive became invisible.
P.S. and it was not a SanDisk, it was a Kingston DTEG2 (64G)
 
Regards, Alexey

**Comment by r0bertini** [comment]
Thanks, that helped on my SandDisk 32GB, so that seems like universal solution for until this issue is fixed in Media Writer. Thanks Alexey!

**Comment by MartinBriza** [comment]
Hmm, I gotta admit the restore implementation in Windows could be better but I didn't find a good way to do it. I'll leave this bug open and maybe at some point I'll find a better way to restore the drives.

**Comment by abitrolly** [comment]
Did anyone find docs what the Restore options is supposed to do? I probably should reformat flash drive to original filesystem, like FAT32 or NTFS, but does it save the filesystem type anywhere?

**Comment by MartinBriza** [comment]
It doesn't save the FS type. "Restore" is probably not a very good term but yeah, it will be FAT32 always. The more important thing it actually does is restoring the partition table though. It's slightly busted by writing the ISO to it and a lot tools (like GParted or Windows format dialog) can't deal with that.

**Comment by maxmod** [comment]
Use this utility for windows 100% working https://bit.ly/3oBO5JO

**Comment by dreua** [comment]
@maxmod  why do you post this as a bit.ly link? Additionally I'm not sure this site is tool is trustworthy, I'd suggest everyone to make their own reasearch and not rely on @maxmod's statement here.

**Comment by MartinBriza** [comment]
@maxmod I redacted your link, sorry. I wouldn't mind if your tool was open source, you linked to your page directly and the website provided a little more information about it. This way was just weird. Feel free to get in touch with me via a separate issue or email if you want to object or discuss this.

**Comment by dreua** [comment]
Maybe @maxmod's software is a good fork of rufus, maybe it's a bad one, but can it do anything that rufus can't?

**Comment by usbtool** [comment]
> @maxmod why do you post this as a bit.ly link? Additionally I'm not sure this tool is trustworthy, I'd suggest everyone to make their own reasearch and not rely on @maxmod's statement here.
> 
> Update: And please disclose your relationship to that product. I really wonder what this is about, unfortunately I don't have the tools to analyze your executable :/

Sir,
Code is punlished you can check
Thank You

**Comment by usbtool** [comment]
> Maybe @maxmod's software is a good fork of rufus, maybe it's a bad one, but can it do anything that rufus can't?

Sir,
you can check https://www.virustotal.com/gui/file/658cb937213bf2f2fa397cbdad1540b1c45ec8720bd5cd336bf441cfd3390841/detection
Just made small utility for format usb only and code also available
Thank You

**Comment by grulja** [comment]
@usbtool please stop posting links to your websites.
