### ISSUE TITLE
Doesn't work on macOS Catalina

### ISSUE THREAD

**Issue by togores** [FedoraQt/MediaWriter#217]
I tried both ways (the default and choosing an image) but the application doesn't write anything to the disk, even though it says "writing".

**Comment by chiffon-rouge** [comment]
I struggled with this problem for the last hour and actually thought it might be something wrong with the USB stick I was using until I got the idea it might be macOS 10.15 related. I'm curious about a solution as well.

**Comment by pshyko667** [comment]
> I struggled with this problem for the last hour and actually thought it might be something wrong with the USB stick

Same here. Please fix this!

**Comment by MartinBriza** [comment]
Well, to be honest, I don't really have the capacity to work on this at the moment. I'll at least look into it to see what's the cause when I use my Mac next time.

**Comment by chiffon-rouge** [comment]
Sounds good. It would also be great to reflect this (temporary?) issue on the getfedora.org page to avoid unnecessary confusion (if you have the means to do so).

**Comment by MartinBriza** [comment]
Yeah, when I know the source of the problem, I'll notify the Fedora people to put something on the website. I use my Mac pretty often these days so I'll look into it tomorrow or the day after probably.

**Comment by MartinBriza** [comment]
Ok, it's not so bad, I've been able to use the helper binary from the terminal by using this:
```osascript -e 'do shell script "cd ./helper/mac/helper.app/Contents/MacOS/; ./helper restore disk2" with administrator privileges without altering line endings'``` 
(notice the extra `cd` compared to just running the binary)

For some reason I'm not able to reproduce the same behavior from inside FMW but with enough tries, I may be able to fix this. I'll need to go in a few minutes so it'll not be today unfortunately so I'm at least letting you guys know it's possible and (wink wink) how to help me if you have a bit of time.

**Comment by nikolas** [comment]
This is broken for me too, on macOS 10.15.2. The program looks like it's writing the image to the USB drive, then it finishes and nothing has been written.

**Comment by yogeshkamat111** [comment]
> This is broken for me too, on macOS 10.15.2. The program looks like it's writing the image to the USB drive, then it finishes and nothing has been written.

Still it's the same on macOS 10.15.3

**Comment by pshyko667** [comment]
In the meanwhile you can use Etcher (etcher.io). It's working fine for me.

**Comment by adambkaplan** [comment]
@dusymabe bumping this - folks like me running frankenmachines can't use Fedora Media Writer on Catalina (and can't get Fedora 32 😢 ).

**Comment by sethgoldin** [comment]
Replicating the issue here.

**Comment by AdamWill** [comment]
@MartinBriza ping? any chance of prioritizing this? it seems like a fairly major issue.

**Comment by funnelfiasco** [comment]
[Downstream bug](https://bugzilla.redhat.com/show_bug.cgi?id=1840663) nominated as a [Prioritized Bug](https://docs.fedoraproject.org/en-US/program_management/prioritized_bugs/).

**Comment by MartinBriza** [comment]
Sorry for taking so long to do something about this. I don't have much free time to spend tweaking the writer script this because I have other stuff on my plate at this moment. If there was somebody willing to step up and fix this (I have written some notes on the topic above), I'd be more than willing to just test the solution and release it.

**Comment by MartinBriza** [comment]
Good news! I got it to work, except in a completely different way than I expected. It will actually report the progress on macOS now same as on other platforms and overall it seams much better.

There is one slight problem with the code is I'm TECHNICALLY (well, actually, really) violating either GPL or some other license so I need to find a compatible library that does the same thing I want or write the whole thing myself.
