### ISSUE TITLE
Increase scaling factor of interfaces fonts to make text at last readable.

### ISSUE THREAD

**Issue by Ricky-Tigg** [FedoraQt/MediaWriter#218]
Component: mediawriter.x86_64  4.1.4-3.fc31 @fedora; Tested under **Gnome standard** on **Wayland**; **15.60**-inched screen; Resolutions (pix): 1920 x 1080, 1600 x 900, 1368 x 768, 1280 x 720 (16:9).

_Enhancement request_ – Interface's font sizes are neither readable nor scalable whatever the resolution applied, which is a pity as I was convinced I had to rely on that tool in order to produce easily reliable installation media. By comparing Libreoffice's _Liberation Serif_ font sizes on a document matching the physical size of a page, as measurement mean, to sizes displayed in interface, closest possible values I obtained were as follow:
- Titles: 10 pt;
- Descriptions: 8 pt.

_Note_: in _gnome-tweaks_, increasing value of section Fonts | Scaling Factor won't have any effect on the interface's font sizes.

I would suggest to **increase** accordingly all values by 32 % to 24 %. Tool was left unused, which could not be the goal desired.

**Comment by MartinBriza** [comment]
Hm, I'm not sure what's wrong but I have a 14inch 1920x1080 system and it works alright. Probably your DPI information is incorrect? What does `xrandr` report?

**Comment by Ricky-Tigg** [comment]
On Wayland tHat X.Org X11 X server utility is  not reliable. It displays different resolution regarding it is run under Wayland or X windows servers. An issue report has been posted regarding that behavior. Since Fedora 32, options _Gnome on Xorg_, _Gnome Classic_,  are no more available through GNOME Display Manager (GDM); _Gnome_  –which is on Wayland–.remained. Thus a comparative information cannot be produced anymore under Gnome.

Here are values of no help; most of the resolutions listed by _Gnome control center_ are missing from `xrand`, eg. **1920 x 1080**, while out of all, five resolutions listed by `xrand `are also listed by _Gnome control center_, eg. **1368 x 768**.
```
$ xrandr
Screen 0: minimum 16 x 16, current 1368 x 768, maximum 32767 x 32767
XWAYLAND0 connected 1368x768+0+0 (normal left inverted right x axis y axis) 340mm x 190mm
   1368x768      59.71*+
   1024x768      59.68  
   800x600       59.47  
   640x480       59.38  
   320x240       59.52  
   720x480       59.71  
   640x400       59.20  
   320x200       58.96  
   1280x720      59.65  
   1024x576      59.58  
   864x486       59.45  
   720x400       59.55  
   640x350       58.91
```

**Comment by grulja** [comment]
With port to QQC2 in the new FMW 4.2.0 I believe this should no longer be a problem.
