### ISSUE TITLE
Ability to write multiple ISO files at once to an USB block device, in order to operate multi-boot on EFI/BIOS systems

### ISSUE THREAD

**Issue by Ricky-Tigg** [FedoraQt/MediaWriter#220]
Component: mediawriter.x86_64 4.1.4-3.fc31 @fedora

_New feature request_ – Ability to write multiple ISO files of Fedora installation media –be they _Live_ or not– at once to a same USB block device, in order to operate **multi-boot** on EFI/BIOS systems.

**Comment by MartinBriza** [comment]
This is pretty likely to never going to happen in the future. It's pretty damn hard to do this in OSes that are not Linux and we're trying to keep the features of the app to be completely the same on all three supported systems...

Personally, again, as said in the other bugs, am focused on just maintaining this app and I'm not actively developing it. HOWEVER, if somebody is willing to step up in the future and actually implement and maintain the code, I'm all for it.

**Comment by Ricky-Tigg** [comment]
That was a comment I could have myself wrote as a developer. It seems to me fair to close if you have no objection.
