### ISSUE TITLE
cannot find silverblue images in flathub version

### ISSUE THREAD

**Issue by hferreiro** [FedoraQt/MediaWriter#222]
Either the version in flathub isn't the latest one or the silverblue image support is not working.

**Comment by MartinBriza** [comment]
It is in the Workstation release, if you click the "Other variants..." link.

**Comment by hferreiro** [comment]
I have to say that finding it there is really hard. Other variants is in most cases (all?) used for choosing between hardware architectures (Intel 64bit vs ARM v7 in all cases I checked).

Additionally, using the search box didn't reveal any results.

**Comment by rugk** [comment]
created a new issue for that: https://github.com/FedoraQt/MediaWriter/issues/237

It's indeed IMHO not acceptable to hide it so much in the GUI.
