### ISSUE TITLE
Error "Not authorized to perform this action" when writing iso

### ISSUE THREAD

**Issue by nikolas** [FedoraQt/MediaWriter#223]
I'm using Fedora Media Writer version 4.1.3, trying to write a Fedora image to a external hard drive. I'm on Debian sid. dbus, policykit, and udisks2 is running on my system.

I get the error "Not authorized to perform this action" when writing this iso. Screenshot:

![2019-12-20-231609_633x333_scrot](https://user-images.githubusercontent.com/59292/71302916-27933900-237f-11ea-81e3-9efcd83b6b91.png)

Using sudo, I can't even open the image selection dialog, and I read this program wasn't meant to be run as root anyways.

Here's the last part of the log:
```
W@1115ms: Error QNetworkReply::UnknownNetworkError reading from QUrl("https://getfedora.org/releases.json") : "Error while reading: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init"
W@1780ms: qrc:/views/ImageDetails.qml:136:29: QML Text: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead. (qrc:/views/ImageDetails.qml:136)
W@1780ms: qrc:/views/ImageDetails.qml:136:29: QML Text: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead. (qrc:/views/ImageDetails.qml:136)
W@1780ms: qrc:/views/ImageDetails.qml:136:29: QML Text: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead. (qrc:/views/ImageDetails.qml:136)
W@3700ms: qrc:/views/ImageDetails.qml:136:29: QML Text: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead. (qrc:/views/ImageDetails.qml:136)
W@3700ms: qrc:/views/ImageDetails.qml:136:29: QML Text: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead. (qrc:/views/ImageDetails.qml:136)
W@3700ms: qrc:/views/ImageDetails.qml:136:29: QML Text: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead. (qrc:/views/ImageDetails.qml:136)
W@6570ms: Writing failed: "Not authorized to perform operation"
W@6572ms: Couldn't send a notification: "org.freedesktop.DBus.Error.ServiceUnknown" - "org.freedesktop.DBus.Error.ServiceUnknown"
W@86422ms: Writing failed: "Not authorized to perform operation"
W@86424ms: Couldn't send a notification: "org.freedesktop.DBus.Error.ServiceUnknown" - "org.freedesktop.DBus.Error.ServiceUnknown"
W@114798ms: Writing failed: "Not authorized to perform operation"
W@114800ms: Couldn't send a notification: "org.freedesktop.DBus.Error.ServiceUnknown" - "org.freedesktop.DBus.Error.ServiceUnknown"
```

**Comment by MartinBriza** [comment]
This is either a distribution or a system setup issue. FMW is utilizing UDisks over D-Bus to gain access to the device you're trying to write to. Either there's something wrong with your polkit setup or it is **really** strict - I'm not really that well versed in this topic but I think it's possible you could have either a deny-all policy or something very strict intended to be used on servers (where you don't want applications to access storage in this way anyway).

Also, are you trying to write a live image to a hard drive?

**Comment by nikolas** [comment]
Okay, after reading some more I think this may be related to not using a full desktop environment like Gnome which has notification daemons (i'm using xmonad), so, I'm installing Gnome and I'll try from there. And yeah, like you said it could be a strict policy-kit config too. I'm not familiar with that either so I'll read up on that.

> Also, are you trying to write a live image to a hard drive?
Yeah. I have an external hard drive I was trying to put this on. I get the same error when attempting on a 16gb usb driver, though.

**Comment by nikolas** [comment]
Okay, it worked in Gnome. Maybe it should be listed under the requirements that Media Writer needs to be run in a desktop environment, and not an alternate window manager.

**Comment by MartinBriza** [comment]
Hmm, it should run mostly everywhere as long as UDisks over D-Bus is present. Did it write the image to the drive, despite the error? I honestly forgot how I wrote it but handling notification errors the same as writing errors doesn't seem right.

**Comment by nikolas** [comment]
I didn't see if the error showed or not in the log when I ran this in Gnome, it just worked, with the auth prompt provided by Gnome. Sorry, I didn't save the log.

**Comment by antonmry** [comment]
It happened the same to me with I3WM. Switch to Gnome solved it.

**Comment by dodowhat** [comment]
I met the same problem under i3wm, and solved it.
The reason is your system is lacking a polkit authentication agent for desktop environment (refer to [Polkit - ArchWiki](https://wiki.archlinux.org/title/Polkit)), so just pick one and install it, then make it autostart with your desktop or window manager, done.
I chose `lxpolkit`, a simple one, and made it autostart with i3.conf:
```
exec lxpolkit
```

**Comment by stelcodes** [comment]
Thanks so much @dodowhat. I can confirm using `lxpolkit` also works in Sway as well.

**Comment by noahdotpy** [comment]
Can confirm that I installed lxpolkit and ran it and now I can write using fedora media writer, cheers boys.

**Comment by sysp0** [comment]
Update:
I had this problem on I3WM.
Run with root level, the "Not authorized to perform this action" problem is solved
