### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [FedoraQt/MediaWriter#224]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by Jibec** [comment]
kind warning, you are using strings from fedora Websites, which moved to Weblate. You'll soon have obsolete translations.
Please start conversation so we can make sure this has no impact on future release of your project.

**Comment by MartinBriza** [comment]
Uh, thanks for letting me know and sorry for not answering earlier. 

For the mandatory answers:

* `master`
* not yet

As for the info, that's great but the translation files are generated from more projects and I was taking a lot of text from the Fedora Websites project to have as much translated text "for free" by reusing the content from getfedora.org. 

I'll have to delve more in depth into it soon.

**Comment by Jibec** [comment]
You don't have to worry about it.
Let translators handle this.
Weblate will automatically suggest translation, taking the closer match. It will be easy for us to do.

**Comment by Jibec** [comment]
kind reminder, zanata removal is coming in a few weeks: https://fedoraproject.org/wiki/Changes/Zanata_removal

**Comment by grulja** [comment]
FMW now use Weblate.
