### ISSUE TITLE
Not a big deal; media writer doesn't repect gtk yjrmr

### ISSUE THREAD

**Issue by coz** [FedoraQt/MediaWriter#226]
Hello,
 I know media writer doent respect the gtk theme however, is there a way to theme it to a dark theme?
I have bad eye sight and can only read it when colors are inverted which I can do with compiz negative plugin. 
   I know I could continue to do this, but was cutious if I had to.

Thanks
coz

**Comment by MartinBriza** [comment]
Mediawriter takes the color scheme from the Qt style you have set up. If you haven't done anything about it, then the colors will be off.
If you don't use it, I recommend getting https://github.com/FedoraQt/QGnomePlatform . Your distro probably ships it. Then it really depends on what style you use with GTK.
Another way around this is using https://sourceforge.net/projects/qt5ct/ that allows you to fine-tune stuff, including color schemes. 
And the simplest workaround is to put `QT_STYLE_OVERRIDE=$sometheme` to either your `bashrc` or into the mediawriter desktop file.
If this is confusing to you, let me know, I'll try to help :)

**Comment by coz** [comment]
Martinbiza,
Thank you. I trying your recommendations. This will certainly help!
coz
