### ISSUE TITLE
A communication issue

### ISSUE THREAD

**Issue by FutureFireplace** [FedoraQt/MediaWriter#227]
Without being pretentious I have to stress the following:

There is a contrast between 'normal workstation users' (most of us) and 'linux users' (this community). With the sphere in between, I consider it an important task for the Linux World; to meet the normal users half way. In many cases they do, but in relation to the:

"Windows
Building FMW in Windows is just the matter of running qmake and make.

To create a standalone package, use the windeployqt tool, included in your Qt installation. You will probably have to include a bunch of not included DLLs.

Requirements
xz-libs"

- message in this git, the 'half way point' does seem to be met (at all, actually).

Why? I have tried the following:
1) Downloaded the rep, and thereafter written 'qmake' or 'make', in the correct dowloaded + unpacked CMD-path ...
2) - which hasn't worked with [trying*] to install xz-libs as explained above.
---
As being close to giving up (on a {start by google search: "easiest USB feodora installation"} >> that lead to https://docs.pagure.org/docs-fedora/how-to-create-and-use-live-usb.html >> then guided to here}), I hope to both get wiser, but also help other 'normal users', who wants to install Feodora in the most easiest of ways (5 yrs ago I did install Feodora, with some trouble, but this seems harder now ->> 'the easiness' is going in the wrong direction).
[trying*]: The information on https://tukaani.org/xz/ for xz-libs installation, is confusing also {I will recommend them to make a show-and-tell video, as I really can't figure out if "Source code + Stable" is sufficient or "Pre-built binaries" is required also}.

All in all: make it easy to install Feodora/Linux - we are many 'normal users' who often wants to give Linux a chance once in a while.
But some things has to get better: info on this page + also more stable work-station installations (the reason why I didn't used my old Feodora installation much, was the command prompt functionality => half of the commands I tried didn't work :-// )

**Comment by MartinBriza** [comment]
Yeah, sorry, I wrote the README first when the `xz` dependency was not there. Honestly, I don't know how to build the app on Windows easily - since first you have to have `xz-libs` somewhere the compiler sees it. 
The actual Windows version we're providing to the end users is actually crosscompiled using `MinGW` in Fedora... 
Basically, the only thing I can do is remove the "simply run qmake" part from README because I simply don't have the resources to figure out how to build the app on Windows (and I don't actually need to do that, personally).

**Comment by FutureFireplace** [comment]
ok, fair enough - thanks for the detailed answer

**Comment by MartinBriza** [comment]
In case you're still interested in building the app yourself, I've added a GitHub Actions workflow to this repo today: https://github.com/FedoraQt/MediaWriter/blob/master/.github/workflows/ccpp.yml#L130

On the linked line, you can see the hacky way I chose to build `xz-utils`, install it inside the Qt root directory and then just let `qmake` find it itself when building.

**Comment by FutureFireplace** [comment]
ok, ended up installing a Ubuntu-version
