### ISSUE TITLE
Theme/widget style issues

### ISSUE THREAD

**Issue by allanday** [FedoraQt/MediaWriter#232]
The media writer UI has quite a lot of theme/widget style issues - see below for a collection of examples. I could probably come up with more.

Rather than tackle each one individually, we should see if there's a more general fix for this - likely by using a theme that's maintained elsewhere, rather than relying on custom styling.

One concern I have in this area is whether there's a mismatch between the design patterns being used in the app and the widgets that are supported by the toolkit/theme. This is particularly the case for the big lists. If we can't find a theme that adequately supports the design patterns, we might need to rethink the design and which theme we're using.

## Examples

Spurious border around the scroll bar, plus there's an obvious glitch with the trough area:

![image](https://user-images.githubusercontent.com/213068/78251988-0f889500-74ea-11ea-8154-cb818ba24474.png)

Odd dark lines on the left of the lists:

![image](https://user-images.githubusercontent.com/213068/78242682-57072500-74da-11ea-9696-736b63f5ba3a.png)

Incorrect/poor button colours:

![image](https://user-images.githubusercontent.com/213068/78242712-6e461280-74da-11ea-953e-b43d7b7814b1.png)

Selected text colour:

![image](https://user-images.githubusercontent.com/213068/78242858-ac433680-74da-11ea-962f-2545982f673b.png)

Harsh button border, incorrect border radius:

![image](https://user-images.githubusercontent.com/213068/78242903-bebd7000-74da-11ea-9d05-96b415053837.png)

**Comment by grulja** [comment]
I believe most of the issues you mentioned are gone or way better with FMW 4.2.0. While I agree it would be good to use a style maintained elsewhere, it is not really possible with Qt5 as they have just one, very basic, style for QQC2 components. It should be different with Qt6, where they will provide QQC2 styles for Mac OS and Windows.
