### ISSUE TITLE
Widget scaling issues on Windows 10

### ISSUE THREAD

**Issue by allanday** [FedoraQt/MediaWriter#233]
On Windows 10, the widgets grow far too large when the window is maximised:

![image](https://user-images.githubusercontent.com/213068/78243667-16101000-74dc-11ea-83f1-461af9a4f997.png)

The height of the search bar and architecture combobox is a particular issue.

I'm assuming that this is a Windows 10 issue, but it could be a problem with high density displays?

This could be another aspect of #232.

**Comment by grulja** [comment]
This should be already fixed in FMW 4.2.0.
