### ISSUE TITLE
Make Fedora Silverblue version it's own proper entry

### ISSUE THREAD

**Issue by rugk** [FedoraQt/MediaWriter#237]
I still don't find it in v4.1.4-3.

The search cannot find it, at least.

What I find is some kind of AArch64 (??) image in the workstation version selection that also has a "Silverblue" in it's name:
![silverblue](https://user-images.githubusercontent.com/11966684/80753013-d9602480-8b2c-11ea-9231-a4950541204f.png)

AArch64 is some AMD architecture, that is not helpful for usual x86_64 users.

This is still totally confusing, as Silverblue is IMHO quite different from Workstation and should ahve
* it's own entry
* and is AFAIK also available in multiple architectures and, of course, versions

**Comment by MartinBriza** [comment]
there still seems to be no translateable metadata for silverblue so it's
really pretty hard to incorporate into the mostly localized fmw

**Comment by rugk** [comment]
Okay, so where does one need to ask (or even contribute) to get these info?

**Comment by rugk** [comment]
Also this still does not explain the architecture problem.

**Comment by MartinBriza** [comment]
as for aarch64, that's actually 64bit arm, I'm not sure why only that is
there but my best guess would be the releases.json file hosted on fedora
websites is incomplete, please report that issue to them

**Comment by rugk** [comment]
Okay opened https://pagure.io/fedora-web/websites/issue/114 (for metadata) and https://pagure.io/fedora-web/websites/issue/113 (for the missing architecture entries).

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/MediaWriter/pull/293.
