### ISSUE TITLE
MEDIA WRITER ON WINDOWS 10 NOT WORKING

### ISSUE THREAD

**Issue by RONLTL** [FedoraQt/MediaWriter#238]
Trying to write Red Hat DVD image to USB key - barnd new 16GB.  Fails immediately and shows RETRY.

DOES FLASH SOMETHING AMOUT MEDIA BEING RESIZED BEFORE BUT TOO QUICK TO SEE ALL.

Just downloaded latest version.

**Comment by froginperil** [comment]
I had the same problem but resolved it. There are two versions of FMW in the wild. One is simply a zip archive with instructions to unzip and then run the program file as an administrator. **That does not work**.

The other, which did work, actually installs FMW to Windows. It works perfectly. I obliterated Windows completely so I have no history to work with but I believe the working version is here: https://en.freedownloadmanager.org/Windows-PC/Fedora-Media-Writer-FREE.html

That is the kind of link that I would ordinarily avoid but I was desperate. I haven't used Windows in over 20 years and hated every second that it existed on the machine.

**Comment by MartinBriza** [comment]
huh, that doesn't make any sense to me, if you want to get an installer for
the latest version, you can go to getfedora.org or just get one from this
github page
i definitely don't think downloading binaries from some random website is a
good idea
as for this issue, I'm afraid there's not enough info for me to be able to
determine where is that coming from, can you please specify which version
of fmw are you using and what is your exact version of windows?

**Comment by CC-Hsu** [comment]
MediaWriter 4.1.5 also not works on my computer (win10 1903).

I reinstall the previous version (4.1.4) and it works again.

Both installers are downloaded from GitHub release page and are installers.

How to get MediaWriter log in Windows?

Maybe I can reinstall 4.1.5 and check the log to get some clue.

Thanks.

**Comment by MartinBriza** [comment]
Yeah, sorry guys, this is very likely caused by my error when composing the image on this page. One library is missing and the helper process just fails without it. I'll release a fixed version soon.

**Comment by CC-Hsu** [comment]
Hi, Martin,

Thanks a lot.

**Comment by pdcemulator** [comment]
version 4.1.4 is working if anyone has the same problem
https://github.com/FedoraQt/MediaWriter/releases/download/4.1.4/FedoraMediaWriter-win32-4.1.4.exe

**Comment by MARK-PENGUIN** [comment]
Aand version 4.1.5 broke it again

**Comment by MARK-PENGUIN** [comment]
The problem is that version 4.1.5 downloads a newer image, whereas 4.1.4 does not, meaning you have to boot into the OS and do more unnecessary things, if 4.1.5 included liblzma, which it does not for some reason,  you wouldn't have to go through all of that

**Comment by divaksh-fw** [comment]
> The problem is that version 4.1.5 downloads a newer image, whereas 4.1.4 does not, meaning you have to boot into the OS and do more unnecessary things, if 4.1.5 included liblzma, which it does not for some reason, you wouldn't have to go through all of that
> 
> Workaround: download [XZ Tools](https://tukaani.org/xz/xz-5.2.5-windows.zip) and copy the files into the program installation directory, usually in x86 program files for windows.

I confirm this workaround is working.

**Comment by Divaksh** [comment]
> The problem is that version 4.1.5 downloads a newer image, whereas 4.1.4 does not, meaning you have to boot into the OS and do more unnecessary things, if 4.1.5 included liblzma, which it does not for some reason, you wouldn't have to go through all of that
> 
> Workaround: download [XZ Tools](https://tukaani.org/xz/xz-5.2.5-windows.zip) and copy the files into the program installation directory, usually in x86 program files for windows.

I confirm this workaround is working. Just copy files from the desired bin and paste it into the root of the Fedora Media Writer installation.
