### ISSUE TITLE
Fedora Media Writer stops with error 

### ISSUE THREAD

**Issue by PieHoleDepravity** [FedoraQt/MediaWriter#239]
Hi,
After choosing the distro and downloading it, pressing "Write to Disk" produces the following...
_The code execution cannot proceed because liblzma.dll was
not found. Reinstalling the program may fix this problem._

I uninstalled/reinstalled but the error persists. Any clues about what to do please?

Dualboot Windows version 1909 build 18363.815, Manjaro 20.01 KDE
i7-9750H, 8 GB Ram, 1TB HDD & 256GB SSD, GeForce GTX 1650ti 4 GB

**Comment by PieHoleDepravity** [comment]
I found the 32bit 4.1.4 version, that works just fine so I've gone with that.

**Comment by pdcemulator** [comment]
duplicate to #238

**Comment by PieHoleDepravity** [comment]
Peoples I wouldn't hold your breath waiting for assistance much less a resolution to this. I dropped my query about this over a month ago and I've concluded this isn't something of concern to the dev(s) since absolutely no response was the reply. I did however have a poke about on some forums where the general consensus is to try anything else _but_ this installer, which struck me as kind of odd but heyho. I decided another distro might be a better option for me because it's possible I may need assistance at some point in the future and I felt it doesn't look like i'm going to get it with Fedora Media Writer involved.

**Comment by sobeitnow0** [comment]
> Peoples I wouldn't hold your breath waiting for assistance much less a resolution to this. I dropped my query about this over a month ago and I've concluded this isn't something of concern to the dev(s) since absolutely no response was the reply. I did however have a poke about on some forums where the general consensus is to try anything else _but_ this installer, which struck me as kind of odd but heyho. I decided another distro might be a better option for me because it's possible I may need assistance at some point in the future and I felt it doesn't look like i'm going to get it with Fedora Media Writer involved.


True...

**Comment by MartinBriza** [comment]
Sorry for the issues, there was an error with the compose script in GitHub Actions. It is fixed now for 4.1.6 and I have rebuilt 4.1.5 so it's okay as well.

**Comment by MartinBriza** [comment]
> Peoples I wouldn't hold your breath waiting for assistance much less a resolution to this. I dropped my query about this over a month ago and I've concluded this isn't something of concern to the dev(s) since absolutely no response was the reply. I did however have a poke about on some forums where the general consensus is to try anything else _but_ this installer, which struck me as kind of odd but heyho. I decided another distro might be a better option for me because it's possible I may need assistance at some point in the future and I felt it doesn't look like i'm going to get it with Fedora Media Writer involved.

Also, hey, I'm not paid to develop this thing, if you don't like something doesn't work and seems so simple to fix to you, just come and open a PR, I'd be absolutely happy to merge it if it fixes an issue. These knowitall comments from people who feel like they're entitled to receive prompt fixes for each and every issue they report totally make me want to work faster... :facepalm:

**Comment by PieHoleDepravity** [comment]
> 
> _Also, hey, I'm not paid to develop this thing, if you don't like something doesn't work and seems so simple to fix to you, just come and open a PR, I'd be absolutely happy to merge it if it fixes an issue. These knowitall comments from people who feel like they're entitled to receive prompt fixes for each and every issue they report totally make me want to work faster..._
>
I'm going to guess you're a busy person, having closed this seven days ago and only now deciding to vent your feelings. I ask only that you read again my comment and take note that no reference was made about your abilities or compared them to anyone elses including my own. Indeed no mention of the quality of your coding or your skill sets have been mentioned by anyone anywhere, and nowhere was it said that it "seems so simple to fix" . However what is stated very clearly is the lack of response to an issue within a period of a month. Even a simple _"Hey everybod, I'll get to this sometime in the next four weeks!"_ would have been hugely appreciated. But again I am guessing you are a very busy person. I believe this is your only valid reason. To fall back on silly throwbacks like _"knowitall comments from people who feel like they're entitled"_ are perhaps born from a Friday tantrum and so overlooked here. The value of your voluntary contribution to this project is not lost on anyone I'm sure. But consider for a moment those who make sacrifices of their time and effort by volunteering in all walks of life such as medical, rescue, educational and the care sector (that's me 20hrs a week on top of my full time job since this blasted covid-19 thing started) were to fall back on the old _"Also, hey, I'm not paid"_ chestnut each time they might feel pressured to provide something they had offered? Would that be reasonable do you think? I doubt it. So... if nothing else do take away from this these three things 1) that gratitude for efforts made for free may not always obvious nor should it be 2) when stressed don't be letting off steam by misrepresenting anything that has been said.. and 3) it's Friday, grab a beer or whatever and chill.
