### ISSUE TITLE
Search breaks Custom image

### ISSUE THREAD

**Issue by Pascal666** [FedoraQt/MediaWriter#243]
Seen in v4.1.4-1.fc30 on Windows 10:
1. Open Fedora Media Writer
2. Click on Vertical ellipsis
3. Type something into search that makes at least one option go away ("fe" will not cause the bug because nothing goes away, but "to" or "te" will)
4. Click "Custom image"
5. Select an ISO
6. It will sit at "Preparing" forever

Additional bug: I was unable to reproduce this a second time, but while documenting the above I clicked "Cancel", deleted the search string, and played around with steps 3-6 many times, and eventually the program crashed.

**Comment by MartinBriza** [comment]
I don't have much else to say than: Huh, that's weird, I don't see a reason why that should happen. I'll try that on my machine a few times and see if I can reproduce.

**Comment by Pascal666** [comment]
Wild guess (having never seen any of this project's code): The Custom image option is getting filtered out, but forced to appear anyway.  The Preparing step references the filtered list, instead of the unfiltered list.

**Comment by grulja** [comment]
Can you try with MediaWriter 4.2.0?

**Comment by Pascal666** [comment]
Bug still exists in 4.2.0
