### ISSUE TITLE
Windows 10 disc image boots into GNU GRUB

### ISSUE THREAD

**Issue by Ricky-Tigg** [FedoraQt/MediaWriter#247]
Component: mediawriter.x86_64 4.1.4-4.fc32 @fedora

[Download](https://www.microsoft.com/en-us/software-download/windows10ISO) a disc image (ISO file)
```
$ file -b Win10_2004_Finnish_x64.iso 
ISO 9660 CD-ROM filesystem data 'CCCOMA_X64FRE_FI-FI_DV9' (bootable)
```
On an EFI supported computer, the USB device boots into GNU GRUB  environment instead of the graphical interface environment.

**Comment by MartinBriza** [comment]
Hi. FMW does not support writing Windows images. I'm going to open an issue to implement notifiying the user when they open a ISO file with "win" or "windows" in its file name.
