### ISSUE TITLE
Error installing RHEL 8.2

### ISSUE THREAD

**Issue by adam-hanna** [FedoraQt/MediaWriter#249]
Host - Windows 10; I ran MediaWriter in administrator mode
ISO - RHEL 8.2 x86_64 dvd iso (downloaded from red hat's website, today)
Usb - 16GB recently formatted to FAT32

I can't seem to find `FedoraMediaWriter.log` anywhere on my computer. I've searched my entire `C:\` drive and it's no where to be found.

Here's a gif. I'll keep looking for the log file.

![error](https://user-images.githubusercontent.com/5436950/84729484-ae009000-af48-11ea-86f2-303989f39c35.gif)

**Comment by adam-hanna** [comment]
Related issue?

https://github.com/FedoraQt/MediaWriter/issues/238

**Comment by pdjprogrammer** [comment]
I just downgraded to 4.1.4 and it works fine.

**Comment by MartinBriza** [comment]
Sorry for the issues, there was an error with the compose script in GitHub Actions. It is fixed now for 4.1.6 and I have rebuilt 4.1.5 so it's okay as well.
