### ISSUE TITLE
osascript shouldn't be used to gain privileged access

### ISSUE THREAD

**Issue by MartinBriza** [FedoraQt/MediaWriter#25]

**Comment by squimrel** [comment]
Privileged access seems complicated on mac. Someone threw a lot of code together in this repository: [mbsanchez/QtPrivilegedHelperExample](https://github.com/mbsanchez/QtPrivilegedHelperExample). But it's not nice. This shouldn't be that much effort.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/MediaWriter/commit/4ebdd7cbf505e3a23b2cd4306a5b3bd9021eaa6f.
