### ISSUE TITLE
LZMA Missing in Windows 10

### ISSUE THREAD

**Issue by J3RN** [FedoraQt/MediaWriter#250]
I downloaded version 4.1.15 from the Fedora website. It is able to download the Fedora Workstation image without issue, but when attempting to write, I am presented with this error:
![Capture](https://user-images.githubusercontent.com/2058614/84832304-042e0b80-affb-11ea-8fdd-894b819b7486.PNG)

I'm running
- Windows 10 (Education Edition), 64 bit
- Intel Core i7 6700K

**Comment by birkenfunk** [comment]
Have the same Probems
I'm running:

- Windows 10 (Professional), 64 bit
- Intel i/-8550U or Ryzen 7 2700X

**Comment by pdcemulator** [comment]
duplicate to #239 and #238

**Comment by J3RN** [comment]
I'm not 100% sure that #238 is the same issue, but #239 definitely is. Sorry, that didn't show up when I was searching the issues. Closing this in favor of #239.
