### ISSUE TITLE
4.1.5 does not work on Win 10, Version 2004, Build 19041

### ISSUE THREAD

**Issue by pdjprogrammer** [FedoraQt/MediaWriter#251]
So I am in the process of making some sticks for family members and they are running latest version of win 10.  When I downloaded .iso and then click write.  Just says error and then displays retry button.  Had to downgrade to 4.1.4 and works like a charm.

**Comment by e-thales** [comment]
Same issue here and I can confirm that it works fine on 4.1.4. Also, it seems like the app can't fetch the new Fedora versions, only Fedora 30 is avaliable and it keeps trying to update to no avail
![image](https://user-images.githubusercontent.com/55266991/85319280-ab95bd00-b497-11ea-806f-8f05aa7c7362.png)

**Comment by MartinBriza** [comment]
Sorry for the issues, there was an error with the compose script in GitHub Actions. It is fixed now for 4.1.6 and I have rebuilt 4.1.5 so it's okay as well.
