### ISSUE TITLE
Microsoft SmartScreen blocks the installer

### ISSUE THREAD

**Issue by cosmic-echo** [FedoraQt/MediaWriter#252]
OS: Windows 10 version 2004
App version: 4.1.5

The app got blocked because "it could harm the device". In Microsoft Edge (probably Chrome too since I'm using the new Microsoft Edge based on Chromium) you'll have to click keep, then in the next page click in keep again and when opening the .exe the user have to press in the "more info" > execute in the SmartScreen window.

https://imgur.com/a/uEDSzDX

**Comment by GabeAl** [comment]
Same behavior here, with same WIndows and app version

**Comment by grulja** [comment]
This should be happening only with the version you download on GitHub, but not with the one we provide on https://getfedora.org.
