### ISSUE TITLE
Won't update to latest release

### ISSUE THREAD

**Issue by GabeAl** [FedoraQt/MediaWriter#253]
Downloaded latest image for Windows from the Fedora main site (4.1.5).

Hangs at update phase (only displaying Fedora 30, instead of 32).

I allowed it through firewall. Windows 10 OS. May be related to the numerous other bugs I'm submitting.

**Comment by GabeAl** [comment]
4.1.4 works.

**Comment by MartinBriza** [comment]
There is no difference between 4.1.4 and 4.1.5 in this regard. It's possible the metadata file from Fedora was missing/broken when you tried it. Can you try it again?

**Comment by grulja** [comment]
I don't think this is still an issue and can be closed. Please re-open if the issue remains.
