### ISSUE TITLE
Fails to write official Fedora 32 Workstation ISO

### ISSUE THREAD

**Issue by GabeAl** [FedoraQt/MediaWriter#254]
Windows 10 OS, latest 4.1.5.

Upon navigating to the Fedora 32 Workstation ISO image, selecting it, and selecting my 32GB USB drive, I get an immediate rapid message "Error" at the top of the screen. No other information is displayed.

**Comment by GabeAl** [comment]
Older 4.1.4 works. (Or at least it doesn't fail immediately -- it's now actually trying to write the ISO)

**Comment by MartinBriza** [comment]
Sorry for the issues, there was an error with the compose script in GitHub Actions. It is fixed now for 4.1.6 and I have rebuilt 4.1.5 so it's okay as well.
