### ISSUE TITLE
Fails at restoring previous USB device's settings

### ISSUE THREAD

**Issue by GabeAl** [FedoraQt/MediaWriter#255]
Windows 10 OS, v4.1.5

Trying to restore a previously formatted USB device (containing, I believe, an older Fedora 31 image), results in failure with the following dialog box:

helper.exe System Error: The code execution cannot proceed because liblzma.dll was not found. Reinstalling the program may fix this problem. 

![image](https://user-images.githubusercontent.com/8050438/85960171-3cbcd600-b967-11ea-8f36-85b21e9ab940.png)

May be related to the numerous other bug reports recently filed by me. 

Thanks for looking into these!

**Comment by MartinBriza** [comment]
Sorry for the issues, there was an error with the compose script in GitHub Actions. It is fixed now for 4.1.6 and I have rebuilt 4.1.5 so it's okay as well.
