### ISSUE TITLE
Add Keywords to .desktop file

### ISSUE THREAD

**Issue by dreua** [FedoraQt/MediaWriter#262]
There are a lot of good keywords in the metainfo:
https://github.com/FedoraQt/MediaWriter/blob/835f7d5fa1195f81bcd12b1100e8595a8fc61b59/dist/linux/mediawriter.appdata.xml.in#L15-L22

Unfortunately I can't find the software in my Gnome search with these keywords, assuming this is not a bug in my desktop, I'd suggest adding these to the [.desktop file](https://github.com/FedoraQt/MediaWriter/blob/826daa45a2d663ef548f990294813f6f699b76d4/dist/linux/mediawriter.desktop.in).

My favorite is "iso" but I think it won't hurt to add all of them.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/MediaWriter/pull/293.

**Comment by dreua** [comment]
Sorry for creating duplicate issues here, I totally forgot about this one and created #291 half a year later. :laughing:
