### ISSUE TITLE
Media Writer ignores touchpad Natural Scrolling setting

### ISSUE THREAD

**Issue by ferdnyc** [FedoraQt/MediaWriter#263]
Despite having Natural Scrolling selected for my laptop's touchpad in `gnome-control-center`, dragging two fingers towards the bottom of the touchpad in Media Writer causes the page to scroll downwards, and an upward two-finger drag causes the page to scroll upwards.

In every other app, the Natural Scrolling preference reverses the scroll direction of those gestures.

This is with `mediawriter-4.1.4-4.fc32.x86_64` installed on Fedora 32 from the official repos.

**Comment by grulja** [comment]
I believe this has been fixed with transition to QQC2 so recent FMW (4.2.1) should work just fine.
