### ISSUE TITLE
Mediawriter icon missing 

### ISSUE THREAD

**Issue by sumantro93** [FedoraQt/MediaWriter#266]
This came up on test day
 GNOME, while the software is running, if I hit ALT+TAB, the icon is a "generic" one, see: 
https://alciregi.fedorapeople.org/screenshot/fmw.png

**Comment by dreua** [comment]
Not an issue on F32 from the fedora repository: mediawriter-4.1.4-4.fc32

**Comment by grulja** [comment]
This should be fixed in current master with upcoming MediaWriter.

Fixed with: https://github.com/FedoraQt/MediaWriter/commit/09f41d5c9f16a5c1e63c486457bee09913474c12
