### ISSUE TITLE
Multiple notifications about completing image writing

### ISSUE THREAD

**Issue by joshas** [FedoraQt/MediaWriter#268]
After writing disk image to SD card I got two notifications "Finished!".
Version 4.1.6-1.fc32 on Fedora 32.

**Comment by grulja** [comment]
Is this still a problem with FMW 4.2.1?

**Comment by joshas** [comment]
Yes. Just now wrote raspios image to SD card using FMW 4.2.1 on Fedora 33 and got two notifications.
![Screenshot from 2021-05-13 21-14-56](https://user-images.githubusercontent.com/79141/118168493-92d82200-b430-11eb-9030-cc8fdebc4390.png)

**Comment by grulja** [comment]
Thank you. I will try to reproduce and fix.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/MediaWriter/commit/54a7fffbb15b068720c492a6a20eae16f5df248c.
