### ISSUE TITLE
Mediawriter 4.1.6 (current version for macOS) only lists Fedora 30 for Intel 64 bit architecture

### ISSUE THREAD

**Issue by slippedtisk** [FedoraQt/MediaWriter#270]
![fedora33bug](https://user-images.githubusercontent.com/11414246/97813367-7039a500-1c66-11eb-92bb-9371ae6612f7.png)

**Comment by DannyThomas** [comment]
Firstly, can confirm FMW 4.1.7 runs OK on macOS 11.1 on 2013 MBP
While FMW initially displays Fedora 30, that changes in a second for me to Fedora 33 Server. I think it looks in the Downloads folder for .iso images but also connects to getfedora.org servers to list versions it can download.

**Comment by liutaurasa** [comment]
Same here. Using `Fedora release 33 (Thirty Three)` and `mediawriter-4.1.7-1.fc33.x86_64`. Launch "Fedora media writer" and the newest version available is 30. Spinner spins forever (more than 10 mins). I have downloaded ISO in mean time.

**Comment by liutaurasa** [comment]
Hm, maybe I was wrong - I was actually using MediaWriter which comes from Fedora flatpak repos, not the one installed with dnf. I've removed flatpak version, reinstalled mediawriter with dnf and now I see Fedora 33 in the list of possible versions.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/MediaWriter/commit/8d32ff73c850aa62ed12962be06a76551be3beb9.
