### ISSUE TITLE
Port to CMake

### ISSUE THREAD

**Issue by KAMiKAZOW** [FedoraQt/MediaWriter#272]
According to https://www.qt.io/blog/qt-6-build-system CMake is the default build system for Qt6. The page says about qmake: "At the moment the qmake build system is still in place" which doesn't really give confidence that qmake is here for the long haul.

**Comment by Conan-Kudo** [comment]
Actually nevermind, it looks like it's already there?

**Comment by grulja** [comment]
It's already ported to CMake.
