### ISSUE TITLE
UI doesn't update during operation

### ISSUE THREAD

**Issue by sciurius** [FedoraQt/MediaWriter#273]
The MediaWrite UI doesn't properly update when dialogs are shown or after being partially obscured. See screenshots.

mediawriter-4.1.4, Fedora with MATE.

![scrot20201217083001](https://user-images.githubusercontent.com/1118804/102457117-83e87180-4042-11eb-9ab7-047909fc9727.png)
![scrot20201217083148](https://user-images.githubusercontent.com/1118804/102457118-84810800-4042-11eb-8f19-d1150fd79b90.png)

**Comment by grulja** [comment]
Can you try with MediaWriter 4.2.0?

**Comment by eekboek** [comment]
I tried MediaWriter 4.1.7 on Fedora 33 MATE and it seems to behave fine, so I assume the problem has been solved since 4.1.4.
Thanks.

**Comment by grulja** [comment]
Thank you.
