### ISSUE TITLE
Doesn't write to any flash drive

### ISSUE THREAD

**Issue by Moldify** [FedoraQt/MediaWriter#274]
![error message](https://user-images.githubusercontent.com/76455176/102826829-6e12dd80-43af-11eb-94f7-e0d3773402d3.PNG)
I've been trying to install this on both this VendorCo Flash drive, as well as 2 Sandisk ones, and all of them end up with this error message.

**Comment by andrewc78** [comment]
simular issue. tried 3 different types of usb drive from win 10pro. No error description other than the word Error above horizontal progress bar.

**Comment by nigelis** [comment]
Encounter the same issue with v4.1.7, but it's ok with v4.1.6.

OS: Windows 10 Pro 2004
Disk: SanDisk 128GB
Image: CentOS-8-Stream

**Comment by grulja** [comment]
Should be fixed with https://github.com/FedoraQt/MediaWriter/commit/cd100d10d8a059b743b658520c406a25397868ed.
