### ISSUE TITLE
Misspelling of Cancel

### ISSUE THREAD

**Issue by dsr432** [FedoraQt/MediaWriter#276]
![image](https://user-images.githubusercontent.com/66963044/107152503-4d3e2180-6936-11eb-9255-8cfc93c39b84.png)
Cancel is misspelled as Cance. I'm just a user so I have no clue where this is stored, but I would think this should be a simple fix?  It's not a huge deal but it's a simple change that currently makes the system a little sketchy to the user...

**Comment by dreua** [comment]
Duplicate: #267

**Comment by grulja** [comment]
Closing as duplicate. Can you also try with newer version?
