### ISSUE TITLE
"Downloading" progress title looks jumpy when less then 1.0GB left to download

### ISSUE THREAD

**Issue by delight-aug** [FedoraQt/MediaWriter#278]
In the title of downloading progress bar, it shows decimal number even after less than 1 GB left to download. In other words, it shows progress with 100 KB precision. This makes the number in title change very fast and so, because the title is centered, it looks jumpy.

https://user-images.githubusercontent.com/51861383/109422939-4448e900-79e6-11eb-868d-4e1ada8563a4.mp4

It looks way faster IRL in contrast with waiting to change decimal with gigabytes.

The fix is probably to align the title to the left and stop showing decimals with megabytes

**Comment by allanday** [comment]
My issue - #422 - was slightly different, in that it was about the downloading progress string in general, not just when it's below 1.0 GB.

The issue isn't that the text is centered, but that the numeric characters need to be tabular, to avoid their width changing.

**Comment by grulja** [comment]
> My issue - #422 - was slightly different, in that it was about the downloading progress string in general, not just when it's below 1.0 GB.
> 
> The issue isn't that the text is centered, but that the numeric characters need to be tabular, to avoid their width changing.

I understand the issue, basically the width of the text needs to have the exact same width no matter what number it shows. Like "1,1 GB" should have same width as "2,2 GB" etc.
