### ISSUE TITLE
how do I fix this issue?

### ISSUE THREAD

**Issue by linucoybiloybiloy** [FedoraQt/MediaWriter#281]
```
19:20:46: Running steps for project mediawriter...
19:20:46: Starting: "/opt/Qt5.14.2/5.14.2/gcc_64/bin/qmake" /home/lucas/Downloads/MediaWriter-4.2.0/mediawriter.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
Info: creating stash file /home/lucas/Downloads/build-mediawriter-Desktop_Qt_5_14_2_GCC_64bit-Debug/.qmake.stash
19:20:46: The process "/opt/Qt5.14.2/5.14.2/gcc_64/bin/qmake" exited normally.
19:20:46: Starting: "/usr/bin/make" -f /home/lucas/Downloads/build-mediawriter-Desktop_Qt_5_14_2_GCC_64bit-Debug/Makefile qmake_all
cd lib/ && /opt/Qt5.14.2/5.14.2/gcc_64/bin/qmake -o Makefile /home/lucas/Downloads/MediaWriter-4.2.0/lib/lib.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd lib/ && /usr/bin/make -f Makefile qmake_all
make[1]: Entering directory '/home/lucas/Downloads/build-mediawriter-Desktop_Qt_5_14_2_GCC_64bit-Debug/lib'
cd isomd5/ && /opt/Qt5.14.2/5.14.2/gcc_64/bin/qmake -o Makefile /home/lucas/Downloads/MediaWriter-4.2.0/lib/isomd5/isomd5.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
cd isomd5/ && /usr/bin/make -f Makefile qmake_all
make[2]: Entering directory '/home/lucas/Downloads/build-mediawriter-Desktop_Qt_5_14_2_GCC_64bit-Debug/lib/isomd5'
make[2]: Nothing to be done for 'qmake_all'.
make[2]: Leaving directory '/home/lucas/Downloads/build-mediawriter-Desktop_Qt_5_14_2_GCC_64bit-Debug/lib/isomd5'
make[1]: Leaving directory '/home/lucas/Downloads/build-mediawriter-Desktop_Qt_5_14_2_GCC_64bit-Debug/lib'
cd theme/ && /opt/Qt5.14.2/5.14.2/gcc_64/bin/qmake -o Makefile /home/lucas/Downloads/MediaWriter-4.2.0/theme/theme.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
Project ERROR: adwaita-qt development package not found
/home/lucas/Downloads/build-mediawriter-Desktop_Qt_5_14_2_GCC_64bit-Debug/Makefile:118: recipe for target 'sub-theme-qmake_all' failed
make: *** [sub-theme-qmake_all] Error 3
19:20:47: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project mediawriter (kit: Desktop Qt 5.14.2 GCC 64bit)
When executing step "qmake"
19:20:47: Elapsed time: 00:01.
```

**Comment by dreua** [comment]
Hey, please edit your post and try to make it more valuable for everyone involved, a few ideas: Use code formatting for the log output. Use a more descriptive title, e.g., "Build error: adwaita-qt development package not found"

Most importantly: Give us some information to work with, like your platform / Linux distro and version, the steps you took that led to this error, like the build commands.

I'll hide this post once your edits are done.

**Comment by dreua** [comment]
It looks like this is about the adwaita-qt package. Is it installed von your system? Have you searched for the existence of a related devel or dev package?

(Are you sure you need to compile MediaWriter at all? If you just want to use it there may be easier options.)

**Comment by linucoybiloybiloy** [comment]
hi, howdy? I wanna compile this app and pack as appimage, for a better portation and easy path to use it in linux.
I'm using Lubuntu 18.04 lts for doing that. I have installed Adwaita-qt through out my package manager and I have unpacked the .deb file which contains a lib inside, how can I metion this lib during the compilation process? or is it possible for I desable this icon theme into the source code and use pure qt as the main theme for the application?
here says ":-1: error: adwaita-qt development package not found".

**Comment by linucoybiloybiloy** [comment]
by thw way I am suing qt creator 5.14.1, wich is enough for this build.

**Comment by grulja** [comment]
If you install adwaita-qt along with its devel subpackage (usually "-dev" suffix), then qmake should find it using pkg-config and you shouldn't need to modify it all.  You can also use a different theme, just disable building "theme" directory. However, none of Qt QML themes is as useable as the theme we ship.
