### ISSUE TITLE
Link to translation page is dead

### ISSUE THREAD

**Issue by cervyvin** [FedoraQt/MediaWriter#283]
Hi!

**Issue**
I saw a wrong translation in the app and wanted to correct it. Tried to visit the [link in this repo](https://fedora.zanata.org/iteration/view/mediawriter/master) but that link was dead for me.

I also tried to go through the [fedora translate page](https://translate.fedoraproject.org/) but could not find this project there either.

**Expected solution**
A valid link to the translation page or updated instructions on how to contribute to translations.

**Comment by grulja** [comment]
This is because Fedora migrated from Zanate to Webleta and we haven't finished the migration yet.

See https://github.com/FedoraQt/MediaWriter/issues/224.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/MediaWriter/pull/296.
