### ISSUE TITLE
Offer nightly images for QA Testing

### ISSUE THREAD

**Issue by andypillip** [FedoraQt/MediaWriter#289]
To participate at the Fedora Test Days it would be really handy to have an option for the currently nightly build, which seems to be only available as a net install.

This would render participation yet more accessible to a larger audience.

**Comment by dreua** [comment]
What is a net install?
Do you want a Flatpak, RPM or both?

Not sure whether the developers have some reasons not to have nightlies but at least an RPM should be easy to build and store as artifact. (It's always Zip-ed unfortunately, I hope you could live with that?)
For reference: We're already doing this [over at PDF Arranger](https://github.com/pdfarranger/pdfarranger/blob/522da53edf965bceb6465bbcdb74aed60bed6f8a/.github/workflows/install.yml#L32-L39), here is an [example of the results](https://github.com/pdfarranger/pdfarranger/actions/runs/726099712).

**Comment by andypillip** [comment]
Hi there. I'm so sorry, I was not very clear in my suggestion I realise.
I am referring to the images that Fedora Media Writer is offering.

There is potential to increase participation at the [QA Fedora Test Days](https://fedoraproject.org/wiki/QA/Test_Days) by making it convenient to create a Live USB for QA testing Fedora. Ideally you could choose the latest Beta release image, as well as a nightly image.

These nightly Fedora images seem to be only available as net install images, so there some additional magic would be necessary to get them conveniently onto a USB drive.

I hope I could clarify my suggestion?

**Comment by dreua** [comment]
I totally misunderstood your request, sorry! So if I understand correctly now, it is possible to Download a testing ISO yourself and write a bootable USB drive using FMW but you'd like to streamline this by haveing a "nightly" choice directly in FMW and letting it handle the downloading and verification of the ISO? Sounds like a good idea to me!

**Comment by dreua** [comment]
> These nightly Fedora images seem to be only available as net install images, so there some additional magic would be necessary to get them conveniently onto a USB drive.

This might be obvious to others but why and what additional magic would be necessary? Can't we just write the net install iso to a USB drive like any other image?

**Comment by andypillip** [comment]
There are two steps to this suggestion, I guess.

### 1 The Betas

On the [Fedora Workstation Download Page](https://getfedora.org/en/workstation/download/) you can download a simple ISO for the Beta to put on your USB.. The current F34 Beta is 1.3

Streamlining this by offering the Beta f.e. in the Labs section of FMW would be nice, and should be easy?

### 2 Fedora pre-release Nightly builds or Test Day Image

I'm quite new to this myself, so I don't have a lot of answers.

I just found the well hidden wiki page on [Creating a Test Day Live Image](https://fedoraproject.org/wiki/QA/Test_Days/Live_Image). So I guess FMW could offer a virtual _Test Day_ image which would automate these steps transparently to the user.

**Comment by dreua** [comment]
In my FMW I can already choose different versions, for example of the desktop install, including F34 beta. not sure whether that is 1.3, though. Are your aware of that?

The nightly builds you describe in (2) sound like something I'd do with a bash script on a server. Including the whole process in FMW does not make sense to me on the first glance. However, the process of downloading and writing the resulting ISO could be streamlined so that users just need to click a link or run a custom command which they receive via email or from a website. (Custom url handler, File Like flatpakref or just a command line argument? Maybe the latter is already possible?)

Keep in mind that I'm not a FMW dev but just another interested user trying to help with bug triage.

**Comment by andypillip** [comment]
Hei. Oh boy, that's right. I didn't expect it to be in a menu behind "Fedora 33", where you can switch version *after* choosing Desktop. So 1) is covered.

For 2) I agree, it would probably be up to the team that manages deployment to automate ISO creation, only than could FMW pick up the ISOs. It doesn't make sense to put additional logic into FMW.

Thanks for baring with me. Cheers!

**Comment by dreua** [comment]
You're welcome, happy to help :smiley:
