### ISSUE TITLE
Add FMW keyword to desktop file

### ISSUE THREAD

**Issue by dreua** [FedoraQt/MediaWriter#291]
I ended up typing FMW in the gnome search but got no results. Wouldn't hurt to add that as a keyword, would it? Would you like a PR?

**Comment by grulja** [comment]
Yes, please. Thank you.

**Comment by dreua** [comment]
#293 adds `fmw;usb;iso;bootable;` as keywords. I'd prefer that.

#295 adds only fmw as keyword. This is good enough, but more keywords would be better imo. (I remember searching for at least some of them when looking for this tool.)

Choice is up to you, just close the other PR. Thanks!
