### ISSUE TITLE
mediawriter does not start (fedora 34)

### ISSUE THREAD

**Issue by legacychimera247** [FedoraQt/MediaWriter#297]
hello,
used media writer to create an installation usb of fedora 34, and installed it. Now i want to revert back the usb key but the media writer does not start (in the installed fedora34), i would sent you a terminal output but i can't find the name for launching the app on the terminal

**Comment by grulja** [comment]
What is your MediaWriter version? You can start it from terminal running `mediawriter`.

**Comment by grulja** [comment]
You can check your version with `rpm -q mediawriter`.

**Comment by legacychimera247** [comment]
So, mediawriter proposed me to install the package "mediawriter" that i declined because i was thinking it was already installed via the gnome software center

Seems that this was not the case, althought it was listed as installed and had the icon. In the end anyway, installing the proposed package from the terminal was actually the solution, and everything is fine now

Honestly i don't know if that's a rare issue or it's common and it's worth solving

Feel free to close that if you think everything is ok

**Comment by dreua** [comment]
Maybe you installed the flatpak version of FMW, could you run `flatpak run org.fedoraproject.MediaWriter` and see what happens?

**Comment by legacychimera247** [comment]
well terminal gives me a long error message, and the app appear briefly then disappear, how weird...want too see the message?

**Comment by dreua** [comment]
Yes please. You can attach a file or use spoiler tags if you like.

**Comment by legacychimera247** [comment]
ok so, i thought i had installed mediawriter from rpm, now i am thinking it was from flatpak, maybe i've done some confusion cause now flatpaks from fedora are coming from  fedora "registry.fedoraproject" and rpms from fedora "fedoraproject"

anyway the rpm works fine, the flatpak is not starting giving me this error i told you

`Gtk-Message: 14:17:59.504: Failed to load module "pk-gtk-module"
Gtk-Message: 14:17:59.504: Failed to load module "pk-gtk-module"
W@97ms: Qt: Session management error: None of the authentication protocols specified are supported
W@108ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/iso/Fedora-Server-netinst-armhfp-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-33-1.2.armhfp.raw.xz"
W@108ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-33-1.2.armhfp.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-armhfp-33-1.2-sda.raw.xz"
W@109ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-33-1.2.iso"
W@109ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/armhfp/images/Fedora-Workstation-33-1.2.armhfp.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/armhfp/images/Fedora-Workstation-armhfp-33-1.2-sda.raw.xz"
W@109ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-libvirt.box"
W@109ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-virtualbox.box"
W@109ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/iso/Fedora-Scientific_KDE-Live-x86_64-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-libvirt.box"
W@109ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-virtualbox.box"
W@110ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/images/Fedora-Server-armhfp-32-1.6-sda.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/iso/Fedora-Server-netinst-armhfp-32-1.6.iso"
W@110ms: SHA256 hash of "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/iso/Fedora-Server-netinst-armhfp-32-1.6.iso" changed from "fff20ec4f6ce3ea232c74b80b7ffad935bfe213652aad669dedfabb54e98cefc" to "888ae8108f89b6f6e73815120f8e812daabaaf4479e3022ca40591f399eaad58"
W@110ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-32-1.6.iso" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-32-1.6.iso"
W@110ms: SHA256 hash of "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-32-1.6.iso" changed from "a241b624af5218cd8dc9b8459a34b6682d813fd6305ceab3d95e1f4da9803d7d" to "4d0f6653e2e0860c99ffe0ef274a46d875fb85bd2a40cb896dce1ed013566924"
W@110ms: Url "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-virtualbox.box"
W@110ms: SHA256 hash of "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-virtualbox.box" changed from "b18475f18de00bb3fd7d8300b755fa541e7521e34cc8be18592c5ef854520a96" to "01d0f81c361ab93dbafd9f64e2a08afbc739f5b4bf509529943b309244d95823"
W@111ms: Url "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-virtualbox.box" changed to "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-32-1.6.iso"
W@111ms: SHA256 hash of "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-32-1.6.iso" changed from "01d0f81c361ab93dbafd9f64e2a08afbc739f5b4bf509529943b309244d95823" to "d00ee0bd73d260eb7769d12a636cca86c54e486bf7335192a88ddd574ebaa51d"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
W@237ms: QGLXContext: Failed to create dummy context
F@405ms: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)`

**Comment by grulja** [comment]
> ok so, i thought i had installed mediawriter from rpm, now i am thinking it was from flatpak, maybe i've done some confusion cause now flatpaks from fedora are coming from fedora "registry.fedoraproject" and rpms from fedora "fedoraproject"
> 
> anyway the rpm works fine, the flatpak is not starting giving me this error i told you
> 
> `Gtk-Message: 14:17:59.504: Failed to load module "pk-gtk-module" Gtk-Message: 14:17:59.504: Failed to load module "pk-gtk-module" W@97ms: Qt: Session management error: None of the authentication protocols specified are supported W@108ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/iso/Fedora-Server-netinst-armhfp-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-33-1.2.armhfp.raw.xz" W@108ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-33-1.2.armhfp.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-armhfp-33-1.2-sda.raw.xz" W@109ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-33-1.2.iso" W@109ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/armhfp/images/Fedora-Workstation-33-1.2.armhfp.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/armhfp/images/Fedora-Workstation-armhfp-33-1.2-sda.raw.xz" W@109ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-libvirt.box" W@109ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-virtualbox.box" W@109ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/iso/Fedora-Scientific_KDE-Live-x86_64-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-libvirt.box" W@109ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-virtualbox.box" W@110ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/images/Fedora-Server-armhfp-32-1.6-sda.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/iso/Fedora-Server-netinst-armhfp-32-1.6.iso" W@110ms: SHA256 hash of "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/iso/Fedora-Server-netinst-armhfp-32-1.6.iso" changed from "fff20ec4f6ce3ea232c74b80b7ffad935bfe213652aad669dedfabb54e98cefc" to "888ae8108f89b6f6e73815120f8e812daabaaf4479e3022ca40591f399eaad58" W@110ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-32-1.6.iso" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-32-1.6.iso" W@110ms: SHA256 hash of "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-32-1.6.iso" changed from "a241b624af5218cd8dc9b8459a34b6682d813fd6305ceab3d95e1f4da9803d7d" to "4d0f6653e2e0860c99ffe0ef274a46d875fb85bd2a40cb896dce1ed013566924" W@110ms: Url "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-virtualbox.box" W@110ms: SHA256 hash of "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-virtualbox.box" changed from "b18475f18de00bb3fd7d8300b755fa541e7521e34cc8be18592c5ef854520a96" to "01d0f81c361ab93dbafd9f64e2a08afbc739f5b4bf509529943b309244d95823" W@111ms: Url "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-virtualbox.box" changed to "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-32-1.6.iso" W@111ms: SHA256 hash of "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-32-1.6.iso" changed from "01d0f81c361ab93dbafd9f64e2a08afbc739f5b4bf509529943b309244d95823" to "d00ee0bd73d260eb7769d12a636cca86c54e486bf7335192a88ddd574ebaa51d" libGL error: No matching fbConfigs or visuals found libGL error: failed to load driver: swrast W@237ms: QGLXContext: Failed to create dummy context F@405ms: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile QSurfaceFormat::NoProfile)`

This looks like an issue in the package itself (packaging issue). Doesn't seem to be related to MediaWriter. I will try to investigate anyway.

**Comment by grulja** [comment]
Looks like a flatpak issue: https://github.com/flatpak/flatpak/issues/138

**Comment by dreua** [comment]
Thanks for investigating!
OT: Open issue since 2016... I'm not a big fan of the flatpak ecosystem because there is a number of these issues :cry:
