### ISSUE TITLE
Writer doesn't write ISO (even though it says it is) and screen flickers on Windows 10.

### ISSUE THREAD

**Issue by buttery-potato** [FedoraQt/MediaWriter#298]
GPU drivers are fully updated.

**Comment by grulja** [comment]
I cannot reproduce. I installed FMW 4.2.1 on my Windows 10 (with Intel graphics card) and it wrote ISO image.

**Comment by buttery-potato** [comment]
I'm using an AMD RX 580. It very well could be my GPU drivers, but Rufus writes the exact same image just fine.

**Comment by grulja** [comment]
> I'm using an AMD RX 580. It very well could be my GPU drivers, but Rufus writes the exact same image just fine.

The screen flickering might be some driver issue (incompatibility with Qt), however, you should be able to write the image. Does it show any error? Can you share a screenshot?

**Comment by buttery-potato** [comment]
No error is produced. The writer just exits silently. I can’t take a screen recording right now but when I get in front of my PC I’ll do it.

**Comment by buttery-potato** [comment]
I updated my driver to 25.5.1, and it works fine now.

**Comment by grulja** [comment]
Thank you for letting us know. I'm glad it works now.
