### ISSUE TITLE
macOS: text is not displayed correctly

### ISSUE THREAD

**Issue by arthurk** [FedoraQt/MediaWriter#299]
I'm using Fedora media 4.2.1 writer on macos 10.15.7 and the text when writing the image to the drive does not display correctly:

![mediawritertext-crunch](https://user-images.githubusercontent.com/23406/116835136-cbd3f380-abf3-11eb-9425-e44ef31593ce.png)

**Comment by grulja** [comment]
I'm not able to reproduce on MacOS Catalina and I'm afraid I have no way how to test older version of MacOS. Does it happen everytime? When you resize the window, does it fix the issue?

**Comment by grulja** [comment]
I can reproduce on Windows.

**Comment by grulja** [comment]
Should be fixed with https://github.com/FedoraQt/MediaWriter/commit/e3f59e40b8fb48d26e93badc15d6c5f758e49b2a.
