### ISSUE TITLE
Missing program icon in notifications

### ISSUE THREAD

**Issue by joshas** [FedoraQt/MediaWriter#311]
Program notifications are missing icon. Could this be an issue with packaging? FMW 4.2.1 on Fedora 33.
![Screenshot from 2021-05-13 21-14-56](https://user-images.githubusercontent.com/79141/118168683-c87d0b00-b430-11eb-9e76-8933b90132c6.png)

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/MediaWriter/commit/fd917b33296518778d4ecf705cabbd87c86710a9.
