### ISSUE TITLE
Authentification dialog dismissed error message layout issue

### ISSUE THREAD

**Issue by joshas** [FedoraQt/MediaWriter#312]
Before starting write operation I accidentally pressed "Cancel" in authentication dialog. Error message "... authentication dialog was dismissed" layout in main window is broken.
![Screenshot from 2021-05-13 21-07-52](https://user-images.githubusercontent.com/79141/118169113-3d504500-b431-11eb-91f7-51cc8f926833.png)

**Comment by grulja** [comment]
This should be already fixed with https://github.com/FedoraQt/MediaWriter/commit/0c8d358df3dffa0c04d2a4445fde103ddbf9450c. The fix will be in the next release (4.2.2).
