### ISSUE TITLE
Update Media Writer downloads

### ISSUE THREAD

**Issue by aryanL-x86** [FedoraQt/MediaWriter#321]
[FedoraMediaWriter-osx-latest.dmg](https://getfedora.org:443/fmw/FedoraMediaWriter-osx-latest.dmg) in the Fedora website is not up-to-date as the [Releases](/FedoraQt/MediaWriter/releases) page.

**Comment by grulja** [comment]
Hi, I'm aware of that, it is being blocked by Fedora Engineering, see: https://pagure.io/releng/issue/10116
