### ISSUE TITLE
[Fedora 34] Possibility of missing dependency definition

### ISSUE THREAD

**Issue by mikunimaru** [FedoraQt/MediaWriter#339]
I installed a media writer on a minimal Fedora 34 with gnome-shell, gnome-terminal and nautilus installed. [(Is like this)](https://able.bio/KY64/minimal-installation-fedora-linux--73410e6d)
Basically it works comfortably, but the selection screen that opens by tapping the custom image is inoperable.

I don't think there are any practical problems because few people build minimal Fedora and those users are the type of users who can solve the problem on their own, but I will report it just in case.

**Comment by mikunimaru** [comment]
I have identified the missing dependencies.
The cause of the problem is that the QGnomePlatform is not included in the dependency.

**Comment by grulja** [comment]
It is not missing, there is just a bug in the Qt default implementation apparently and QGnomePlatform has slightly different implementation. I have a potential solution in mind to fix this. I will try to implement it as soon as possible.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/MediaWriter/pull/342.
