### ISSUE TITLE
The downloaded image is corrupted

### ISSUE THREAD

**Issue by wlucasmartino** [FedoraQt/MediaWriter#344]
I am following the official docs on Fedora's website to use Fedora Media Writer, like so:

1. Setup Flatpak on my system, following the guidelines on the Flatpak documentation page.
2. Run the Fedora Media Writer, not as sudo because I get the following: `error: "flatpak run" is not intended to be ran with sudo`. So I just run `flatpak run org.fedoraproject.MediaWriter`

When I am trying to create a live usb of Fedora Workstation 34, I get the error mentioned in the title: "The downloaded image is corrupted" and I cannot do anything else.

### Some output from the command line:
    "Error transferring http://fedora.zero.com.ar/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-34- 
    1.2.iso - server replied: Not Found"

    "W@10808ms: Computed SHA256 hash of "/home/lucas/Downloads/Fedora-Workstation-Live-x86_64-34-1.2.iso.part"  -  
    "2062d8a19c48eb6b420b0783e5865b510e671346d4a2aab15e77b42ad7c1d131" does not match expected 
    "865c4457dd066d3074c35a8847c8dac1380667c96a4f6d74526324dba14f1b5c"

    W@132395ms: Error QNetworkReply::ContentNotFoundError reading from 
    QUrl("http://fedora.zero.com.ar/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-34-1.2.iso") : "Error 
    transferring http://fedora.zero.com.ar/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-34-1.2.iso - 
    server replied: Not Found"

    W@132396ms: Computed SHA256 hash of "/home/lucas/Downloads/Fedora-Workstation-Live-x86_64-34-1.2.iso.part"  -  
    "3e26a5d106a3cf2e48aa14a197bf24d0959dde194fcf371c5ac7657ee85cc0bd" does not match expected 
    "865c4457dd066d3074c35a8847c8dac1380667c96a4f6d74526324dba14f1b5c"

**Comment by grulja** [comment]
Looks like there was some outage or your connection dropped or I don't know. Can you try one more time or different variant?

**Comment by wlucasmartino** [comment]
I recently tried and the issue remains. I don't think the problem is my connection, because all the services I use are working fine.

It's possible that the link `http://fedora.zero.com.ar/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-34- 
1.2.iso` is the problem? because I tried to access via web browser and I get a classic `404 Not Found`.

**Comment by grulja** [comment]
Links to images are on mirror and looks like you got one which is currently down. 

I opened a ticket: https://pagure.io/fedora-infrastructure/issue/10130

**Comment by grulja** [comment]
The ticket has been resolved. Can you try again?

**Comment by wlucasmartino** [comment]
It's working! The image is downloaded correctly.
