### ISSUE TITLE
Ability to leave the media opened

### ISSUE THREAD

**Issue by Ricky-Tigg** [FedoraQt/MediaWriter#349]
**OS:** Fedora;  **mediawriter v.:** 4.2.2 x86_64

_New feature request_ (Only if the feature can easily be implemented and maintained on supported systems by no more than one person – Ability to leave the media **opened**, so that new data can be written onto it, onto the free space

_Current properties of a created media_ | tested with Fedora server network installation ISO file. Media closed by _read-only_ after the verification of the written data is accomplished.
```
$ mount | grep /dev/sdc
/dev/sdc1 on /run/media/(...) type iso9660 (ro,nosuid,nodev,relatime,nojoliet,check=s,map=n,blocksize=2048,uid=1000,gid=1000,dmode=500,fmode=400,uhelper=udisks2)
# fdisk -l /dev/sdc | tail -4
Device     Boot Start     End Sectors  Size Id Type
/dev/sdc1  *        0 1325055 1325056  647M  0 Empty
/dev/sdc2         164   20539   20376  9.9M ef EFI (FAT-12/16/32)
/dev/sdc3       20540   63387   42848 20.9M  0 Empty
# parted /dev/sdc1 print | tail -2
 2      84,0kB  10,5MB  10,4MB  primary  fat16        esp
# parted /dev/sdc2 print | tail -2
 1      0,00B  10,4MB  10,4MB  fat16
# parted /dev/sdc3 print | tail -2
 1      0,00B  21,9MB  21,9MB  hfs+
```

**Comment by dreua** [comment]
I guess read only is beneficial for the built in checksum test on boot. Depending on the use case an additional empty partition may be the better option.

**Comment by Ricky-Tigg** [comment]
A source of inspiration in regards to the depicted feature could have been _Rufus_, but my suggestion had none.

![Rufus_Fedora_server_Persistance_feature](https://user-images.githubusercontent.com/26058215/130072767-45abafa7-9d9c-42ab-a4c4-b4d1342f968d.png)

There, the activation of that feature, referred as _persistence_, is governed by the property of the source file, here is one from an eligible file:
```
$ file -b Fedora-Server-netinst-x86_64-34-1.2.iso 
ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'Fedora-S-dvd-x86_64-34' (bootable)
```

**Comment by dreua** [comment]
> There, the activation of that feature, referred as _persistence_, is governed by the property of the source file, here is one from an eligible file:

Which property do you mean?

**Comment by Ricky-Tigg** [comment]
On purpose i did not make mention of cases represented by source files that are not eligible since this was implicit. I cover it now to be explicit then. An installation file obtained by the tool available on that [site](https://support.microsoft.com/en-us/windows/create-installation-media-for-windows-99a58364-8c02-206f-aa6f-40c3b507420d) won't trigger the exhibition of that _persistence_ tool.

Then that's according to those cases that may be or not be eligible to trigger the exhibition of that _persistence_ tool that i could conceive the obvious, which is that there must be a propriety within the disk image that governs it. That property, i would not know at all unless i was one of the developers of that software.
