### ISSUE TITLE
Window too small after switching to another program and back

### ISSUE THREAD

**Issue by joshas** [FedoraQt/MediaWriter#351]
Started writing new image to USB flash drive, switched to another window and when switched back to Fedora Media Writer, "Write Custom image" window was resized and bottom buttons were cut off.

![Screenshot from 2021-08-13 19-41-03](https://user-images.githubusercontent.com/79141/129444902-f2772437-a616-40df-8549-9d936ada106b.png)

Fedora 34 (Workstation Edition), GNOME 40.3.0, Wayland.

**Comment by grulja** [comment]
This will be fixed in the upcoming version which completely changed design.
