### ISSUE TITLE
Update to Fedora 35

### ISSUE THREAD

**Issue by romulasry** [FedoraQt/MediaWriter#359]
For the latest fedora version? Or do you want to wait until it formally releases?

**Comment by romulasry** [comment]
August 10, 2021 / Ben Cotton / 2 Comments	

Fedora Linux 35 branches from Rawhide today.

**Comment by grulja** [comment]
We don't need to make a release when a new Fedora is released. The list of images is downloaded everytime FMW is started so it always offers the latest and greatest.
