### ISSUE TITLE
FMW doesn't work on Apple M1 devices (arm64)

### ISSUE THREAD

**Issue by nullr0ute** [FedoraQt/MediaWriter#360]
When trying to use media writer to write out a Fedora 35 Beta (x86_64) live image the FMW fails to run on a M1 based Mac at all. The error it provides is "“Fedora Media Writer” can’t be opened because Apple cannot check it for malicious software." and then says "This software needs to be updated. Contact the developer for more information."

**Comment by grulja** [comment]
Hi, did you download it from here or from https://getfedora.org/?

**Comment by nullr0ute** [comment]
Yes, the one linked for Fedora 35 Beta if that makes a difference

**Comment by C47F15H** [comment]
> The error it provides is "“Fedora Media Writer” can’t be opened because Apple cannot check it for malicious software." and then says "This software needs to be updated. Contact the developer for more information."

If you get a warning like that, go to System Preferences > Security & Privacy > General and click "Allow".
It does not depend on the computer chip (Intel/Arm)

**Comment by nullr0ute** [comment]
> If you get a warning like that, go to System Preferences > Security & Privacy > General and click "Allow". It does not depend on the computer chip (Intel/Arm)

Why doesn't the OS prompt me if I want to allow the access like other apps do?

**Comment by C47F15H** [comment]
That is because the app isn't notarized by Apple
https://support.apple.com/en-gb/HT202491

**Comment by grulja** [comment]
This is still (hopefully) in progress. Closing as duplicate https://github.com/FedoraQt/MediaWriter/issues/317.
