### ISSUE TITLE
Add Fedora Kinoite support

### ISSUE THREAD

**Issue by Schmensch** [FedoraQt/MediaWriter#364]
With Fedora Kinoite now released as a beta, I'd like it to be listed within the "Emerging Fedora Editions" category.

**Comment by dreua** [comment]
I think FMW sources all it's data from the getfedora website. Is it listed there?

**Comment by grulja** [comment]
We get data from https://getfedora.org/releases.json and it already lists Kinoite, problem is that we don't have a logo for Kinoite to present it in the view.

**Comment by sanecito** [comment]
Discussion on logo candidates looks to be happening at the meeting at the end of November: https://pagure.io/design/issue/710
