### ISSUE TITLE
Restoring usb drive doesnt work

### ISSUE THREAD

**Issue by Lomppu** [FedoraQt/MediaWriter#370]
Received an old laptop with two ssd:s and no os on either of them. Used one 8gb usb drive to install Win11 on one of the drives, and used MediaWriter in that Win11 to write the latest Fedora Workstation on that same 8gb usb drive.

Usb didnt show up in boot menu, so I went back to Windows. The Usb drive is now unusable, shows up in Diskpart but gives out "access denied" for every command, and using the MediaWriter to restore the drive runs for a second, says it finished succesfully, but nothing changes. Plugging the drive in again makes MediaWriter prompt me again to restore the drive.

Is this usb drive history? Thanks for the help.

**Comment by dreua** [comment]
Did you run those diskpart commands as root / administrator?

**Comment by Lomppu** [comment]
I used EaseUs software to partition the drive and windows disk manager to format it. Now it works again. Will try installing fedora with it again, let's see if that works this time.

**Comment by Lomppu** [comment]
Never mind, the usb drive doesnt work after all. I managed to get it temporarily in to a state where I could write data on it by 
1. letting MediaWriter "restore" it to factory settings
2. creating a volume on it in windows disk manager
3. formatting it in EaseUs (can not format in windows explorer, disk manager or diskpart)
with these steps I can consistenly repeat the state of the usb drive, but as soon as I unplug it or restart windows, the usb drive reverts to being unusable. 
MediaWriter will prompt me in every one of those 3 steps that there is a live system on the drive and it can be restored. Even after I copied some random videos on there and watched them on the drive, perfectly functional.
What is going on?

**Comment by dreua** [comment]
Sounds like an issue with that drive to me, not a MediaWriter issue. Maybe a hardware failure. I remember having strange issues with USB drives, especially when using older USB drives. They all went a way (and flashing + installation becomes much faster) with a new, decent USB 3 drive. They are not that expensive for 8 GB either, but be sure to not buy fake drives, they seem to be quite common.

**Comment by Lomppu** [comment]
you might be right, time to ditch this old one. thanks.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Only Fedora Media Writer is not able to restore my installation media. All else has been able to restore it. I have utilised one Serial ATA 64-gigabyte solid-state drive that is connected via Universal Serial Bus for installation of Fedora Silverblue, and Fedora Kinoite, and Fedora Workstation, and the network-installer that is for Fedora Server. Subsequent restoration has been successful via the “partitionmanager” of KDE Plamsa.
