### ISSUE TITLE
Fedora i3 Window Manager Spin is not listed

### ISSUE THREAD

**Issue by X3MBoy** [FedoraQt/MediaWriter#374]
When displaying the full configuration of options to install, the Fedora i3 Window Manager Spin is not shown in the list,

**Comment by X3MBoy** [comment]
Need to clarify, it's not listed in the Windows version 4.2.2

**Comment by termdew** [comment]
I built it with the current main branch, it's listed there. Could you rebuild and verify?

**Comment by X3MBoy** [comment]
I would love to, but I don't know how. Let me try to follow the instructions provided and see how it goes.
