### ISSUE TITLE
Selecting Fedora Workstation from the menu not working

### ISSUE THREAD

**Issue by superuser-miguel** [FedoraQt/MediaWriter#376]
Test on Fedora 34 Workstation : 

From the menu, selecting Fedora Workstation 35 currently downloads and burns a Fedora 35 Workstation image. 
**Installs** `Fedora-Workstation-Live-x86_64-34-1.2.iso`
**Expected** `Fedora-WS-Live-35-1.2.iso`

**Comment by grulja** [comment]
I cannot reproduce. I just opened FMW, picked to download latest Fedora Workstation and I can see it downloads `Fedora-Workstation-Live-x86_64-35-1.2.iso`.
