### ISSUE TITLE
Mediawriter doesn't use native system theme when used under Fedora KDE spin

### ISSUE THREAD

**Issue by raghu-kamath** [FedoraQt/MediaWriter#379]
Media writer uses adwaita theme despite the system theme being breeze. I read a [blog post](https://egastablog.wordpress.com/2021/12/10/first-post/) mentioning that windows and macos will have native styling. It would be great if media writer used system theme and styling under linux too rather than hardcoded theme.

**Comment by grulja** [comment]
This will be possible once KDE Breeze theme is ported to Qt 6.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/FedoraQt/MediaWriter/issues/379#issuecomment-1108482444

@grulja, the Breeze theme has been ported to Qt6, per https://packages.fedoraproject.org/pkgs/plasma-breeze/plasma-breeze-qt6/fedora-40.html#provides.

**Comment by grulja** [comment]
> > [#379 (comment)](https://github.com/FedoraQt/MediaWriter/issues/379#issuecomment-1108482444)
> 
> @grulja, the Breeze theme has been ported to Qt6, per https://packages.fedoraproject.org/pkgs/plasma-breeze/plasma-breeze-qt6/fedora-40.html#provides.

Yes, I know. I've tested it already. Can be closed now.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/FedoraQt/MediaWriter/issues/379#issuecomment-2022883294

@grulja, are you referring to https://github.com/FedoraQt/MediaWriter/pull/659#event-10677110795 (per https://github.com/FedoraQt/MediaWriter/releases/tag/5.1.0)?
