### ISSUE TITLE
Disk Format Feature

### ISSUE THREAD

**Issue by G-M0N3Y** [FedoraQt/MediaWriter#388]
Really enjoy using this on Fedora 35 so far.  Especially the options for Fedora Labs and Spins and the option to automatic write to usb. Have you considered a erase/format FAT32 feature similar to the Raspberry Pi Imager tool? I know other tools within Fedora accomplish this but it would be a great feature to integrate, making this a one stop shop for making bootable media. I'll never use Balena Etcher again eitehr way . Great tool. Thanks !

**Comment by grulja** [comment]
You can format your USB drive afterwards. If you again open FMW or insert your USB drive while having FMW opened, you will get a popup on the top asking you whether you want to restore your drive.
