### ISSUE TITLE
Port the app with GTK4 with libadwaita

### ISSUE THREAD

**Issue by tsunamistonefly** [FedoraQt/MediaWriter#390]
Currently, Fedora MediaWriter UI doesn't align with the new design from GNOME 42. Porting it to libadwaita would make it to get aligned with GNOME design principles. 

By the way, MediaWriter doesn't look native: 

- There is a different gradient in the titlebar
- When dragging the window, the titlebar becomes light grey, a thing that doesn't happen in GTK3 apps
- Close button hover state is incorrect and there is no pressed state
- Font antialiasing is subpixel instead of grayscale, which is the default mode in GNOME

**Comment by grulja** [comment]
There is a new Fedora MediaWriter UI in progress, but it is still written in Qt/QML. Anyway, most of the issues you mention with the titlebar etc. are actually not issues in MediaWriter, but in decorations that come from QGnomePlatform.
