### ISSUE TITLE
I'm having an error during the compilation process in debian 11

### ISSUE THREAD

**Issue by lucasmz1** [FedoraQt/MediaWriter#416]
when I open the app without sudo and click in the box choose a file it freeze when open a gtk window but if I run as sudo it opens a qt window and everything works fine.
how do I enable the qt window without use sudo ?
this is what the terminal says.
I debugged on terminal and it show this log.

Gtk-Message: 20:17:27.266: GtkDialog mapped without a transient parent. This is discouraged.
W@4108ms: Model size of -34 is less than 0
Gtk-Message: 20:21:42.192: GtkDialog mapped without a transient parent. This is discouraged.

![Captura de tela de 2022-04-17 20-22-00](https://user-images.githubusercontent.com/95252125/163735886-fd252e03-c5f7-4392-ab8d-938f8c13e0da.png)

how do I fix it ?

**Comment by grulja** [comment]
I'm afraid this is not issue in Fedora MediaWriter but rather in the `xdg-desktop-portal-gtk`.

What is your version of `xdg-desktop-portal` and `xdg-desktop-portal-gtk`?

**Comment by grulja** [comment]
We already have this issue opened as https://github.com/FedoraQt/MediaWriter/issues/277.

I guess you don't have `xdg-desktop-portal[-gtk]` installed and therefore you use Qt implementation which is causing this issue.

**Comment by lucasmz1** [comment]
hello again here says I'm using the newest version: xdg-desktop-portal-gtk is already the newest version (1.0.2-0ubuntu1.1).
how do I enable to use only qt ?
is there any possibility?

**Comment by grulja** [comment]
> hello again here says I'm using the newest version: xdg-desktop-portal-gtk is already the newest version (1.0.2-0ubuntu1.1). how do I enable to use only qt ? is there any possibility?

Does it run? Do you see xdg-desktop-portal and xdg-desktop-portal-gtk process running? The version you have is quite old so it might be issue there as well.

Can you run `dbus-monitor --session` in a terminal, keep it running and run FMW trying to open the dialog. Once it freezes, you can paste the output somewhere (e.g. pastebin.com) and post the link here. From that we will now for sure whether it opens file dialog from Qt or using portals.
