### ISSUE TITLE
Improve presentation of cancel dialog

### ISSUE THREAD

**Issue by allanday** [FedoraQt/MediaWriter#420]
It currently looks like this:

![image](https://user-images.githubusercontent.com/213068/164415722-19571a1a-5204-4f3e-9070-73569a24d0e4.png)

There's a bunch of issues here:

 * The title is "MediaWriter", which isn't helpful
 * There's a close button in the title bar - this is non-standard for a confirmation dialog, and its purpose will be unclear (I don't see a way to avoid this with Qt Quick dialogs though)
 * Typically the format of a confirmation dialog is to have a heading with a longer description below; the lack of heading makes the window harder to read
 * The layout isn't very pleasing - it mixes centered alignment for the text, with right alignment for the buttons, and the margins are off
 * The dialog doesn't appear to be modal - its position over its parent isn't fixed, and the parent doesn't appear non-interactive

This is a tricky one, given that Windows, Mac and GNOME have different conventions for confirmation dialogs, plus there are constraints to what we can do with Qt Quick. Given that both Windows and Mac use left/right alignment for their confirmation dialogs, perhaps a layout like this might work best overall?

![image](https://user-images.githubusercontent.com/213068/164426151-c85e1ca5-2daa-42be-b753-a6ec1a369650.png)

**Comment by grulja** [comment]
The process currently consists from 3 steps:
- Download
- Writing
- Data verification

Do we want to have a generic dialog/text for all of them or just slightly different text for each step? 

Like:
**Cancel Download** / **Cancel Writing** / **Cancel Verification**
Download progress will be lost and media writing will be aborted / Writing process will be aborted and your drive will have to be restored afterwards / This operation is safe to be cancelled.

**Comment by allanday** [comment]
> Do we want to have a generic dialog/text for all of them or just slightly different text for each step?

I think that it would be good to make sure that the cancel dialog text is consistent with the progress text, so if the progress text says "downloading", the dialog says "cancel download". Otherwise we end up in a situation where the progress says "downloading" and the dialog says "cancel write", which doesn't make sense.
