### ISSUE TITLE
Jiggly progress bar download text

### ISSUE THREAD

**Issue by allanday** [FedoraQt/MediaWriter#422]
The progress bar text frequently changes width as the download size changes, which doesn't look great. Would it be possible to use tabular numbers for the download size? That would reduce the jiggle.

**Comment by grulja** [comment]
This is duplicate of https://github.com/FedoraQt/MediaWriter/issues/278.

**Comment by allanday** [comment]
Sorry for the noise!

**Comment by grulja** [comment]
> Sorry for the noise!

No problem at all. It's hard to get oriented in the list of bugs we have reported against FMW.
