### ISSUE TITLE
Media Writer cannot be opened on macOS 12.3.1

### ISSUE THREAD

**Issue by davide125** [FedoraQt/MediaWriter#445]
On macOS 12.3.1 I get this error when trying to open Fedora Media Writer:

> “Fedora Media Writer” can’t be opened because Apple cannot check it for malicious software.
> This software needs to be updated. Contact the developer for more information.

This is on a M1 macbook pro, in case it matters.

**Comment by davide125** [comment]
<img width="1101" alt="Screen Shot 2022-04-26 at 7 41 51 AM" src="https://user-images.githubusercontent.com/397089/165434750-ffbd6841-b016-493e-87cb-d25bbb760b99.png">

**Comment by grulja** [comment]
See https://github.com/FedoraQt/MediaWriter/issues/360.

Currently it doesn't matter whether you downloaded from getfedora.org or from GitHub, none of them is notarized (yet) and therefore you have to go to System Preferences > Security & Privacy > General and click "Allow". Then you should be able to open it.
