### ISSUE TITLE
Renewing a download makes the Writing dialog stuck

### ISSUE THREAD

**Issue by kparal** [FedoraQt/MediaWriter#461]
Reproducer:
1. pick an image to download, start downloading
2. cancel the download after a while
3. pick the same image again, the download will continue where it left off
4. after the download is complete, FMW is forever stuck at the writing phase (at 0%)
![Screenshot from 2022-05-06 11-45-26](https://user-images.githubusercontent.com/755451/167108192-740e2e8e-4081-44d7-b4a6-9965fb6d4949.png)
5. But, after a while, I receive a notification that writing was completed! FMW still looks the same as above, though.

It seems that when a download is stopped and renewed, the GUI gets stuck, but the writing process works. It's just GUI which is not updating.

```
mediawriter-4.9.99-2.fc36.x86_64
```

**Comment by grulja** [comment]
I can reproduce.

**Comment by grulja** [comment]
My guess is that after the download process is cancelled there is some state that doesn't get restored correctly and that confuses the writing process once we resume the dowload.
