### ISSUE TITLE
Restoring a flash drive on Windows creates a FAT16 partition, which is unusable on larger drives

### ISSUE THREAD

**Issue by kparal** [FedoraQt/MediaWriter#464]
When I restore the flash drive on Fedora, it creates a FAT32 partition which can be mounted and works. My flash drive size is 64GB, and the partition covers the whole space.

However, when I restore the flash drive on Windows 10, it creates a FAT16 partition which can't be mounted (in Windows nor in Fedora), and Windows immediately pops up with a message:
> You need to format the disk in drive X: before you can use it. Do you want to format it?

This is not really a problem, I can use the Windows popup to format the drive (it uses exFAT by default) and have it usable. But I wonder, is this necessary? Can't it create also at least FAT32 partition like on Fedora? Or exFAT?

And why is FAT16 partition unusable on both systems? I think it's because the maximum partition size is 2GB, but it is created over the whole 64GB, and therefore it's seen as corrupted. In that case, wouldn't it be better to not create a filesystem there at all?

FMW 4.99.50-3441cb7 on Windows 10

**Comment by Conan-Kudo** [comment]
We should probably use ExFAT by default now. It's supported in most Linux distributions, Windows, and macOS these days.

**Comment by grulja** [comment]
I will check. The code definitely use "fs=fat32" option for formatting so I have to check why it created FAT16 instead.

**Comment by kparal** [comment]
I just did that again. This is what gnome-disks shows:

![Screenshot from 2022-05-06 14-50-05](https://user-images.githubusercontent.com/755451/167134636-18a484d5-e194-41b8-9931-7755bdfa1178.png)

Notice it can't be mounted. Nautilus doesn't show it at all.

And fdisk:
```
$ sudo fdisk -l /dev/sda
[sudo] password for kparal: 
Disk /dev/sda: 58,44 GiB, 62746787840 bytes, 122552320 sectors
Disk model: Extreme         
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x6400acdb

Device     Boot Start       End   Sectors  Size Id Type
/dev/sda1        2048 122552319 122550272 58,4G  6 FAT16
```

```
$ sudo mount /dev/sda1 /mnt/
mount: /mnt: wrong fs type, bad option, bad superblock on /dev/sda1, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
```
(there's no info in dmesg or journal)

**Comment by kparal** [comment]
I have Windows 10 Pro version 21H2.

**Comment by kparal** [comment]
I just tested with a 1GB flash drive, and voila, it gets restored as FAT32. So seems to be definitely related to the drive size. What was your drive size, @grulja ?

**Comment by grulja** [comment]
> I just tested with a 1GB flash drive, and voila, it gets restored as FAT32. So seems to be definitely related to the drive size. What was your drive size, @grulja ?

16GB

**Comment by kparal** [comment]
Please make a new build and I'll test if exfat fixes the problem.

**Comment by grulja** [comment]
> Please make a new build and I'll test if exfat fixes the problem.

It builds automatically. It should be already on the release page.

**Comment by grulja** [comment]
Tested, for me it created: `HPFS/NTFS/exFAT`

**Comment by kparal** [comment]
It worked for both my 64GB and 1GB flash drives on Windows 10! Created an exfat partition, can be mounted and used on both Windows and Linux.

I'd also like to try restoring in Linux, but the flatpak version is not up-to-date yet. Can you create flatpak version and perhaps also a koji build? It has enough fixes now, let's tell people in test list to use the latest rpm.

**Comment by kparal** [comment]
On Linux with [this](https://koji.fedoraproject.org/koji/taskinfo?taskID=86726592) it still creates FAT32 and not exFAT. Is that expected?

**Comment by grulja** [comment]
> It worked for both my 64GB and 1GB flash drives on Windows 10! Created an exfat partition, can be mounted and used on both Windows and Linux.
> 

Good.

> I'd also like to try restoring in Linux, but the flatpak version is not up-to-date yet. Can you create flatpak version and perhaps also a koji build? It has enough fixes now, let's tell people in test list to use the latest rpm.

I did create a new scratch build https://koji.fedoraproject.org/koji/taskinfo?taskID=86726403. I didn't change anything in drive restoration for the Linux verions of FMW so there is probably nothing to test about it.

**Comment by grulja** [comment]
@kparal we now use ExFAT also on Linux and macOS. You can test it if you want, but I already verified both myself.

**Comment by kparal** [comment]
Works even on my flash drives, thanks.
