### ISSUE TITLE
Small graphic on start screen

### ISSUE THREAD

**Issue by GuiltyDoggy** [FedoraQt/MediaWriter#465]
The graphic on the start screen is appearing small.

[Screenshot](https://nextcloud.matsumura.family/s/gaysksKjk8sZ7AR)

[System Info](https://paste.centos.org/view/2ecf0d35)

Flatpak version - 4.99.50-d66bcd3

System:
  Kernel: 5.17.5-300.fc36.x86_64 arch: x86_64 bits: 64 Desktop: KDE Plasma
    v: ERR-101 Distro: Fedora release 36 (Thirty Six)
Graphics:
  Device-1: AMD Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] driver: amdgpu
    v: kernel
  Device-2: HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo
  Display: wayland server: X.Org v: 1.22.1.1 compositor: kwin_wayland
    driver: gpu: amdgpu resolution: 3840x2160~120Hz
  Message: Wayland GBM/EGL data currently not available.

**Comment by kparal** [comment]
Just a tip, @GuiltyDoggy . You can upload pictures and text files directly here into github issues. Then there is no risk that the hosting you're using goes down and those artifacts become unreachable. Which is exactly what will happen to that pastbin link in a few hours:
> This paste will join the choir invisible in 6 Hours.

**Comment by kparal** [comment]
Also, for comparison, does the old FMW 4.2 work better on your hardware?

**Comment by GuiltyDoggy** [comment]
> Just a tip, @GuiltyDoggy . You can upload pictures and text files directly here into github issues. Then there is no risk that the hosting you're using goes down and those artifacts become unreachable. Which is exactly what will happen to that pastbin link in a few hours:
> 
> > This paste will join the choir invisible in 6 Hours.

My apologies, I will do that from here on out.

> Do you have your font size increased from the default one? Or are you using resolution scaling? I see that you have a 4K screen. If you reset all font sizes/resolution scaling/etc to default, does it help in some way? Or if you switch to 1920x1080, does that help?

My resolution scale is at 100%. 
![Resolution Scale](https://user-images.githubusercontent.com/52749251/167130969-953e7fac-7ed0-4e68-9d01-d1546c2384a7.png)

Changing to 1080p does not fix it.
![1080p](https://user-images.githubusercontent.com/52749251/167131330-38012f07-d8f2-4659-8238-0c39328a3a9e.png)

Fonts DO affect it. Default font settings restore the graphic size:
![Fonts Default](https://user-images.githubusercontent.com/52749251/167131593-e94fb2c9-18d4-4b7b-9e36-a919d95f9dd5.png)
My font settings:
![Fonts Custom](https://user-images.githubusercontent.com/52749251/167132101-dae22970-1571-4615-abc6-1a7e83dc4f99.png)

**Comment by GuiltyDoggy** [comment]
> Also, for comparison, does the old FMW 4.2 work better on your hardware?

4.2 has worked flawlessly for me.

**Comment by kparal** [comment]
OK, I think #466 #467 #468 can be all merged into this one. FMW doesn't react well to an increased font size. Instead of making the window bigger, it has fixed size and then the contents doesn't fit. The question is whether it's a fault of FMW or QT in general.

**Comment by kparal** [comment]
@GuiltyDoggy Can you please re-download and re-install the flatpak and test?

**Comment by GuiltyDoggy** [comment]
Can confirm that issue is resolved. Thanks.
