### ISSUE TITLE
The latest version of MediaWriter cannot download and write any Server images.

### ISSUE THREAD

**Issue by lruzicka** [FedoraQt/MediaWriter#470]
When trying to choose a Fedora Server image, I cannot choose anything, because the applications only displays "0".
Check the screenshot. Other variants are at least shown. I tried to download about 5 of them and they were downloaded indeed.

https://imgur.com/a/ZoOE1Y1

I have seen this on all version of the new Mediawriter, incl. mediawriter-4.9.99-3.fc36.x86_64

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/MediaWriter/pull/472.

**Comment by kparal** [comment]
Seems to work fine with the latest build.
