### ISSUE TITLE
When download is cancelled, Mediawriter inform about deleting the underlying file but it does not delete it.

### ISSUE THREAD

**Issue by lruzicka** [FedoraQt/MediaWriter#471]
Basically, the title says everything. When the download is cancelled, the incomplete `*.iso.part` file stays in the Download location, although the application claims that it will be deleted and the download will not be resumed later.

System: Fedora 36
Version: mediawriter-4.9.99-3.fc36.x86_64

**Comment by lruzicka** [comment]
Yes, that is the screen. I believe that if the function is the be able to resume the download later, the application should say so. 
I think that *download progress* will be lost means that **what has been downloaded will be gone and you will not be able to reuse it later.** Am I wrong?

**Comment by kparal** [comment]
The message is now clearer, thanks.
