### ISSUE TITLE
Restore option disappears after I choose Select ISO and hit Back

### ISSUE THREAD

**Issue by kparal** [FedoraQt/MediaWriter#475]
When I start FMW, there's a Restore option. When I choose Select ISO, and then hit Back, the Restore option is missing. I have to restart FMW.

See this video:
[video.zip](https://github.com/FedoraQt/MediaWriter/files/8640180/video.zip)

FMW 4.99.50

**Comment by kparal** [comment]
A pro tip. Rename mkv into mp4, and github will allow to upload it and play it:

https://user-images.githubusercontent.com/755451/167149070-2cc0a79b-fbbc-4186-ac71-5ebd43df37cb.mp4

**Comment by kparal** [comment]
A slight issue, now it happens in reverse :-D

https://user-images.githubusercontent.com/755451/167361558-00c2c08d-c87f-4e26-8a15-e3efade69947.mp4

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/MediaWriter/pull/498.

**Comment by kparal** [comment]
Seems to work fine now.
