### ISSUE TITLE
macOS - Restore is broken

### ISSUE THREAD

**Issue by GuiltyDoggy** [FedoraQt/MediaWriter#482]
Using the Restore option will change the screen to the restore screen, but the progress bar does not move. 

* The Restore button will not do anything. 
* Going back to try to use the USB drive, it is no longer detected by FMW
* The USB drive no longer shows up in Finder
* Crucially, unplugging and plugging the USB drive in the Mac no longer mounts the drive, nor does it bring up the dialog saying it is unreadable (Eject/Ignore/Initialize). The drive is now no longer usable by macOS.

https://user-images.githubusercontent.com/52749251/167145664-ebb01130-0b3c-4f05-b846-06fec1551c09.mp4

Examining the disk in Linux shows that the disk was formatted. 
```
NAME   FSTYPE FSVER LABEL     UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
sdc                                                                               
└─sdc1 vfat   FAT32 FLASHDISK 4A2A-100D                              31.2G     0% /run/media/yosuke/FLASHDISK


Disk /dev/sdc: 31.22 GiB, 33520877568 bytes, 65470464 sectors
Disk model: USB 3.0 FD      
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start      End  Sectors  Size Id Type
/dev/sdc1        2048 65470463 65468416 31.2G  b W95 FAT32
  
```                                   

Creating a new partition table (dos or gpt) using fdisk on Linux makes the disk recognizable by macOS again and prompts to Eject/Ignore/Initialize upon plugging in.

**Comment by grulja** [comment]
Restoring the drive works for me. It appears to be successfuly restored and I'm able to mount it in Finder. This is on macOS Big Sur (11.6.5).

**Comment by GuiltyDoggy** [comment]
I am on macOS Monterrey (12.3.1)

**Comment by GuiltyDoggy** [comment]
I think this may be linked to #480. Rebooting the Mac and doing the Restore completes successfully. There must have been something "stuck" after the crash in 480 that prevented Restore cleanly.

**Comment by grulja** [comment]
> I think this may be linked to #480. Rebooting the Mac and doing the Restore completes successfully. There must have been something "stuck" after the crash in 480 that prevented Restore cleanly.

Maybe the helper got stuck. I will investigate the crash, but as I mentioned in #480, it looks like a crash in Qt.

**Comment by grulja** [comment]
I will close this now as you said it worked for you after all. I re-tested it again and it worked just fine. Issue #480 is fixed so hopefully it shouldn't happen anymore.
