### ISSUE TITLE
5.0 release. Download error, bad localization and other problems.

### ISSUE THREAD

**Issue by user12981** [FedoraQt/MediaWriter#502]
I have a dowload error, even if I use a vpn. Version 4.2 worked fine. I use Fedora 36.
![Снимок экрана от 2022-05-10 09-07-58](https://user-images.githubusercontent.com/105268505/167562040-0367250b-7aa5-4f8c-be04-3443f537619d.png)
![Снимок экрана от 2022-05-10 09-08-27](https://user-images.githubusercontent.com/105268505/167562090-373241c3-2110-4ab5-8d6e-328068323d73.png)
![Снимок экрана от 2022-05-10 09-08-38](https://user-images.githubusercontent.com/105268505/167562102-9a2f6a4f-7274-42bc-9099-8446511a4cf4.png)
 
 Why did you remove the pictures, description and the size of the distribution? It was very convinient

**Comment by grulja** [comment]
You will be able to start downloading only after you plug in an USB drive. The issue with translations is something that people doing translations have to fix themself or alternatively you can suggest a fix yourself here: https://translate.fedoraproject.org/projects/fedora-media-writer/mediawriter/
