### ISSUE TITLE
Pt-BR translations didn't get right on a Pt-BR locale machine

### ISSUE THREAD

**Issue by geraldosimiao** [FedoraQt/MediaWriter#509]
It seems I'm looking for Pt-pt strings, mixed with english, and not the right Pt-BR ones.

System Locale: LANG=pt_BR.UTF-8
VC Keymap: br
X11 Layout: br
mediawriter-5.0.0-2.fc36.x86_64
Operating System: Fedora Linux 36
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.3
Kernel Version: 5.17.7-300.fc36.x86_64 (64-bit)
X11 and Wayland

![Screenshot_20220512_202601](https://user-images.githubusercontent.com/72357821/168183253-82fca3cd-4c33-4589-a40d-60b2b7f24782.png)

**Comment by grulja** [comment]
Fixed in 5.0.1.

**Comment by geraldosimiao** [comment]
ok, thank you.
