### ISSUE TITLE
Download automaticaly button and selection apears as "download failed" on my translation

### ISSUE THREAD

**Issue by geraldosimiao** [FedoraQt/MediaWriter#510]
mediawriter-5.0.0-2.fc36.x86_64
   System Locale: LANG=pt_BR.UTF-8
   VC Keymap: br
   X11 Layout: br

Operating System: Fedora Linux 36
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.3
Kernel Version: 5.17.7-300.fc36.x86_64 (64-bit)
Graphics Platform: X11 and Wayland (happens on both)

![Screenshot_20220512_201150](https://user-images.githubusercontent.com/72357821/168183604-60c172dd-4e54-42bf-8901-b27bbbc8ed75.png)

![Screenshot_20220512_201338](https://user-images.githubusercontent.com/72357821/168183629-862d4567-5e9b-4de1-a322-70b96c513493.png)

**Comment by grulja** [comment]
Fixed in 5.0.1.

**Comment by geraldosimiao** [comment]
Thanks :)
