### ISSUE TITLE
USB Drive in read-only mode

### ISSUE THREAD

**Issue by Sebicci** [FedoraQt/MediaWriter#518]
I recently installed Fedora 36 final version on my USB drive with Fedora Media Writer in Fedora 36 beta. It worked well, everything was fine 'til I plugged that USB drive on Windows 10.

I am not able to do anything on the drive. It seems to be in some kind of read-only mode.

Please how can I fix this issue ?

**Comment by grulja** [comment]
Use Fedora Media Writer again to restore your USB drive. Once you plug it it, you will get an option to restore your USB drive from the main page.
