### ISSUE TITLE
Updating Live image

### ISSUE THREAD

**Issue by abitrolly** [FedoraQt/MediaWriter#527]
Made F36 image and couldn't `dnf update` it. Run out of space by 500Mb. Does the live image write any information to the flash? Does it persist anything after reboot?

**Comment by grulja** [comment]
Hi, it doesn't and after reboot everything will be gone. What you are looking for is https://github.com/FedoraQt/MediaWriter/issues/219. We unfortunately don't have capacity to implement it at this moment.

**Comment by abitrolly** [comment]
@grulja thanks for the clarification. It does worth to mention it in the writer.

Given the original problem that the newly created F36 USB drive had about 1G+ missing updates. Is there a way to write Live image that already includes latest updates?
