### ISSUE TITLE
Allow to download an ISO without an USB flash drive plugged in

### ISSUE THREAD

**Issue by coz** [FedoraQt/MediaWriter#533]
Tried the 5.2 version of mediawriter but could not find a way to download the ISO image without inserting a flash drive. I use KVM
I had to downgrade to 4.2.2

**Comment by grulja** [comment]
Right, with the new version it is not possible to download an ISO without an USB flash drive inserted so it is automatically written into it. We might look into enabling this so it works for people with your use-case.
