### ISSUE TITLE
Mediawriter.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by devrittick** [FedoraQt/MediaWriter#536]
The procedure entry point CreateEventW could not be located in the dynamic link library api-ms-core-synch-l1-2-0.dll

**Comment by grulja** [comment]
Can you be more specific what is the issue? What Windows versions?

**Comment by devrittick** [comment]
![Mediawriter exe - Entry Point Not Found](https://user-images.githubusercontent.com/85804624/178215101-3980dd6a-9ba3-4266-a360-eed2974b1c71.png)
What Windows versions?
---- Windows 7

https://user-images.githubusercontent.com/85804624/178215510-22926378-ed9c-4552-9e13-9565df9a1254.mp4

Check the video
