### ISSUE TITLE
Does not launch under Linux Mint

### ISSUE THREAD

**Issue by IlgazC** [FedoraQt/MediaWriter#538]
I see this message when I attempt to run via flatpak run

W@344ms: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
W@344ms: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
W@345ms: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
F@345ms: Could not initialize GLX

nvidia 340 driver here. (MCP79/nvidia 9400)

**Comment by grulja** [comment]
This look like some driver issue / incompatibility with Qt 6. I would suggest trying another QML / Qt 6 based application, but I cannot think of any at this moment.

**Comment by grulja** [comment]
Try to run "flatpak update" as suggested here https://forum.manjaro.org/t/stable-update-2022-01-23-opensearch-kernels-kde-software-cinnamon-pipewire-mesa-gnome-libreoffice/99878/6.

**Comment by tenzap** [comment]
There is a QTBUG reported for this https://bugreports.qt.io/browse/QTBUG-140459
