### ISSUE TITLE
"helper" linux command line arguments?

### ISSUE THREAD

**Issue by lambertlu** [FedoraQt/MediaWriter#540]
Hi There,

I am trying to use the "helper" tool to write an ISO to USB in the command line without the GUI.

I could not understand the source code https://github.com/FedoraQt/MediaWriter/blob/main/src/helper/linux/writejob.cpp

`# /usr/libexec/mediawriter/helper write /ISO/Fedora_36.iso /dev/sdb`

The error message:
`Object does not exist at path “/dev/sdb”`

Also tried: /dev/disk/by-id/
```
# ls -alt /dev/disk/by-id/
lrwxrwxrwx 1 root root  10 Jul 28 10:09 usb-SanDisk_Cruzer_Pop_4C532000070916110163-0:0-part1 -> ../../sdb1
lrwxrwxrwx 1 root root   9 Jul 28 10:09 usb-SanDisk_Cruzer_Pop_4C532000070916110163-0:0 -> ../../sdb

# /usr/libexec/mediawriter/helper write /ISO/Fedora_36.iso /dev/disk/by-id/usb-SanDisk_Cruzer_Pop_4C532000070916110163-0:0
dbus[741]: arguments to dbus_message_new_method_call() were incorrect, assertion "_dbus_check_is_valid_path (path)" failed in file ../../dbus/dbus-message.c line 1377.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

Much appreciate if anyone know what is the arguments.

Best,

**Comment by grulja** [comment]
It should look like this:
`/usr/libexec/mediawriter/helper write "/home/jgrulich/Fedora-Workstation-Live-x86_64-36-1.5.iso"  "/org/freedesktop/UDisks2/block_devices/sda"`

At least this is what I see is executed.
