### ISSUE TITLE
I assumed this was fixed?

### ISSUE THREAD

**Issue by coz** [FedoraQt/MediaWriter#546]
I use qemu/kvm. Unless I am installing on hardware, I rarely put an iso onto flash.
I got an email closing this issue, and i assumed this was fixed.
I am not being grumpy, because I can always downgrade.

**Comment by grulja** [comment]
I guess you mean having option to only download an ISO without having an USB drive plugged in? Yes, this will be possible with the next release.

**Comment by coz** [comment]
Jim,

Thank you for the response.
I had no doubts you guys would respond.
Thank you!
coz
