### ISSUE TITLE
Fedora Versions need to be updated on the tool for windows

### ISSUE THREAD

**Issue by falcon-Z** [FedoraQt/MediaWriter#547]
On windows the version numbers for Fedora has not been  updated properly and as such it displays `Fedora 35`  as the default Latest version and shows the latest current version `36` as still in Beta. Kindly update the tool as to reflect current versions of Fedora.

![image](https://user-images.githubusercontent.com/28111283/182549350-f7ccaa24-ed57-48e2-82a6-e671445f4a03.png)

**Comment by grulja** [comment]
It should be updated automatically when you start FMW. We can for sure update the list for the next release, but the point is that you should be able to run even older versions of FMW and still be able to download future Fedora releases.

Maybe https://getfedora.org/releases.json was unaccessible at the moment you tried?

**Comment by falcon-Z** [comment]
> Maybe https://getfedora.org/releases.json was unaccessible at the moment you tried?

I am not sure about that but, i have been seeing this issue since the release of **Fedora 36** and today before posting the issue i went ahead downloaded and reinstalled `FMW`

Also, the same issue does not occur in my `Fedora` Machine. 

Because of this issue on windows i Directly download `ISO` files and choose custom image so, i cant verify if  its just the labels that are wrong

**Comment by grulja** [comment]
Where did you get FMW from? Do you use official builds from getfedora.org or from GitHub?

**Comment by grulja** [comment]
I tested both, the official build from getfedora.org and latest testing build from GitHub and both correctly allow me to download F36 (stable, not beta).

**Comment by falcon-Z** [comment]
> Where did you get FMW from? Do you use official builds from getfedora.org or from GitHub?

Official builds from getfedora.org

**Comment by falcon-Z** [comment]
> I tested both, the official build from getfedora.org and latest testing build from GitHub and both correctly allow me to download F36 (stable, not beta).

Yes, I just checked again and now it seems to be working proeperly as expected

![image](https://user-images.githubusercontent.com/28111283/182567213-8b0e9dd7-aae7-48e6-8784-71da2e3e79f3.png)
