### ISSUE TITLE
Impossible to write usb key (32Go) with fedora media writer

### ISSUE THREAD

**Issue by jeromeperez** [FedoraQt/MediaWriter#555]
I can't create fedora live 36 on usb key .
Error when writing access denied
![fedora 2022-09-01 165157](https://user-images.githubusercontent.com/22741807/187945207-af4997e1-b93f-4ef8-b575-70d24d3c771f.png)

**Comment by grulja** [comment]
Did you get a dialog asking for permission to write the image?

**Comment by jeromeperez** [comment]
i finally installed fedora with unetbootin
