### ISSUE TITLE
Restore option isn't present on drive reconnect on Windows 11

### ISSUE THREAD

**Issue by kparal** [FedoraQt/MediaWriter#556]
When I burn an image on Windows 11, I see the Restore menu item present in FMW immediately afterwards. But when I disconnect the drive (the Restore option disappears) and reconnect it again, the Restore option doesn't re-appear. When I try it on Fedora 36, it works as expected.

FMW 5.0.3, Windows 11
tested with Fedora-Workstation-Live-x86_64-37_Beta-1.5.iso

**Comment by grulja** [comment]
I can reproduce on Windows 10. I will investigate.

**Comment by grulja** [comment]
This is probably happening because we mark the drive restorable based on whether it has a letter assigned or not. When I now test it in Windows 10, I see that when I insert a drive with Fedora, it will show two new USB drives in Windows, where both want me to format it and both obviously have letters assigned and therefore the drive doesn't show up as "restoreable" in FMW.

The code for that is here: https://github.com/grulja/MediaWriter/blob/main/src/app/windrivemanager.cpp#L212, see `!hasLetter` argument. That one makes it restoreable.

Hey @MartinBriza, as the original author of this code, do you have any idea how to further check whether a plugged drive can be restored?

**Comment by mnowak02** [comment]
what should I do to restore usb disc?

**Comment by grulja** [comment]
> what should I do to restore usb disc?

Doesn't Windows offer you to restore the drive when it's plugged in? It does in my case. Alternative workaround would be to open Fedora Media Driver, try to write a new image, but cancel the process immediately once it starts writing and once it returns to the main page, there should be option to restore the drive.

**Comment by mnowak02** [comment]
Windows do not see it, when it is plugged in.
It is only visible in Device Manager in Windows in section Disk drives but in my computer do not see it

**Comment by mnowak02** [comment]
In windows in Disk Managment I see only :
Disk2
Removable (E):
No Media
and I am not able to do nothing with that

**Comment by grulja** [comment]
> In windows in Disk Managment I see only : Disk2 Removable (E): No Media and I am not able to do nothing with that

You should be able to format it from there.

**Comment by mnowak02** [comment]
ok I give up :(
thanks for help :)

**Comment by grulja** [comment]
> ok I give up :( thanks for help :)

Don't. I'm sorry, I was wrong and it's not possible to format the drive from the disk management tool for some reason. What works and I already suggested is to again run Fedora Media Writer and write the same image (or another one, doesn't matter) again and right after it starts writing (not downloading), you just cancel the process (there is "cancel" button, do not close the app) and once it brings you back to the main page, there will be option to restore your drive. I just tested it and it works.

**Comment by mnowak02** [comment]
Ok but at the beggining in FMW when I put usb disc into usb slot, doesnt see usb disc, so I have no possibility to start and stop FMW. It looks like that FMW broke/damage usb disc, I think FMW change sth about format data etc and I try but not able to format or sth like that that usb disc.

**Comment by grulja** [comment]
FMW will see the drive, it just won't give you option to restore it initially when you start it. You really have to repeat the steps and write the image again so FMW marks the drive as restoreable.

**Comment by mnowak02** [comment]
I am not able to restore because FMW broke earlier usb disc and when I start FMW, FMW doesnt see disc
![2022-10-11_10h06_07](https://user-images.githubusercontent.com/35466026/195033878-4dc62073-de7b-4044-a14f-56a907be4fd7.png)

**Comment by grulja** [comment]
FMW definitely didn't break your USB drive, but it's weird you don't see it at all. Can you try to install Rufus and check whether it can be restored there?

**Comment by mnowak02** [comment]
![2022-10-11_15h41_48](https://user-images.githubusercontent.com/35466026/195107261-df6d5979-ef6f-4063-9a2e-b82fc1380ca9.png)
logs:
Found USB 2.0 device 'NAND USB2DISK USB Device' (FFFF:1201)
Device eliminated because it appears to contain no media
0 devices found
so thats mean Rufus see USBDISK only in logs but I can not choose this disc

**Comment by kparal** [comment]
@mnowak02 I'd try booting Fedora Workstation Live image, running GNOME Disks, and testing whether you can see the USB drive from there and reformat it. If you can't, then it looks like your USB drive simply died.

**Comment by grulja** [comment]
@mnowak02 to me it looks like your USB drive died, which might explain FMW got stuck as you reported in your original report.

**Comment by grulja** [comment]
@kparal can you try with latest Windows build from my fork? It has the change I proposed here https://github.com/FedoraQt/MediaWriter/pull/566.

Link: https://github.com/grulja/MediaWriter/releases/tag/latest-windows

**Comment by kparal** [comment]
> @kparal can you try with latest Windows build from my fork? It has the change I proposed here #566.

I don't have Win 11 ready right now, I only have Win 10. On my Win 10, I can't reproduce the original problem with an F37 Workstation Live image. Restore option is always present. However, I can reproduce the problem when I burn F37 Everything netinst image. After reconnecting the drive, two USB partitions are shown and assigned letters (and I'm asked to format them), and FMW doesn't offer any option to restore the drive. However, your build doesn't make any difference, still no Restore option there.

**Comment by grulja** [comment]
> > @kparal can you try with latest Windows build from my fork? It has the change I proposed here #566.
> 
> I don't have Win 11 ready right now, I only have Win 10. On my Win 10, I can't reproduce the original problem with an F37 Workstation Live image. Restore option is always present. However, I can reproduce the problem when I burn F37 Everything netinst image. After reconnecting the drive, two USB partitions are shown and assigned letters (and I'm asked to format them), and FMW doesn't offer any option to restore the drive. However, your build doesn't make any difference, still no Restore option there.

You are right, I could reproduce. Can you try one more time with https://github.com/grulja/MediaWriter/releases/tag/latest-windows? I did it the other way around now, instead of searching for the first mountable drive, I check for the first non-mountable drive and in that case I mark it as restoreable.

**Comment by kparal** [comment]
That works. I can now restore a flash drive containing Netinst (and Live still works). I only tested on Win 10. I might be able to test on Win 11 again in the future, but I'm not sure when.
