### ISSUE TITLE
During create image MediaWriter stuck and system do not see pendrive

### ISSUE THREAD

**Issue by mnowak02** [FedoraQt/MediaWriter#564]
During create image ISO from RH MediaWriter stuck. I turn off Media writer but  system do not see pendrive. I can not restore a disc from Media Writer, it doesnt see it. How to format pendrive because nothing tool see it

**Comment by grulja** [comment]
Hi, what operating system do you use? Where did you get FMW from? Do I understand correctly that FMW got stuck while writing an image and you closed it and neither FMW or any other tool (can you name what tool) don't see it?

**Comment by grulja** [comment]
This might be issue that is already reported here: https://github.com/FedoraQt/MediaWriter/issues/556. I will investigate.

**Comment by grulja** [comment]
Duplicate of https://github.com/FedoraQt/MediaWriter/issues/556.
