### ISSUE TITLE
Can't write a Live image twice: Destination drive is not writable

### ISSUE THREAD

**Issue by kparal** [FedoraQt/MediaWriter#574]
When I successfully write a Live image (F37 Workstation Live, in this case), and then immediately want to write it again to the same flash drive, the process fails with:
```
Destination drive is not writable (Incorrect function.)
Couldn't open the drive for writing (Access is denied.)
Couldn't lock the drive (The handle is invalid.)
```
![tRku583](https://user-images.githubusercontent.com/755451/201681640-5f1e7830-41c0-4d41-bdb2-1aa3e3424644.png)

Restarting FMW doesn't fix the problem. I have to unplug the flash drive and plug it again, in order to be able to write to it again.

Interestingly, this problem doesn't happen when I try to write a Netinst image (F37 Everything netinst) twice. Only a Live image.

Are there any logs somewhere which I could attach to help you debug this problem?

Reproducer:
1. Insert a flash drive
2. Write a Live image to it, click Finish, don't close FMW
3. Pick the same ISO again and try to write it again
4. After some time (no progress bar), see the error as above. Retrying again doesn't help, only re-plugging the drive.

System:
FMW 5.0.4
Windows 10

**Comment by grulja** [comment]
Most likely same issue as in https://github.com/FedoraQt/MediaWriter/issues/575.

**Comment by PetrCihlar** [comment]
I had the same issue with RH Remote exam ISO. Some exam candidates experienced it sometime. I did not find any dependency, managed to replicate once and resolved by rinstaling the usb disk or USB drivers. I do not remember. However the newly released RH Remote exam ISO generates the same error every time, while the previous one can be written under the same conditions. Rufus warns about mutliple partitions and FMW on Mac OS both work

Systems:
FMW 5.04 and 5.06 on Windows 10
FMW 5.06 on Windows 11
The ISO contains hidden and encrypted partitions.

Replication steps:
Download the ISO from https://red.ht/rhrex (version 20231116 at the time I write this)
Insert USB stick
run FMW
select iso
write
at the end you observe the error

![Screenshot 2024-02-02 at 10 39 30](https://github.com/FedoraQt/MediaWriter/assets/143876297/bb1bbe75-a7ab-4fec-a32d-f3078eef30d2)
