### ISSUE TITLE
No option to download aarch64 images for Spins

### ISSUE THREAD

**Issue by aleasto** [FedoraQt/MediaWriter#577]
When choosing to download the images within Fedora Media Writer itself, all Spins only offer x86_64 downloads

**Comment by grulja** [comment]
There doesn't seem to be aarch64 images available. I can only see aarch64 for Workstation, Server and IoT.

See https://fedoraproject.org/releases.json.

**Comment by aleasto** [comment]
That's weird cause it's definitely available on the website https://fedoraproject.org/spins/kde/download/
