### ISSUE TITLE
Enable Fedora Budgie and Sway spins to be selected at download dropdown for F38

### ISSUE THREAD

**Issue by geraldosimiao** [FedoraQt/MediaWriter#597]
Starting at F38 there's now two new spins, [fedora budgie](https://fedoraproject.org/wiki/Changes/FedoraBudgie) and [fedora sway](https://fedoraproject.org/wiki/Changes/Fedora_Sway_Spin), but when using mediawriter to automaticaly download a chosen spin, both are not present at the dropdown menu.

**Comment by geraldosimiao** [comment]
tested mediawriter-5.0.4-1.fc37.x86_64

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/MediaWriter/commit/4e64bcb5c55247dfd154d72b6a7bbd3f8181b49c.
