### ISSUE TITLE
USB stick not recognized & unusable on windows 10 x64, USB storage space is shrinked after !! & failed to boot with "test media and start the distribution" option

### ISSUE THREAD

**Issue by Grimst** [FedoraQt/MediaWriter#598]
Hey, guys 

Here I tell you today's misadventure with your tool MediaWriter. 
![about_fedmediawriter_5 0 4_win64](https://user-images.githubusercontent.com/16018842/226310818-d492adf7-403d-43e6-9b8b-64e9c97734a6.png)
Windows user for a long time, I was tempted to try the Fedora distribution 37, I came across your tool and I saw that you had made a .exe, that's good. so, I launch MediaWriter, I choose the Fedora Worstation 37 spin KDE to download (my favorite, I knew the KDE first ones I'm a fan) and I choose my 4G USB stick that goes well and runs 'Nikel' on my Windows 10 22h2 x64.

The download runs great and the tool seems to finish his job correctly, no extra messages. I unplug my usb key and out of curiosity I replug it
And 
Boom
![err_usb_stick2](https://user-images.githubusercontent.com/16018842/226310866-200b6588-2a35-4ceb-a968-7e66bd5a1d10.png)

On the printscreen below, I have on hardrive (letter C:) and the two others (D: and E: )comes from the USB stick but unavailable.
the shame is that I can not reformat my stick without extra software like IM-Magick, gparted etc because the default windows tool doesn't allow me to reformat my stick
![err_usb_stick](https://user-images.githubusercontent.com/16018842/226310833-fe4d474a-028b-4658-87f2-cfc1bd09116c.png)

Well, I do not stop there, I restart my laptop (an ACER Aspire 1 by the way) with my USB key plugged and I try anyway "on a misunderstanding it can work as Michel Blanc would say""

I select Test the media and start Fedora Workstation 37, result : 
"Checking 4.8%. the media check is complete, the result is : FAIL. 
it is not recommended to use this media.
checkisomd5@dev-sda.service  Media check on /dev/sda
dracut-initqueue [795] job for checkisomd5@dev-sda.service failed because the control process exited with error code
...
Fata CD check failed refusing to continue"

**=> Edit : When I try to start directly without testing the media that is working fine.**

Edit again : The difference with Rufus is obvious, I will use Rufus https://github.com/pbatard/rufus

**Comment by grulja** [comment]
Hi, you will not be able to use your USB drive unless it's again restored using Fedora Media Writer, you won't be able to even view what's on the drive as Windows will not recognize it.

**Comment by Grimst** [comment]
This is not normal behavior if I may say so (cf. the Rufus tool who doesn't do that for example). At least you could warn about this before the user uses your tool, does what I'm saying make sense to you ?

**Comment by grulja** [comment]
> This is not normal behavior if I may say so (cf. the Rufus tool who doesn't do that for example). At least you could warn about this before the user uses your tool, does what I'm saying make sense to you ?

There are some information we show to the user while the image is being written onto your drive:
- `Your drive will be resized to a smaller capacity. You may resize it back to normal by using Fedora Media Writer. This will remove installation media from your drive.`
-  `By writing, you will lose all of the data on xxx`

I understand it might be confusing that your drive is not recognized by Windows anymore, but it's a state that will get reversed when you use FMW to restore it.
