### ISSUE TITLE
Allow burning to optical media (CD, DVD and BD)

### ISSUE THREAD

**Issue by 07416** [FedoraQt/MediaWriter#627]
The application dropdown menu only displays 'USB drive' as writing destination. Please support optical media as well — for cold storage, blu-ray is the most reliable option after magnetic tape to my knowledge.

![image](https://github.com/FedoraQt/MediaWriter/assets/14923168/c21f7002-c922-4557-9759-2b43df5bf940)

**Comment by grulja** [comment]
Hi, I'm sorry, but this is not a planned feature for Fedora Media Writer.
