### ISSUE TITLE
macOS retina display icons

### ISSUE THREAD

**Issue by marekzehra** [FedoraQt/MediaWriter#63]
Icons in macOS version have bad resolution on retina screen. 
<img width="801" alt="snimek obrazovky 2017-01-30 v 16 06 08" src="https://cloud.githubusercontent.com/assets/1109636/22428351/01b8b9d8-e707-11e6-8dd0-9514397211f4.png">

**Comment by MartinBriza** [comment]
Thanks for letting me know, I'll se what I can do about it.

2017-01-30 16:14 GMT+01:00 Marek Žehra <notifications@github.com>:

**Comment by grulja** [comment]
I haven't seen such issue with recent MediaWriter 4.2.0. Feel free to reopen if this issue is still reproducible for you.
