### ISSUE TITLE
Flatpak complains about depreciated platform

### ISSUE THREAD

**Issue by IlgazC** [FedoraQt/MediaWriter#634]
I noticed this message yesterday:

Info: runtime org.kde.Platform branch 6.4 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Info: applications using this runtime:
   org.fedoraproject.MediaWriter

There is also a typo in the message and I couldn't find where to send fix/report/

I know it isn't probably a big deal but it could be alerting to non technical users and it also bugs.

Have fun.

**Comment by grulja** [comment]
I fixed it for builds we do here and I will fix it in Flathub once I make a new release.
