### ISSUE TITLE
Progress bar no longer updates on Fedora 39

### ISSUE THREAD

**Issue by kparal** [FedoraQt/MediaWriter#640]
On Fedora 39 the progress bar looks always to be at 0%:

![writing](https://github.com/FedoraQt/MediaWriter/assets/755451/f97ace5f-1c10-4d8d-8787-b494282bd2b8)

![checking](https://github.com/FedoraQt/MediaWriter/assets/755451/7af4f868-6539-409d-a1a3-b3bd82f63cc6)

It's only jumps to 100% after the whole process is finished.

`mediawriter-5.0.6-3.fc39.x86_64`

On Fedora 38, the progress bar is displayed as expected, it updates live. I suppose the F39 behavior might be related to this:
https://pagure.io/fedora-workstation/issue/351

Only tested in a virtual machine, I don't have a bare metal around at the moment.

**Comment by grulja** [comment]
I cannot reproduce. Testing this with FMW 5.0.7 in F39 Toolbox container on Fedora 39 KDE (also tested in Weston). 

And Adwaita-qt removel (not using it by default) shouldn't have any impact on Fedora Media Writer.

**Comment by kparal** [comment]
Yes, it looks fine in a Fedora 39 KDE VM. But it doesn't display in GNOME. I also tested 5.0.7, no change.

I see the following errors in the terminal:
```
W@11993ms: qrc:/qml/DownloadPage.qml:143: TypeError: Cannot read property 'name' of null (qrc:/qml/DownloadPage.qml:143)
W@11993ms: qrc:/qml/DownloadPage.qml:261: TypeError: Cannot read property 'progress' of null (qrc:/qml/DownloadPage.qml:261)
W@12001ms: qrc:/qml/DownloadPage.qml:143: TypeError: Cannot read property 'name' of null (qrc:/qml/DownloadPage.qml:143)
W@12001ms: qrc:/qml/DownloadPage.qml:261: TypeError: Cannot read property 'progress' of null (qrc:/qml/DownloadPage.qml:261)
W@12044ms: qrc:/qml/DownloadPage.qml:143: TypeError: Cannot read property 'name' of null (qrc:/qml/DownloadPage.qml:143)
W@12044ms: qrc:/qml/DownloadPage.qml:261: TypeError: Cannot read property 'progress' of null (qrc:/qml/DownloadPage.qml:261)
```

**Comment by grulja** [comment]
Does installing `qgnomeplatform-qt6` and running `mediawriter -platformtheme qgnomeplatform` make any difference?

**Comment by kparal** [comment]
No improvement. In this case, the first line in output is:
```
W@116ms: Could not find color scheme  ""
```
not sure whether it's important or not. Either way, progress bars are still broken.

However, I just made a revelation! **The progress bars are only broken the first time you write an image after a clean boot!** If I keep FMW running and write the image again, suddenly, progress bars are updated properly. And even if I close FMW and start it again, the progress bars still work! And those `Cannot read property` errors are no longer displayed, so they are probably somehow relevant to this issue.
(This last paragraph was tested in a default FMW experience, without `qgnomeplatform-qt6` and `-platformtheme qgnomeplatform`).

**Comment by kparal** [comment]
If I log out from my user session and log back in, the progress bars are again broken on the first use of FMW.

**Comment by grulja** [comment]
I'm starting to suspect the issue here is also related to `udisk2` as in https://github.com/FedoraQt/MediaWriter/issues/644. Any chance you can try to downgrade to  `udisks2-2.9.4-7.fc38` or make a scratch build of that older version for Fedora 39? I run Fedora Kinoite and it's harder to boot into GNOME with older udisks2.

**Comment by geraldosimiao** [comment]
tested here on a workstation iso from 2023/09/10 and the bar is working fine
![Screenshot_20230913_140451](https://github.com/FedoraQt/MediaWriter/assets/72357821/85a20703-c558-4a3d-95c4-9d2b3e9ab995)

**Comment by geraldosimiao** [comment]
I'll test now on today's Fedora-Workstation-Live-x86_64-39_Beta-1.1.iso

**Comment by grulja** [comment]
> I'll test now on today's Fedora-Workstation-Live-x86_64-39_Beta-1.1.iso Ok, on the beta 1.1 image I can reproduce the bug. So whats different from the 20230910 iso and the beta-1.1?

What's udisks2 version there? There has been an update submitted to stable few days back

**Comment by grulja** [comment]
I can reproduce with both `udisks2-2.10.1-1.fc39.x86_64` and with `udisks2-2.10.0-2.fc39.x86_64` in GNOME.

**Comment by kparal** [comment]
Ok, a few more data points:
1. It's not a race condition, I can reproduce it reliably, in specific use cases
2. It's not related to VMs, I just reproduced it on bare metal (my colleague's laptop)
3. It only happens once in a **session**, further uses are OK, even if you restart FMW. You need to re-log to trigger it again.
4. You can avoid this bug if you a) restore the drive first (perhaps because it already displays a progress bar (an infinite one, which works), or b) if you cancel the authentication dialog on the first write attempt, and then ask

**Comment by kparal** [comment]
> tested here on a workstation iso from 2023/09/10 and the bar is working fine

I tested that image and I can reproduce it (right from the Live image).

**Comment by kparal** [comment]
The earliest image that I have locally is `Fedora-Workstation-Live-x86_64-39-20230823.n.0.iso` and that one is still broken.

As commented [here](https://github.com/FedoraQt/MediaWriter/issues/644#issuecomment-1719285901), I wasn't successful in downgrading `udisks2` in Fedora 39. But to my layman eye this looks like an UI problem to me, especially given that we get those `TypeError` messages exactly when it happens. Perhaps the first progress bar displayed is not initialized properly or something?

**Comment by kparal** [comment]
Oh, this is extremely interesting. This might be really caused by udisks2 or something related. **Because after a fresh login when I first modify the drive in gnome-disks (e.g. just format it with a new MBR table) before starting FMW, then the progress bar doesn't happen** (and those `TypeError` messages don't appear)! But when I _don't touch_ the drive first, just start FMW and try to write it, then the progress bar bug is there.

So clearly, gnome-disks triggers something in the stack (udisks2 or similar) which than affects FMW later!

**Comment by kparal** [comment]
With the build tested in #650 this now works correctly, thanks.
