### ISSUE TITLE
MediaWriter defaults to geographical location language rather than Windows language

### ISSUE THREAD

**Issue by AdamAnon** [FedoraQt/MediaWriter#654]
I'm physically located in Poland but my Windows is in US EN. MediaWriter starts in Polish, ignoring Windows default language setting, and there is no option to change it to English.

**Comment by grulja** [comment]
I don't think this is something we can change. It will use whatever Qt assumes is the default language. We don't do anything special when picking the language. 

Here is a similar case: https://stackoverflow.com/questions/18594380/qlocale-detects-system-language-incorrectly-on-windows-with-language-pack-instal

I think it depends on what you have in "Control Panel > Region and Language > Format" as mentioned on the link above.
