### ISSUE TITLE
Please add Debian build and/or AppImage

### ISSUE THREAD

**Issue by DragonSerW** [FedoraQt/MediaWriter#668]
Hello guys!
I need to create Fedora 39 Live USB while I am on my Debian 12.2.0 PC.

**Comment by grulja** [comment]
Hi, I'm unfortunately not familiar with Debian or AppImage packaging. You can download a Flatpak version from Flathub that will for sure work without any issue in Debian.

Link: https://flathub.org/apps/org.fedoraproject.MediaWriter

**Comment by eugenialoli** [comment]
Please reconsider an appimage. I use Debian-based distros too, and flatpaks are a no-go in Greece on a slow line. The updates on flatpaks are just too huge, too often (in the gigabytes, almost every week). An appimage of this app wouldn't be more than 50 MB normally.

**Comment by cweiske** [comment]
AppImages do not require any prerequisites on the machine, while flatpaks require a working flatpak application with a daemon in the background.

Related: #210
