### ISSUE TITLE
Can't open file chooser / selector. Error: Failed to open portal file dialog:  "No such interface “org.freedesktop.portal.FileChooser” on object at path /org/freedesktop/portal/desktop"

### ISSUE THREAD

**Issue by R8s6** [FedoraQt/MediaWriter#670]
- Version: 5.0.8.
- OS: Arch
- X11
- Xfce desktop

It used to work but perhaps since the OS updated, some dependency stopped working?

### Symptoms

When I go to "Select .iso file", then hitting the "Select" button has no effect. It used to bring out the file chooser.

![](https://i.imgur.com/mLk3eGK.png)

The error (if run in terminal) is: 

```
Failed to open portal file dialog:  "No such interface “org.freedesktop.portal.FileChooser” on object at path /org/freedesktop/portal/desktop"
```

Thanks!

**Comment by grulja** [comment]
Looks like https://bugzilla.redhat.com/show_bug.cgi?id=2244205.

Apparently fixed with the new version of xdg-desktop-portal.
