### ISSUE TITLE
5.0.7 and 5.0.8 are broken on Windows

### ISSUE THREAD

**Issue by Croydon** [FedoraQt/MediaWriter#671]
I have used 5.0.6 for a while successfully.
I wanted to upgrade to the latest version, before my next use and updated to 5.0.8.

The installation runs through seemingly successful, but whenever I try to start the app, I get asked to grant admin rights, and after granting, nothing appears on screen. The process `mediawriter.exe` keeps running however. Does not matter how often I try to restart the app, restarting my computer also changed nothing.

I then downgraded to 5.0.7 with the exact same result.
I am now back to 5.0.6 and it works again.

I am on an up-to-date version of Windows 10 Pro.

**Comment by grulja** [comment]
I think you are hitting https://github.com/FedoraQt/MediaWriter/issues/66. I will make a new release with this fix.

**Comment by Croydon** [comment]
I can confirm that 5.0.9 works for me.
Thank you!
