### ISSUE TITLE
Phosh not available in Spins list

### ISSUE THREAD

**Issue by valentingregoire** [FedoraQt/MediaWriter#672]
When using the media writer version 5.0.8, when selecting the `Spins` option, the Phosh option is not in the list.

**Comment by grulja** [comment]
Is it an official spin? It doesn't seem to be listed here https://fedoraproject.org/releases.json and if it's not there, it cannot be downloaded with FMW.

**Comment by valentingregoire** [comment]
@grulja, yes, it's available here: https://fedoraproject.org/spins/

**Comment by grulja** [comment]
I know, but until it's added to the releases json file, we won't be able to download it.

**Comment by valentingregoire** [comment]
Then I suppose it needs to be added to that json file.

**Comment by Espionage724** [comment]
How would you install it?

I thought Phosh was just for phones and needed a specialized image, but it's advertised as being good for laptops with touchscreens. Only a raw.xz is provided for aarch64 on the Downloads page, and searching how to install it led to a bunch of threads of others wondering how to install it.

**Comment by grulja** [comment]
Closing this ticket as Phosh spin no longer exists: https://pagure.io/pungi-fedora/pull-request/1233
