### ISSUE TITLE
Dark mode not available

### ISSUE THREAD

**Issue by vedantalim** [FedoraQt/MediaWriter#675]
Hi, 
I know this is not a big concern at all for a functional app like this one, but the light theme does look a bit apart from the other DE theme integrations our Fedora has. I believe it's not really hard to implement too. With all other GNOME apps being dark, the light mode seems disconnected.
Hope this improves the app somewhat.

**Comment by grulja** [comment]
Hi, FMW already has a dark theme and it should be used automatically based on your system theme.  What Fedora version do you have?

**Comment by vedantalim** [comment]
Hi,
I am using latest Fedora 39 workstation, that uses GNOME 45.2. The dark mode isn't applied automatically and I could not find option of applying it manually since the app has not got any Settings. 
![Screenshot from 2023-12-13 04-17-18](https://github.com/FedoraQt/MediaWriter/assets/78305945/4998c9f8-7507-4a84-99f6-85887694b263)

**Comment by Espionage724** [comment]
I also notice this under the same environment today (Workstation, GNOME, F39). I did Settings -> Appearance -> Dark, started Fedora Media Writer, and only the title bar is dark like the screenshot. If it matters I'm using Xorg instead of Wayland session.

**Comment by grulja** [comment]
This will get fixed with https://codereview.qt-project.org/c/qt/qtbase/+/547252. I will backport the fix to Fedora.
