### ISSUE TITLE
Don't mark release as latest until Windows and Mac binaries are there

### ISSUE THREAD

**Issue by alexsch01** [FedoraQt/MediaWriter#694]
https://github.com/FedoraQt/MediaWriter/releases/latest
![image](https://github.com/FedoraQt/MediaWriter/assets/5721147/8d202cd7-707c-4ecf-8f84-e29f40f15af5)

**Comment by grulja** [comment]
The binaries gets added automatically once a new release is published, because a new release triggers a CI job doing that. Just this time it failed in CI so I removed it and have to investigate why it failed to build.

**Comment by grulja** [comment]
Fixed now. Binaries are there.
