### ISSUE TITLE
Not starting on Fedora 39

### ISSUE THREAD

**Issue by BryanRykowski** [FedoraQt/MediaWriter#709]
Running Fedora Media Writer 5.1.0-1.fc39.x86_64 causes nothing to happen. No window, no journalctl messages.

Running mediawriter from the command line produces this output:

```
W@65ms: QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop. For compatibility reasons, the .desktop suffix will be removed. Please specify a desktop file name without .desktop suffix
W@70ms: Architecture "ppc64" is not known!
W@135ms: QQmlApplicationEngine failed to load component
W@135ms: qrc:/qml/main.qml: module "fusion" is not installed
W@364ms: Architecture "ppc64" is not known!`
```

Also a whole bunch of warnings (maybe 60?) about URLs and hashes changing like this:

```
W@68ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/test/40_Beta/Kinoite/x86_64/images/Fedora-Kinoite-40_Beta.1.10.ociarchive" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/test/40_Beta/Kinoite/x86_64/iso/Fedora-Kinoite-ostree-x86_64-40_Beta-1.10.iso"
W@68ms: SHA256 hash of "https://download.fedoraproject.org/pub/fedora/linux/releases/test/40_Beta/Kinoite/x86_64/iso/Fedora-Kinoite-ostree-x86_64-40_Beta-1.10.iso" changed from "" to "2b502043fc56b13ce1e52c306f55cf124fb514b22f1fc67044a1853a7ed349df"
W@364ms: Url "https://download.fedoraproject.org/pub/alt/releases/39/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-39-1.5.iso" changed to "https://download.fedoraproject.org/pub/alt/releases/39/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-39-1.5.x86_64.vagrant-libvirt.box"
W@364ms: SHA256 hash of "https://download.fedoraproject.org/pub/alt/releases/39/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-39-1.5.x86_64.vagrant-libvirt.box" changed from "20b660ac93516c2b82a8f7105151df12c363fd18b358a7cd6a5baaa8d05b8796" to "58e0a3f08e7770197a6bdf4497f3f196e311ad70d36be8b583117f80308a327e"
```

EDIT:

I get pretty much the same output for the flatpak, and also 5.0.8, 5.0.9, and 5.1.1 built from source.

Flatpak version also has this output in addition to the previously mentioned ones:

```
Gtk-Message: 20:38:15.145: Failed to load module "xapp-gtk3-module"
W@61ms: Qt: Session management error: Could not open network socket
```

**Comment by grulja** [comment]
Those URL warnings are not a problem, most likely also the one about `xapp-gtk3-module`.

It fails because of:
```
W@135ms: QQmlApplicationEngine failed to load component
W@135ms: qrc:/qml/main.qml: module "fusion" is not installed
```
Can you check whether you have `qt6-qtdeclarative` installed? But I'm pretty sure it gets pulled in automatically through the dependencies.

**Comment by BryanRykowski** [comment]
> Can you check whether you have qt6-qtdeclarative installed?

dnf info says I have `qt6-qtdeclarative-6.6.2-3.fc39.x86_64` installed.

**Comment by BryanRykowski** [comment]
It turns out the following line in  /etc/environment was the problem:
```
QT_STYLE_OVERRIDE=fusion
```
Removing that or setting it to `Fusion` fixes the problem for me.

I'm hesitant to mark the issue as closed though, since other Qt apps don't seem to have a problem with this. I guess I'll leave it up to you.

**Comment by grulja** [comment]
This is a generic Qt issue, it's not like FMW is loading Qt styles on its own.
