### ISSUE TITLE
Fedora Budgie Spin missing from automatic downloads

### ISSUE THREAD

**Issue by lesinigo** [FedoraQt/MediaWriter#711]
With current Media Writer v5.1.1 on Linux, selecting _Download automatically_ and then _Spins_ does not give the option of Fedora Budgie Desktop, nor is it anywhere else.

Manually downloading `Fedora-Budgie-Live-x86_64-40-1.14.iso` and then using Media Writer to create an USB bootable media works correctly as expected.

**Comment by grulja** [comment]
This has been also fixed with https://github.com/FedoraQt/MediaWriter/pull/717.
