### ISSUE TITLE
Can't run flatpak version on Wayland

### ISSUE THREAD

**Issue by enrico223** [FedoraQt/MediaWriter#719]
Installed the application from Flathub but it doesn't run on Wayland. 
`flatpak run org.fedoraproject.MediaWriter` outputs this: 
```log
W@4ms: could not connect to display
W@4ms: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
I@4ms: Could not load the Qt platform plugin "xcb" in "" even though it was found.
F@4ms: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland, offscreen, xcb, wayland-egl, minimal, linuxfb, minimalegl, eglfs, vnc, vkkhrdisplay.

"/usr/plugins/platforms/libqxcb.so" unloaded library
```
I already tried to reinstall `xcb-util-cursor` and `qt5-base`

**Comment by grulja** [comment]
It looks it doesn't try to run on `Wayland` by default. Can you try to run with `flatpak run org.fedoraproject.MediaWriter -platform wayland`?

**Comment by enrico223** [comment]
It works if I specify that flag

**Comment by grulja** [comment]
Where do you run it? It looks Qt doesn't try to use Wayland by default on your platform for some reason. You can also workaround with an env variable `QT_QPA_PLATFORM=wayland`.

**Comment by enrico223** [comment]
I run it from the terminal.

**Comment by grulja** [comment]
I primarily would like to know what desktop environment do you use? But I think Qt should use Wayland by default everywhere.

**Comment by enrico223** [comment]
KDE Plasma 6.1 (Wayland session) on EndeavourOS

**Comment by grulja** [comment]
Interesting, it works here on Plasma 6.1 (Fedora 40) without any problem. Anyway, this is not a FMW issue so I'm closing this issue.
