### ISSUE TITLE
Stuck with an old version on Windows 10.

### ISSUE THREAD

**Issue by FomalhautGH** [FedoraQt/MediaWriter#722]
Can't install Fedora 40 with the Fedora Media Writer beacause it literally doesn't update itself. 

![immagine](https://github.com/user-attachments/assets/c2886912-95b4-4ba9-848f-1ad99a09f97f)
![immagine](https://github.com/user-attachments/assets/73a39600-709e-4be8-b0d2-c5b2de747f5a)

(I installed it from the official fedora website obv) https://fedoraproject.org/workstation/download

**Comment by grulja** [comment]
It should auto-update when you are connected to the internet. Also, you can download latest version from here (GitHub). The official Fedora website only has an old version. Looks we still didn't update it to link here instead.
