### ISSUE TITLE
FedoraMediaWriterインストール不可

### ISSUE THREAD

**Issue by Inoue-FJ** [FedoraQt/MediaWriter#724]
FedoraMediaWriter-win64-5.1.2.exeをWindows2008ベースのサーバにダウンロード後、インストール実施も”プロシージャエントリポイント 
CreateDXGIFactory2がダイナミックリンクライブラリdxgidllから見つかりませんでした”）というポップアップが出ることを確認しました。インストールができないようです。

**Comment by grulja** [comment]
Windows 2008 is not supported by Qt and therefore not supported by Fedora Media Writer.
