### ISSUE TITLE
"Atomic Desktops" labeled wrongly as "Fedora Escritorio i3" in es_ES.UTF-8 localization

### ISSUE THREAD

**Issue by Tau5** [FedoraQt/MediaWriter#726]
**Information**
Installation method: Flatpak
Version: 5.1.2
OS: OpenSUSE Tumbleweed 20240905
Kernel: Linux 6.10.7-1-default (amd64)
Desktop Environment: KDE Plasma 6.1.4 (Wayland)

**Description**
If the user language is set to Español (España) (`LANG=es_ES.UTF-8`) "Atomic Desktops" label is wrongly translated as "Fedora Escritorio i3"

**How to reproduce**
1. Set `LANG` to `es_ES.UTF-8`
2. Open Fedora Media Writer
3. Click "Siguiente"
4. Observe that the second option is labeled as "Fedora Escritorio i3" instead of "Atomic Desktops"

**Screenshots**

Application in English (LANG=0)
![Captura de pantalla_20240910_132132](https://github.com/user-attachments/assets/b1432468-4e4d-43d3-a524-3553a89673d0)

Application in Español (España)
![Captura de pantalla_20240910_132043](https://github.com/user-attachments/assets/3f36a639-8508-4977-a650-7e7af2392fca)

**Comment by grulja** [comment]
There seem to be a merge conflict for the translations right now at https://translate.fedoraproject.org/projects/fedora-media-writer, but can you please go to Spanish translation and fix the problem there once this is resolved?

**Comment by Tau5** [comment]
Yeah, I had gone after creating the issue report to the weblate instance and accepted a suggestion that fixed the issue. Thanks for the quick response though, hope the merge issues are fixed soon
