### ISSUE TITLE
Dutch translations are somewhat broken

### ISSUE THREAD

**Issue by jbruechert** [FedoraQt/MediaWriter#731]
Some strings have parameters that don't actually exist, while some other strings just seem wrong in the places they are used.

Example:
![image](https://github.com/user-attachments/assets/e76c28fd-e8b3-404d-b569-0dea6898f532)

**Comment by gastoner** [comment]
You can help to translate to Duch on this page https://translate.fedoraproject.org/projects/fedora-media-writer/mediawriter/nl/

**Comment by grulja** [comment]
It should be fixed now. I merged translations from Weblate to our repository and synchronized the Weblate git repo with ours as there were some merge conflicts. I will make a new FMW release soon. Thanks for your report and for fixing the translations.
