### ISSUE TITLE
Using media writer installs mobile version of KDE instead of desktop

### ISSUE THREAD

**Issue by kergelan** [FedoraQt/MediaWriter#734]
On version 5.1.2 of media writer with the following system information:
![image](https://github.com/user-attachments/assets/1a861e2a-c464-4354-95b9-6947a35d112e)

Selecting 'Download automatically', then Spins with 'Fedora KDE Plasma Desktop' selected and installing Fedora 41 Beta on to a USB drive caused it to write Fedora KDEM and not KDE (it still said it was writing KDE plasma desktop while writing)
![image](https://github.com/user-attachments/assets/c5356575-6cc6-41a4-8e9d-6d83612362ad)
Booting into the USB also shows KDE mobile.

**Comment by sjohal21** [comment]
Same problem here, happened on the Windows version of Media Writer downloading the 41 beta KDE spin.
