### ISSUE TITLE
Manually selecting the target device should be the default behavior !!!!!!

### ISSUE THREAD

**Issue by FaintShadow** [FedoraQt/MediaWriter#742]
hey there, Today I used Mediawriter to install a Windows installation into my Flash disk '***sniff***', Since It didn't work (for some reason) I basically just kept rebooting and trying again with another iso file '***crying***' while doing that my 1Tb HDD '***sobs***' was plugged in and It was fine at first until my flash disk wasn't plugged in and I pressed next '***TEARS***' I wiped my entire drive with a windows installation. Please make it so that you choose the target device manually and not automatically PLEASE

**Comment by grulja** [comment]
Hi, I'm really sorry to hear that, it's really unfortunate.

I have submitted https://github.com/FedoraQt/MediaWriter/pull/744. I hope this can prevent situations like the one that happened to you.

**Comment by FaintShadow** [comment]
thanks for the pull request but I think adding the ability for the user to click the select menu and select the drive himself will be also crucial into eliminating these types of problems :heart:
