### ISSUE TITLE
[macOS][ARM] “FedoraMediaWriter” is damaged and can’t be opened. You should eject the disk image.

### ISSUE THREAD

**Issue by osalbahr** [FedoraQt/MediaWriter#756]
Attempting to open [FedoraMediaWriter-osx-arm64-5.1.3.dmg](https://github.com/FedoraQt/MediaWriter/releases/download/5.1.3/FedoraMediaWriter-osx-arm64-5.1.3.dmg) results in the following error message:

“FedoraMediaWriter” is damaged and can’t be opened. You should eject the disk image.

This item is on the disk image “FedoraMediaWriter-osx-arm64-5.1.3.dmg”. Firefox downloaded this disk image today at 6:55 PM.
 
<img width="372" alt="Screenshot 2024-11-09 at 6 56 31 PM" src="https://github.com/user-attachments/assets/539d533b-625e-465f-8ca8-d7dbe71737cb">

- This seems to be related to https://github.com/FedoraQt/MediaWriter/issues/678

**Comment by grulja** [comment]
Yes, it's the same issue. This happens, because the FMW macOS build is not signed.

**Comment by consult-kk** [comment]
So it is effectively useless ?? I mean , is there a workaround /. fix .. rather than "This happens because.. blah blah " ???

**Comment by wonderITea** [comment]
same issue here

**Comment by osalbahr** [comment]
> So it is effectively useless ?? I mean , is there a workaround /. fix .. rather than "This happens because.. blah blah " ???

@consult-kk the workaround is in the linked issue: `xattr -r -d com.apple.quarantine FedoraMediaWriter.app`.

Here is how I adapted the workaround for my workflow:

```
brew install fedora-media-writer
xattr -r -d com.apple.quarantine /Applications/FedoraMediaWriter.app
```

And now you should be able to open the app as normal.

**Comment by osalbahr** [comment]
You can also
```
brew install --no-quarantine fedora-media-writer`
```
- See https://github.com/Homebrew/brew/issues/17979#issuecomment-2273062456

**Comment by osalbahr** [comment]
@anotherk1nd you can directly use `xattr`.

**Comment by osalbahr** [comment]
Closing since a workaround has been found.

It appears Apple might've disabled the old method of overriding a lack of signature through the UI (Settings app). If so, there's nothing Fedora can do unless someone pays for a developer account (or something like that).

**Comment by abbood** [comment]
this workaround works with the fedora media writer file donwnloaded from homebrew, but it doens't work with the one downloaded from the official fedora website

**Comment by rad8329** [comment]
> Same here. I ended up just copying the file system from the DMG to a temporary directory and then running:
> 
> ```
> xattr -r -d com.apple.quarantine FedoraMediaWriter.app
> ```
> 
> Then it worked for me.

Thanks, it worked for me

**Comment by lukasz-piotr-jan-wieczorek** [comment]
Download the second one for old architecture and run:

```sh
softwareupdate --install-rosetta
```

Allow the running under protection.
Mount DMG and ready.

**Comment by teatonedev** [comment]
`sudo installer -package /Volumes/FedoraMediaWriter/FedoraMediaWriter.app -target /
`

`sudo cp -R /Volumes/FedoraMediaWriter/FedoraMediaWriter.app /Applications/\n`

`hdiutil detach /Volumes/FedoraMediaWriter`

`sudo chown -R $(whoami) /Applications/FedoraMediaWriter.app`

`xattr -r -d com.apple.quarantine /Applications/FedoraMediaWriter.app\n`

After these, you are good to go. I made this on M4 macbook macos 15.7.x
