### ISSUE TITLE
5.2.2 does not launch on Windows 11

### ISSUE THREAD

**Issue by TingPing** [FedoraQt/MediaWriter#778]
The `mediawriter.exe` process is running but a UI never appears.

**Comment by grulja** [comment]
Did you maybe install the new version over the old one?  If so, can you try uninstalling and installing again?

**Comment by gastoner** [comment]
It works for me on W11 (FMW downloaded from github - new instalation)

**Comment by TingPing** [comment]
Running the uninstaller on this working version *does* remove all files. So something caused the upgrade to be in a bad state.
