### ISSUE TITLE
Missing MSVCP40.dll

### ISSUE THREAD

**Issue by nboelter** [FedoraQt/MediaWriter#782]
When starting Fedora Media Writer on Windows 11 Education N the start was aborted because MSVCP40.dll was missing.

I had to manually install a Microsoft Visual C++ Redistributable from https://learn.microsoft.com/de-de/cpp/windows/latest-supported-vc-redist?view=msvc-170 before it would start.

**Comment by grulja** [comment]
This is expected. It's mentioned in the README as well.
