### ISSUE TITLE
Add support for Dark mode.

### ISSUE THREAD

**Issue by ToothedTomb** [FedoraQt/MediaWriter#785]
When using dark mode on my Gnome System the application is in light mode.
I am using version 5.2.1.
I am using the latest version of Fedora. 
Thanks. :)

Jonathan Steadman

**Comment by grulja** [comment]
Dark mode is implemented in Qt itself. We no longer do any detection on our side as we don't have a custom theme as we used to have in the past. 

Is that a regular RPM package? What Fedora version?

**Comment by 4jNsY6fCVqZv** [comment]
![Image](https://github.com/user-attachments/assets/499b780b-8a46-4f99-8cc5-21612306a90c)

![Image](https://github.com/user-attachments/assets/133dffe7-4788-4358-86cc-86f175c14803)

Looks to me like there is still no real dark mode.

I'm using Fedora Workstation 41, with the default GNOME desktop.

**Comment by grulja** [comment]
I believe this issue will be fixed with https://codereview.qt-project.org/c/qt/qtbase/+/610137.
