### ISSUE TITLE
Missing automatic HiDPI displays on Linux

### ISSUE THREAD

**Issue by shoothub** [FedoraQt/MediaWriter#86]
Hello, I have a new 27" HiDPI display with resolution 3840x2160 and using scaling factor 2: gsettings set org.gnome.desktop.interface scaling-factor 2 (on Fedora 26 alpha, gnome 3.24.2, mediawriter-4.0.95-2.fc26.x86_64). All gnome/gtk3 and Qt5 application run correctly in this setup, but not mediawriter. It is not scalled at all. If I export QT_SCALE_FACTOR=2 and run mediawriter from console, it scales well. So probably something is missing to detect HiDPI scalling factor, please check and repair. 

Reference:
https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/
http://doc.qt.io/qt-5/highdpi.html

Thanks a lot.
BTW great application for Fedora newcomers.

**Comment by MartinBriza** [comment]
There's a problem with how Qt detects high DPI displays on Linux, that's why I turned the option off. It's actually pretty weird Qt apps scale for you on that display, I don't think Qt works with the GNOME scaling settings in any way.
However, I'm looking for a fix for this in the bigger picture - that is for all the Qt apps, in my QGnomePlatform project. I'll keep you posted when I've found a good way to fix this.

**Comment by sh0thub** [comment]
You are right, probably Qt application doesnt scaling automatically by gnome settings. Actually I only use one Qt application: VirtualBox, so propably it detects gnome settings somehow. Thanks for your feedback...

**Comment by M5oul** [comment]
I use qbittorent, and other Qt apps on Fedora 26 alpha which are well scaled.
I have a small window with Fedora Media Writter.

**Comment by MartinBriza** [comment]
qbittorrent is a widget application which is a bit different case than
mediawriter that is written using qml.
I actually have some scaling support in the app but it's not working as
intended on a lot of setups, so I had to turn it off... :/

2017-05-26 11:28 GMT+02:00 M5oul <notifications@github.com>:

**Comment by sh0thub** [comment]
Hello, I found, that High-DPI support is included in Qt Quick Controls 2, but not in version 1, please check:

https://doc.qt.io/qt-5/qtquickcontrols2-highdpi.html

**Comment by MartinBriza** [comment]
Well I have actually built in some level of high DPI support myself, however people complained it was too big/small, especially on Linux where the user is unable to set how scaling should work on their system.
I'll probably re-enable the code for Linux and Mac systems.

**Comment by grulja** [comment]
FMW has been ported to QQC2, hopefully this issue is fixed now.
