### ISSUE TITLE
Cursor never changes

### ISSUE THREAD

**Issue by rugk** [FedoraQt/MediaWriter#91]
Using Fedora 26 beta (v4.1.0-1.fc26) the cursor never changes from the default 'pointer' one. Not when hovering over the link to GitHub (where it should be the "hand") nor in the search input field. That's a bit irritating.

Wayland

**Comment by MartinBriza** [comment]
Yeah, this happens to me to time to time. I think it's a problem in Qt, the cursor is there sometimes and sometimes it's not... I'll check when and how this happens.

**Comment by grulja** [comment]
I cannot reproduce. We now ship FMW with Qt 5.15 so it's most likely fixed there already.
