### ISSUE TITLE
Do not downloading on Windows

### ISSUE THREAD

**Issue by veyselerden** [FedoraQt/MediaWriter#92]
I use 4.1.0-1.fc26 version Fedora Media Writer. When I try to download Workstation 25, it gives a download error.
![ekran alintisi](https://user-images.githubusercontent.com/12845347/27733308-159f6c36-5d9e-11e7-91c7-67ef2d9acb02.PNG)

It says on the top left (with red stop icon) Downloaded image broken. And says "Failed download" It doesn't download anything. Just a .part file with 0kb and fails. I couldn't find any log files sorry.

**Comment by Northest** [comment]
By the way other verions are downloadable. So that means its a server problem?

**Comment by MartinBriza** [comment]
Sorry for replying way too late. Yes, this is most likely a server problem. However, FMW should let you know about that in a legible way so this is a bug anyway.
