### ISSUE TITLE
small text on macOS

### ISSUE THREAD

**Issue by cmurf** [FedoraQt/MediaWriter#93]
The text is small, and seems smaller than prior versions of FMW on macOS but this is the first time I've tested it on macOS Sierra. The display is not hidpi.

macOS 10.12.5 (16F73)
https://github.com/MartinBriza/MediaWriter/releases/download/4.1.0/FedoraMediaWriter-osx-4.1.0.dmg
15.4-inch (1680 x 1050) built-in display
AMD Radeon HD 6750M 1024 MB
![screen shot 2017-07-02 at 3 21 44 pm](https://user-images.githubusercontent.com/10091077/27773618-e2f7ad9a-5f3a-11e7-87fa-5109e17f7bc5.png)

**Comment by MartinBriza** [comment]
Sorry for replying so late. I'm aware of this. For some reason, the font sizes are handled in a different way on macOS. I'll have to change the way font sizes are handled in the whole app so it looks the same everywhere.
