### ISSUE TITLE
Windows 10, flash drive is not writable

### ISSUE THREAD

**Issue by pwl4909** [FedoraQt/MediaWriter#96]
Hello, 

The following error was given for two different flash drives. Using the preset Fedora Workstation, and then a custom image using the downloaded iso. The drives were also set back to factory default using Fedora Media Writer several times. 

Thank you for any help. 

![image](https://user-images.githubusercontent.com/6242248/28098192-e4efd038-6682-11e7-8fdb-30a63b3e6a7f.png)

**Comment by squimrel** [comment]
Only the "Access is denied." error is relevant.

I'd guess that either:
* you don't have permission.
* another program already uses the disk.
* diskpart holds on to the disk for longer than expected.
* Windows does something else that's weird.

**Comment by pwl4909** [comment]
The drive becomes undetected, so I can no longer view what is inside. After
plugging back in FMW recognizes the drive as already having a live
partition on it. At this point I restored to factory default and tried
again. I am wondering if the live partition was successful and ran into a
snag at the end.

Would there be a safe way to verify the flash drive? would there be any
risk in trying to boot from the flash drive?

**Comment by squimrel** [comment]
It breaks most likely just after it "cleaned" the drive and before anything gets written to it.
From Windows you can not manually verify the drive but it's definitely broken anyways.
There's no risk in trying to boot from the flash drive.

Only the "Access is denied." error is relevant. (The error handling is messed up after that point that's why you get multiple errors.)

> I'd guess that either:
>
>    * you don't have permission.
>    * another program already uses the disk.
>    * diskpart holds on to the disk for longer than expected.
>    * Windows does something else that's weird.

Generic Windows debugging as always:

* Reboot
* Make sure that the drive is not mounted.
* Make sure nothing else is running on the system apart from FMW and System32 foo.
* Try the same flash drive on another Windows machine to see if the error persists.
* Make sure to scan your System for Viruses if none of the above helps.

**Comment by mihawk90** [comment]
This seems to be a bigger issue. Rufus has the same issue when writing in ISO mode. Writing the ISO Image in DD Mode did work perfectly fine though. So this seems to be an issue with how Windows 10 handles things differently.

**Comment by squimrel** [comment]
What exactly do you suspect do be the issue? 

What's DD and ISO mode?
How Windows 10 handles what differently?

**Comment by MartinBriza** [comment]
That's strange because FMW basically uses a DD-like approach to writing the iso to the flash drive. Are you sure the drive is alright? That means, can you use it as a regular flash drive, write and then read data successfully to/from it?

**Comment by pwl4909** [comment]
Yes I can access the drive normally, I have also attempted this with a
different flash drive with the same result and the flash drives are
different as in not the same brand.

Additionally I have tried this on a different windows 10 computer with the
same result.

**Comment by darrenbarklie** [comment]
+1 for this exact same problem.

Win 10 setup that I previously managed to successfully installed F25 without a hitch.  Attempting to clean install F26 and I hit the above issues, with multiple USB drives, fresh installs of the MediaWriter and generic Windows debugging precautions.  No  FedoraMediaWriter.log is produced.

**Comment by tsssystems** [comment]
Same issues with both a 64GB corsair originally formatted as ExFAT and a 2GB giveaway drive originally formatted as FAT32. In both cases after FMW fails the drive shows up in W10 disk management as "unallocated". Reformatting makes the flash drive usable again by everything (except FMW).

Will just download the 64bit ISO and burn it to DVD...

**Comment by tsssystems** [comment]
Same issues with both a 64GB corsair originally formatted as ExFAT and a 2GB giveaway drive originally formatted as FAT32. In both cases after FMW fails the drive shows up in W10 disk management as "unallocated". Reformatting makes the flash drive usable again by everything (except FMW).

Will just download the 64bit ISO and burn it to DVD...

**Comment by mihawk90** [comment]
> What exactly do you suspect to be the issue?

Honestly, no idea. Just pointing out that it doesn't seem to be MediaWriter itself, but something underneath? I haven't looked at any code so really no idea, just thought that pointing a direction might help :)

> Are you sure the drive is alright?

Brand new drive fresh out the box, never been formatted before. And after I tried and failed with MediaWriter it worked fine with Rufus, at least the writing, I didn't get the time to try the booting part yet.

**Comment by pwl4909** [comment]
I was able to install Ubuntu properly from the flash drive, I plan on
trying FMW this weekend with the previous version of Fedora to further
isolate the issue. If no luck with that attept it from ubuntu.

**Comment by pwl4909** [comment]
I was able to successfully install Fedora 25, using FMW onto the same 4GB flash drive that was giving me issues with 26 on Windows 10. I would have to think that means something with 26 is messing things up. I admittedly have limited knowledge of what is going on under the hood here.

**Comment by kaiyoma** [comment]
I'm getting a very similar error on Windows 10:

![error](https://user-images.githubusercontent.com/10719780/31471880-002e60ca-aea0-11e7-8cf9-590cf3f9c58c.png)

At this point, my USB drive doesn't show up in Windows Explorer anymore (but it does show up in Disk Management). I've tried every combination of ejecting and unmounting and restoring, but I always get this error. If I restart the program with this drive plugged in, it seems to recognize the fact that the drive has already been written:

![message](https://user-images.githubusercontent.com/10719780/31471925-515ef2de-aea0-11e7-9cc8-974a78c3df84.png)

**Comment by Junaid94** [comment]
So all I did was to turn off my Real-Time Protection.
Settings -> Update & Security -> Windows Defender -> Open Windows Defender Security Center -> Virus & Threat Protection -> Virus & Threat Protection Settings -> Real-Time Protection.
And it worked for me, it started writing the iso to the usb.

**Comment by utebehemoth** [comment]
> So all I did was to turn off my Real-Time Protection.
> Settings -> Update & Security -> Windows Defender -> Open Windows Defender Security Center -> Virus & Threat Protection -> Virus & Threat Protection Settings -> Real-Time Protection.
> And it worked for me, it started writing the iso to the usb.

This worked for me as well.  Thanks for the suggestion.

**Comment by l0c4lh057** [comment]
I'd be interested in a way to get my USB drive working again. Deleting/creating new partitions does not help, I can't format the usb drive or give it a drive letter. Nothing I tried was working. I ended trying Etcher to flash the image on the usb drive and the two drives I tried to use with Media Writer could not be written to by Etcher either, but a third one was working perfectly fine. Now I have no clue how to get the two usb drives working again...

**Comment by sbhattarai5** [comment]
For making my usb work again, I used a third party app called MiniTool partition. I cleaned the disk with the app and initialize with GPT option. It was working again. I'm not sure why I'm getting error for installing linux using fedora media writer.

**Comment by maxmod** [comment]
which i stuck used format usb to clean all partition than fedoraqt work here the utility for windows https://bit.ly/3oBO5JO

**Comment by ljr55555** [comment]
The solution provided by Junaid94 above worked for me as well -- Windows 10 w. latest patches, latest FMC, and Fedora 36 ISO is _finally_ on my removable disk! 

> So all I did was to turn off my Real-Time Protection. Settings -> Update & Security -> Windows Defender -> Open Windows Defender Security Center -> Virus & Threat Protection -> Virus & Threat Protection Settings -> Real-Time Protection. And it worked for me, it started writing the iso to the usb.

**Comment by escalonn** [comment]
this problem is affecting me, on windows 10. the indicated fix does not change the results. rufus works without any trouble.

**Comment by greenrd** [comment]
Rebooting and running Media Writer as Administrator worked for me. Not sure which part was the important part.
